### ISSUE TITLE
Got errors when start a project with tabs template

### ISSUE THREAD

**Issue by fantasizer** [driftyco/ionic#10149]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0
ios-sim version: 4.1.1
OS: macOS Sierra
Node Version: v6.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```
insert the output from ionic info here
```
ionic start wechat tabs --V2 -i
Creating an Ionic app in /Users/xyqu/RD/mygithub/apps/wechat based on the tabs template.

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
Installing npm packages (may take a minute or two)...
add to body class: platform-ios
Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip
Error updating config.xml file: TypeError: packageName.replace is not a function
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:869:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/ionic/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/ionic/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/usr/local/lib/node_modules/ionic/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:503:31)

Relative information from the forum which post by another guy:
https://forum.ionicframework.com/t/problem-when-start-the-app/76292

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1873
