### ISSUE TITLE
3rd Party Library “cordova-plugin-ms-azure-mobile-apps” not getting recognized in my Ionic 2 app

### ISSUE THREAD

**Issue by paragw09ckp** [driftyco/ionic#10310]
**Ionic version:**  (check one with "x")
[X ] **2.0.0**

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
I added "**cordova-plugin-ms-azure-mobile-apps**" library/module to my project and after importing "**WindowsAzure**" from it, I wrote the following line of code to connect to my Microsoft Azure Mobile Apps Backend:

**pushClient = new WindowsAzure.MobileServiceClient('https://myazuremobileapp.azurewebsites.net');**

I run my app using "ionic serve" to run it in my Chrome browser. At this point, I get a **Runtime Error** as below:

```
**
Runtime Error
Cannot find module "cordova-plugin-ms-azure-mobile-apps"
Stack
Error: Cannot find module "cordova-plugin-ms-azure-mobile-apps"
    at Object.<anonymous> (http://localhost:8100/build/main.js:114165:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29990:72)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:114006:79)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29966:100)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:113629:71)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
**
```

The same happens on my Android phone when run the app on phone using "**ionic run android**". I get the same exact error.

**Expected behavior:**
If all goes well, the "**client**" object/variable should have reference to my Microsoft Azure Mobile Apps Backend. Then using that reference I can register my phone for receiving Push Notifications.

**Steps to reproduce:**
1. Create a base Ionic 2 project as **ionic start azuretestapp sidemenu --v2 --ts**

2. Add the required plugin using following command: (You can use **npm install --save** also for the same)
```
        ionic plugin add cordova-plugin-ms-azure-mobile-apps --save
```
3. In the base project, in app.component.ts file, write following import statement:

        import { WindowsAzure } from 'cordova-plugin-ms-azure-mobile-apps';

4. Add a variable in MyApp class as below:

```
           pushClient: any = null;
```

5. In the base project, in app.component.ts file, add the following in **initializeApp()** method:

```
         this.pushClient = new WindowsAzure.MobileServiceClient('https://myazuremobileapp.azurewebsites.net');
```

The complete **initializeApp()** method should look like this:

```
          initializeApp() {
              this.platform.ready().then(() => {
               // Okay, so the platform is ready and our plugins are available.
               // Here you can do any higher level native things you might need.
              StatusBar.styleDefault();
              Splashscreen.hide();

              this.pushClient = new WindowsAzure.MobileServiceClient('https://myazuremobileapp.azurewebsites.net');
          });
  } 
```

6. Run command "**ionic serve**" and you will get the error in your browser window.

**Other information:**
**After trying to fix this for 2 days now, I believe this is Ionic 2 specific problem. I am saying this because I am successfully able to use the same "cordova-plugin-ms-azure-mobile-apps" from a regular HTML/JavaScrip project.**

The Stacktrace is:
```
**
Runtime Error
Cannot find module "cordova-plugin-ms-azure-mobile-apps"
Stack
Error: Cannot find module "cordova-plugin-ms-azure-mobile-apps"
    at Object.<anonymous> (http://localhost:8100/build/main.js:114165:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29990:72)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:114006:79)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29966:100)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:113629:71)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
**
```

I have also posted this issue on Stackoverflow, here is the link with complete description:

http://stackoverflow.com/questions/42016964/3rd-party-library-cordova-plugin-ms-azure-mobile-apps-not-getting-recognized-i

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#707
