### ISSUE TITLE
RangeError: Maximum call stack size exceeded error with Angular 2 and Ionic 2

### ISSUE THREAD

**Issue by moumitabala** [driftyco/ionic#10352]
I'm new to Angular 2 while I'm calling an external library from my angular component its returning this error:
RangeError: Maximum call stack size exceeded
    at Dataset.PriceChart.Dataset.Dataset.find (http://localhost:8100/build/main.js:109239:23)
    at Dataset.PriceChart.Dataset.Dataset.fetch (http://localhost:8100/build/main.js:109211:26)
    at PriceChart.update (http://localhost:8100/build/main.js:107920:33)
    at http://localhost:8100/build/main.js:107848:34
    at Dataset.PriceChart.Dataset.Dataset.fetch (http://localhost:8100/build/main.js:109212:24)
    at PriceChart.parseData (http://localhost:8100/build/main.js:107846:30)
    at PriceChart.run (http://localhost:8100/build/main.js:107948:34)
    at Dataset.PriceChart.Dataset.Dataset.fetch (http://localhost:8100/build/main.js:109212:24)
    at PriceChart.update (http://localhost:8100/build/main.js:107920:33)
    at http://localhost:8100/build/main.js:107848:34

I'm using angular 2.2.1 and Ionic framework 2.0.0-rc.5

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
