### ISSUE TITLE
Loading does not appear when .present() is called again

### ISSUE THREAD

**Issue by rephchunhoong** [driftyco/ionic#10586]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Loading screen does not reappear for second time, unless reinitialized.

**Expected behavior:**
Loading screen should be able to display without any re-initialization. 

**Steps to reproduce:**
Redisplay the loading screen.

**Related code:**
**Typescript**
```
constructor() {
  this.loading_content = `<!-- Some content -->`;
  this.loading = this.loadingCtrl.create({
       spinner: 'hide',
       content: this.loading_content,
       duration: 3000
  });
}
showLoading() {    
  this.loading.present();
}
```

**HTML**
`<button ion-button (click)="showLoading()">Show</button>`

**Other information:**

**Logcat**
```
02-28 14:30:18.686: I/chromium(26711): [INFO:CONSOLE(18)] "EXCEPTION: Cannot read property 'nativeElement' of null", source: file:///android_asset/www/build/main.js (18)
02-28 14:30:18.686: I/chromium(26711): [INFO:CONSOLE(18)] "ORIGINAL STACKTRACE:", source: file:///android_asset/www/build/main.js (18)
02-28 14:30:18.687: I/chromium(26711): [INFO:CONSOLE(18)] "TypeError: Cannot read property 'nativeElement' of null
02-28 14:30:18.687: I/chromium(26711):     at e.init (file:///android_asset/www/build/main.js:91:14988)
02-28 14:30:18.687: I/chromium(26711):     at e._trnsStart (file:///android_asset/www/build/main.js:17:30067)
02-28 14:30:18.687: I/chromium(26711):     at e._trnsStart (file:///android_asset/www/build/main.js:17:29726)
02-28 14:30:18.687: I/chromium(26711):     at e.start (file:///android_asset/www/build/main.js:11:3421)
02-28 14:30:18.687: I/chromium(26711):     at e._transition (file:///android_asset/www/build/main.js:17:29872)
02-28 14:30:18.687: I/chromium(26711):     at e._postViewInit (file:///android_asset/www/build/main.js:17:28023)
02-28 14:30:18.687: I/chromium(26711):     at e._viewTest (file:///android_asset/www/build/main.js:17:29224)
02-28 14:30:18.687: I/chromium(26711):     at e._nextTrns (file:///android_asset/www/build/main.js:17:26171)
02-28 14:30:18.687: I/chromium(26711):     at e._queueTrns (file:///android_asset/www/build/main.js:17:25752)
02-28 14:30:18.687: I/chromium(26711):     at e.insertPages (file:///android_asset/www/build/main.js:17:23734)", source: file:///android_asset/www/build/main.js (18)
02-28 14:30:18.693: I/chromium(26711): [INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'nativeElement' of null", source: file:///android_asset/www/build/main.js (11)
02-28 14:30:18.700: E/NONE(26711): Uncaught Exception: Uncaught TypeError: Cannot read property 'nativeElement' of null at (compiled_code):11

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.4.0
Xcode version: Not installed
```

**Comment by ZiFFeL1992** [comment]
Check the documentation: http://ionicframework.com/docs/v2/api/components/loading/LoadingController/

**The note** blockquote under Dismissing section.

**Comment by manucorporat** [comment]
@ZiFFeL1992 exactly

and upcoming release will improve the error message when reusing pages!
