### ISSUE TITLE
error while ionic run android --prod

### ISSUE THREAD

**Issue by abmnukmr** [driftyco/ionic#10698]
01:48:48]  build prod failed: Unexpected value 'QRCodeModule' imported by the module 'AppModule' 
[01:48:48]  ionic-app-script task: "build" 
[01:48:48]  Error: Unexpected value 'QRCodeModule' imported by the module 'AppModule' 
Error: Unexpected value 'QRCodeModule' imported by the module 'AppModule'
    at E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:14078:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:14063:46)
    at E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:12865:47
    at Array.forEach (native)
    at analyzeModules (E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:12864:17)
    at OfflineCompiler.analyzeModules (E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:12889:18)
    at CodeGenerator.codegen (E:\ionic app\ionicc1\node_modules\@angular\compiler-cli\src\codegen.js:121:47)
    at Object.runCodegen (E:\ionic app\ionicc1\node_modules\@ionic\app-scripts\dist\aot\codegen\codegen-ng22.js:15:26)
    at Object.doCodegen (E:\ionic app\ionicc1\node_modules\@ionic\app-scripts\dist\aot\codegen.js:6:31)

**Comment by FlashGordon95** [comment]
Hi there!
This doesn't really look like a bug but more so a support request. You might be better served in the Ionic Slack. 
That being said the error suggests one of the following:
You had something (Page or provider maybe) and deleted it but forgot to remove it from the app.module.ts 
Or the module your referencing "QRCodeModule" is not being referenced correctly. Could possible be the '../../path/path' part in your input statement.

**Comment by rapropos** [comment]
If it's the library I think it is, it needs some massaging to be compatible with current versions of Angular. See [this forum thread](https://forum.ionicframework.com/t/qr-code-generator-doesnt-work-properly/77372/).

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
