### ISSUE TITLE
Ionic 2 upgrade from 2.0 to 2.2.0 white screen on android & storage error on serve

### ISSUE THREAD

**Issue by keithmichelson** [driftyco/ionic#10743]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**

After upgrading all files in package.json, I get a white screen on android and on serve I get a storage error. I am on Storage 2.0.0.  

**Expected behavior:**

Everything worked fine before

**Steps to reproduce:**

Ionic 2 upgrade from 2.0 to 2.2.0

**Related code:**

```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "Test: An Ionic project"
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.1 Build version 8B62

---- and when running ionic serve

Runtime Error
Can't resolve all parameters for Storage: (?).
Stack
Error: Can't resolve all parameters for Storage: (?).
    at v (http://localhost:8102/build/polyfills.js:3:4864)
    at SyntaxError.BaseError [as constructor] (http://localhost:8102/build/main.js:128242:27)
    at new SyntaxError (http://localhost:8102/build/main.js:12705:16)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:8102/build/main.js:27515:31)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:8102/build/main.js:27390:26)
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:8102/build/main.js:27378:21)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:8102/build/main.js:27620:40)
    at http://localhost:8102/build/main.js:27578:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:8102/build/main.js:27545:19)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8102/build/main.js:27229:50)
    at JitCompiler._loadModules (http://localhost:8102/build/main.js:73171:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:8102/build/main.js:73131:52)
    at JitCompiler.compileModuleAsync (http://localhost:8102/build/main.js:73097:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:8102/build/main.js:53481:25)
Ionic Framework: 2.2.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 7.3.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

**Comment by keithmichelson** [comment]
Working now after running the command mentioned on an earlier upgrade, just doing an npm install after deleting wouldn't work.
npm install @ionic/storage@2.0.0 --save --save-exact

Getting a warning that this has no exported member.
import { IonicStorageModule } from '@ionic/storage';

Also the images inside ion-card are now sized differently after update.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
