### ISSUE TITLE
"ReferenceError: NPObject deleted

### ISSUE THREAD

**Issue by ZhuShouyu** [driftyco/ionic#10829]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have define a custom plugin, it worked fine in iOS, but for android, it only worked fine for this situation: you have no _iframe_ elements in your page, or the page with _iframe_ has not appeared yet. If the page with _iframe_ has appeared,  you call the cordova plugin, then you  will get error like below
```
I/chromium(14138): [INFO:CONSOLE(78165)] "ORIGINAL STACKTRACE:", source: file:///android_asset/www/build/main.js (78165)
D/SystemWebChromeClient(14138): file:///android_asset/www/build/main.js: Line 78166 : ReferenceError: NPObject deleted
D/SystemWebChromeClient(14138):     at androidExec (file:///android_asset/www/cordova.js:967:40)
D/SystemWebChromeClient(14138):     at Object.exports.openURL (file:///android_asset/www/plugins/com.siamlian.openinnativ
ebrowser/www/OpenInNativeBrowser.js:5:5)
D/SystemWebChromeClient(14138):     at AboutPage.openEmailInNativeBrowser (file:///android_asset/www/build/main.js:84613:
33)
D/SystemWebChromeClient(14138):     at DebugAppView.View_AboutPage0.handleEvent_9 (/AppModule/AboutPage/component.ngfacto
ry.js:174:34)
D/SystemWebChromeClient(14138):     at DebugAppView.<anonymous> (file:///android_asset/www/build/main.js:136306:37)
D/SystemWebChromeClient(14138):     at HTMLButtonElement.<anonymous> (file:///android_asset/www/build/main.js:58108:53)
D/SystemWebChromeClient(14138):     at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:10284)
D/SystemWebChromeClient(14138):     at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3869
2:37)
D/SystemWebChromeClient(14138):     at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:10220)
D/SystemWebChromeClient(14138):     at e.runTask (file:///android_asset/www/build/polyfills.js:3:7637)
D/SystemWebChromeClient(14138):     at HTMLButtonElement.invoke (file:///android_asset/www/build/polyfills.js:3:11397)
I/chromium(14138): [INFO:CONSOLE(78166)] "ReferenceError: NPObject deleted
```
**Expected behavior:**

Plugin should worked fine 
**Steps to reproduce:**

**Related code:**

```
<ion-header>
    <ion-navbar>
        <ion-title>
            About
        </ion-title>
        <ion-buttons end>
            <button ion-button (click)="takePhoto()" class="right-bar-button">Plugin</button>
        </ion-buttons>
    </ion-navbar>
</ion-header>
<ion-content padding>
    <iframe src="http://www.baidu.com" width="100%" height="100%"></iframe>
</ion-content>
```
```
takePhoto() {
    let options = {
        maximumImagesCount: 1,
        width: 300,
        height: 300,
        quality : 75
      };
    ImagePicker.getPictures(options);
```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
bash-3.2$ ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.6
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by ZhuShouyu** [comment]
I  don't know why, when i changed the JDK from 1.8 to 1.7, It's OK, worked fine.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
