### ISSUE TITLE
Some errors on test migration to ionic3, ionic-cli 3.beta4, ionic-angular 2.2.0-201703211421 and angular4 rc.5

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10863]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I try to use your latest ionic angular version which you merged yesterday with the 3.0 branch, so I'm trying to migrate my app on angular4 rc.5
By the way, I'm interested to beta test your new ionic3 with now IonicPage (DeepLink) over ionic4 :+1: 

There are two bugs: 
1) the Custom Error Handler does not work as in version 2, on declaring the provider for Custom Error Handler in app.component.ts
`{ provide: ErrorHandler, useClass: LanthingsErrorHandler, deps: [ ToastController ] },`
we get this error
```
polyfills.js:3 Unhandled Promise rejection: Class constructor IonicErrorHandler cannot be invoked without 'new' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Class constructor IonicErrorHandler cannot be invoked without 'new'(…) TypeError: Class constructor IonicErrorHandler cannot be invoked without 'new'
    at new LanthingsErrorHandler (http://localhost:8100/build/main.js:108840:28)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:244:26)
    at AppModuleInjector.NgModuleInjector.create (http://localhost:8100/build/main.js:3591:76)
    at NgModuleFactory.create (http://localhost:8100/build/main.js:3564:18)
    at http://localhost:8100/build/main.js:4760:61
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14738)
    at Object.onInvoke (http://localhost:8100/build/main.js:4151:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14678)
    at n.run (http://localhost:8100/build/polyfills.js:3:9950)
    at NgZone.run (http://localhost:8100/build/main.js:4020:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:8100/build/main.js:4758:23)
    at http://localhost:8100/build/main.js:4800:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14738)
    at n.run (http://localhost:8100/build/polyfills.js:3:9950)
    at http://localhost:8100/build/polyfills.js:3:6647
```

2) the other error we get is on a Custom HTTPService 

```
export function httpFactory(backend: XHRBackend, options: RequestOptions, platform: Platform) {
  return new HttpService(backend, options, platform);
}

...
providers: [
      {
          provide: HttpService,
          useFactory:  httpFactory,
          deps: [XHRBackend, RequestOptions, Platform ]
        },
```

we get this error

```
polyfills.js:3 Unhandled Promise rejection: No provider for XHRBackend! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for XHRBackend!(…) Error
    at y (http://localhost:8100/build/polyfills.js:3:7590)
    at injectionError (http://localhost:8100/build/main.js:1426:86)
    at noProviderError (http://localhost:8100/build/main.js:1464:12)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/main.js:2908:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/main.js:2947:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/main.js:2879:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/main.js:2748:21)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:206:99)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:211:95)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:442:51)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:8100/build/main.js:3610:44)
    at resolveDep (http://localhost:8100/build/main.js:10702:45)
    at createClass (http://localhost:8100/build/main.js:10570:32)
    at createDirectiveInstance (http://localhost:8100/build/main.js:10386:37)
    at createViewNodes (http://localhost:8100/build/main.js:11712:49)
```
**Expected behavior:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0-201703211421
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.0
    Xcode version: Not installed
```

**Comment by AmitMY** [comment]
Getting this error also on updated ionic version `2.3.0-201703231941`
> Unhandled Promise rejection: Class constructor IonicErrorHandler cannot be invoked without 'new' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Class constructor IonicErrorHandler cannot be invoked without 'new'

@mburger81 Did you find a way around it by any chance?

**Comment by mburger81** [comment]
@AmitMY no, at the moment we are not able to continue the migration. Perhaps @brandyscarney can help us on this.

But I think this should be a problem of angular4, so didn't follow angular4 and I don't know what is changed and which breaking changes are there.
But The ionic team for sure have to implement this new, so perhaps they can help as figure it out at this point. :smile:

**Comment by AmitMY** [comment]
@mburger81 Thanks. I removed the error handler, and everything worked. It was great to see how v3 would look like, as there are some breaking changes (I used `ion-grid` a lot, and now it behaves differently than before)

**Comment by mburger81** [comment]
@AmitMY I also use very heavy ion-grid, so this is for now not working as expected? So I have to wait for migration until the team resolves this issue.

I need urgent v3 for lazy-loading, we all need v3 for lazy-loading :smile: 

Perhaps you can open an new issue for this

**Comment by brandyscarney** [comment]
@mburger81 Thanks! We'll take a look at the error handler, cc @danbucholtz 

The new grid was introduced in the `2.1.0` release but we didn't remove the old grid's functionality. I just went ahead and removed the old grid with this release (https://github.com/driftyco/ionic/commit/19c36deea30f4134b6c7f9d22429e3d5794aef57) since it is considered a breaking change. 🙂  

Please see this blog for more information on the new grid: http://blog.ionic.io/build-awesome-desktop-apps-with-ionics-new-responsive-grid/

**Comment by mburger81** [comment]
@brandyscarney I think @AmitMY is saying the  new grid  have problems with ionic3  / angular4, so this could be a bug.

**Comment by brandyscarney** [comment]
@mburger81 @AmitMY Oh, please let me know if that is the case. I haven't seen any issues with it. 🙂

**Comment by AmitMY** [comment]
@brandyscarney Mostly, I meant the `width-x / col-x` changes, but I did have a bug because of the new padding of the grid class `5px` which made stuff move drastically (not 5px).
I managed to fix it by adding `no-padding` to `ion-grid`, and a small css adjustment. 

Thanks for linking the blog post!

**Comment by AmitMY** [comment]
Update: Issue still exists in `2.3.0-201703241812` using angular `4.0.0`

**Comment by AmitMY** [comment]
See https://github.com/angular/angular/issues/15326
It seems to be an issue with the transpiling to ES5 that causes this..

**Comment by jgw96** [comment]
Hello @mburger81 ! Would you mind sharing some more code around your error handler? We are trying to reproduce on our end but cant seem to be able to reproduce the issue.

**Comment by AmitMY** [comment]
@jgw96 Instead of using the `IonicErrorHandler`, do:
```
export class MyErrorHandler extends IonicErrorHandler implements ErrorHandler {
    handleError(error: any): void {
        super.handleError(error);
    }
}
```

And use `MyErrorHandler` instead.

**Comment by jgw96** [comment]
Hey @AmitMY thanks for sharing! So if you want to extend our `IonicErrorHandler` you need to call `super()` in the constructor of `MyErrorHandler`. So if you use this code 
```
export class MyErrorHandler extends IonicErrorHandler implements ErrorHandler {
  constructor() {
    super();
  }

  handleError(error: any) {
    alert(error);
    super.handleError(error);
  }
}
```
It will work. Calling `super()` in the constructor is basically saying "Hey, this class extends another class, so go ahead and give this class access to all the methods of the parent class". Therefore, when you call `super.handleError(error)` in your `handleError` method, it works great (:

**Comment by AmitMY** [comment]
@jgw96 Thanks, it works
I tried the same thing before, but now already updated to `beta.3` so not sure if that is why.

As a note, this code worked before, without a constructor

**Comment by AmitMY** [comment]
Also, just as a note, this behaviour is not correct. When no constructor is given, it automatically goes for super.

Test:
```
class A {
  constructor() { alert() }
}

class B extends A {}

new B();
```

**Comment by mburger81** [comment]
@AmitMY and @jgw96 sorry for my late answer we was busy on finishing some parts on software.

I think @AmitMY is right, why we need to call super(), this should be implicit as in any other language. or not?

@jgw96 I have still the same problem with custom HTTPService,

I can not load the HTTPService as before on angular2/ionic2
This is a part of my code in app.module.ts

```
export function httpFactory(backend: XHRBackend, options: RequestOptions, platform: Platform) {
  return new HttpService(backend, options, platform);
}
@NgModule({
....
providers: [
....
        {
          provide: HttpService,
          useFactory:  httpFactory,
          deps: [XHRBackend, RequestOptions, Platform ]
        },
....
  ]
})
export class AppModule {}
```

The exception is:
```
Runtime Error
No provider for XHRBackend!
Stack
Error
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at injectionError (http://localhost:8100/build/main.js:1512:86)
    at noProviderError (http://localhost:8100/build/main.js:1550:12)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/main.js:3052:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/main.js:3091:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/main.js:3023:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/main.js:2892:21)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:136:99)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:306:95)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:684:51)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:8100/build/main.js:3856:44)
    at resolveDep (http://localhost:8100/build/main.js:11261:45)
    at createClass (http://localhost:8100/build/main.js:11129:32)
    at createDirectiveInstance (http://localhost:8100/build/main.js:10955:37)
    at createViewNodes (http://localhost:8100/build/main.js:12304:49)
```

**Comment by mburger81** [comment]
I found the mistake!!!!

For the HTTP bug I didn't include `HttpModule` in `app.module.ts`, doing this it works now. Now we need this, probably in ionic2 the httpmodule was included out of the box, because this was also needed before I think from angular 2.2.X or 2.4.x

For the problem with the custom ErrorHanlder, now in ionic 3.0.0 it is working out of the box without bug.

So anything is fine :smile: :+1:
