### ISSUE TITLE
rollup failed: ... is not exported by ...

### ISSUE THREAD

**Issue by Michael77** [driftyco/ionic#10914]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a service which exports an interface named Post, and it is imported in several other files. When I run `ionic build android --prod --release` I get the error `rollup failed: 'Post' is not exported by src/app/services/post.service.ts` even though it is exported. This ends the build process.

**Expected behavior:**
There should be no error and the build should complete.

**Related code:**

post.service.ts
```
export interface Post {...};
export interface PostTypes {...};
@Injectable()
export class PostService {...}
```
some.component.ts
```
import {Post, PostService} from "../../services/post.service";
```

**Other information:**

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.10
Node Version: v7.7.3
Xcode version: Not installed
```

**Stack trace:**

```
[17:58:47]  rollup failed: 'Post' is not exported by src/app/services/post.service.ts 
[17:58:47]  ionic-app-script task: "build" 
[17:58:47]  Error: 'Post' is not exported by src/app/services/post.service.ts 
Error: 'Post' is not exported by src/app/services/post.service.ts
    at error (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:7997:2)
    at Module.trace (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:8095:9)
    at ModuleScope.findDeclaration (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:7681:22)
    at Node.bind (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:6733:29)
    at /home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:5291:50
    at Node.eachChild (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:5308:5)
    at Node.bind (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:5291:7)
    at Node.bind (/home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:7207:53)
    at /home/derek/Documents/side_projects/x-mobile/node_modules/rollup/dist/rollup.js:5291:50
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question about an error in your code causing rollup to fail i will urge that you ask this question on our [forum] (https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by Michael77** [comment]
I don't believe that this is an issue with my code because I am able to run ionic serve --prod and that works without errors. The error only occurs when I am building --prod for android. I also tried removing and re-adding the android platform without success.
