### ISSUE TITLE
Broken ionic 3.0.0-beta.3

### ISSUE THREAD

**Issue by maitbayev** [driftyco/ionic#10961]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**
[ x ] **3.0.0-beta.3**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

1. Why ListPageModule isn't declared in https://github.com/driftyco/ionic2-starter-sidemenu/blob/3/src/app/app.module.ts and works without an issue?
2. Why it doesn't work when it's declared?

Error I am getting:
TypeError: undefined is not a function
    at Array.map (native)
    at webpackAsyncContext (http://localhost:8100/build/main.js:44886:34)
    at loadAndCompile (http://localhost:8100/build/main.js:76930:35)
    at NgModuleLoader.load (http://localhost:8100/build/main.js:76895:83)
    at ModuleLoader.load (http://localhost:8100/build/main.js:56145:44)
    at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:31057:39)
    at DeepLinker.getComponentFromName (http://localhost:8100/build/main.js:31040:25)
    at getComponent (http://localhost:8100/build/main.js:33516:23)
    at convertToView (http://localhost:8100/build/main.js:33534:16)
    at NavControllerBase.push (http://localhost:8100/build/main.js:43538:103)
    at Nav.ngAfterViewInit (http://localhost:8100/build/main.js:49795:25)
    at callProviderLifecycles (http://localhost:8100/build/main.js:11382:18)
    at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11357:13)
    at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11341:17)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12359:5)

**Comment by Manduro** [comment]
https://github.com/driftyco/ionic-app-scripts/issues/848

**Comment by jgw96** [comment]
Hello @maitbayev , would you mind posting an example of your issue please? I think i understand the issue here, but I would love if you could show an example.

**Comment by maitbayev** [comment]
Oops, its updated. Seems like to lazy load we shouldn't declare. We need to declare if the component is loaded.

**Comment by peterpeterparker** [comment]
@maitbayev what what what? I've got the same error right now, could you elaborate a bit?

**Comment by maitbayev** [comment]
@peterpeterparker are you adding your generated modules "imports" in app.module.ts and trying to navigate with name?

**Comment by peterpeterparker** [comment]
@maitbayev yep, I only import one module in import (the first page of the app) and I converted all my push, setRoot and modal.create to use string names

**Comment by maitbayev** [comment]
I think the first page should not use a string name. See: https://github.com/driftyco/ionic2-starter-sidemenu/commit/818d0ed3cc4137e6f81ee27950c1d084ae5689a5

**Comment by peterpeterparker** [comment]
@maitbayev I think you are right but I don't understand why it's working in the conference-app (see https://github.com/driftyco/ionic-conference-app/blob/lazy-load/src/app/app.component.ts)

anyway that didn't solve my issue :( I've got the feeling I may have some problems with the loading of the child-/sub-components

**Comment by peterpeterparker** [comment]
I opened a new issue because I was unable to solve it
