### ISSUE TITLE
localhost refused to connect <ionic 2>

### ISSUE THREAD

**Issue by Danaal** [driftyco/ionic#11008]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x ] support request => 

Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

  ### I submitted this issue twice there but I didn't get any solution and I really need a way to fix it cause I have to submit a project this week , so Sorry for putting this here

**Current behavior:**
I have to run ionic serve  each time to see how the app looks like in the browser after adding codes. 
Even though ionic serve works" generate URL and browser", it also throw some errors
 When I refresh the page, it shows that **localhost refused to connect**.  
**Expected behavior:**
To work like a live reload.. I only need to run ionic serve once then any changes I do in the code will automatically show in the browse .

**ionic serve code:**

```
$ ionic serve

> ionic-hello-world@ ionic:serve C:\Users\dana\MyApp11
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

[22:49:56]  ionic-app-scripts 1.2.5 
[22:49:56]  watch started ...
[22:49:56]  build dev started ...
[22:49:56]  clean started ...
[22:49:56]  clean finished in 6 ms
[22:49:56]  copy started ...
[22:49:56]  transpile started ...
[22:50:05]  transpile finished in 8.47 s
[22:50:05]  preprocess started ...
[22:50:05]  deeplinks started ...
[22:50:05]  deeplinks finished in 8 ms
[22:50:05]  preprocess finished in 8 ms
[22:50:05]  webpack started ...
[22:50:05]  copy finished in 9.12 s
[22:50:18]  webpack finished in 13.78 s
[22:50:18]  sass started ...
[22:50:22]  sass finished in 3.77 s
[22:50:22]  postprocess started ...
[22:50:22]  postprocess finished in 1 ms
[22:50:22]  lint started ...
[22:50:23]  build dev finished in 26.84 s
[22:50:25]  watch ready in 28.54 s
[22:50:25]  dev server running: http://localhost:8100/ 

[22:50:29]  lint finished in 6.90 s

C:\Users\dana\MyApp11\node_modules\tiny-lr\src\server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^

TypeError: Cannot read property 'message' of undefined
    at Server.error (C:\Users\dana\MyApp11\node_modules\tiny-lr\src\server.js:266:52)
    at Socket.<anonymous> (C:\Users\dana\MyApp11\node_modules\tiny-lr\src\server.js:217:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:346:10)
    at onwrite (_stream_writable.js:364:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:471:13)
    at Socket._destroy (net.js:512:3)
    at Socket._writeGeneric (net.js:715:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address" "0.0.0.0" "--port" "8100
" "--livereload-port" "35729"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dana\MyApp11\npm-debug.log

```

**Other information:**
I tried to remove npm modulus folder then run npm install as I found in other issues but it didn't work for me 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.10.1
Xcode version: Not installed

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2053
