### ISSUE TITLE
App freezes when using system Chrome for Android < 2.4

### ISSUE THREAD

**Issue by cmorbitzer** [driftyco/ionic#11039]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using Android < 2.4 (tested on 2.2 and 2.3) the app freezes before firing platform onready. The log shows:
```
[ 04-04 00:56:16.791  3835: 3835 D/SystemWebChromeClient ]
file:///android_asset/www/build/main.js: Line 76613 : EXCEPTION: Error in ./ConferenceApp class ConferenceApp - inline template:92:11 caused by: Object [object DOMWindow] has no method '__zone_symbol__requestAnimationFrame'

[ 04-04 00:56:16.791  3835: 3835 E/Web Console ]
EXCEPTION: Error in ./ConferenceApp class ConferenceApp - inline template:92:11 caused by: Object [object DOMWindow] has no method '__zone_symbol__requestAnimationFrame' at file:///android_asset/www/build/main.js:76613

[ 04-04 00:56:16.791  3835: 3835 D/SystemWebChromeClient ]
file:///android_asset/www/build/main.js: Line 76615 : ORIGINAL EXCEPTION: Object [object DOMWindow] has no method '__zone_symbol__requestAnimationFrame'

[ 04-04 00:56:16.791  3835: 3835 E/Web Console ]
ORIGINAL EXCEPTION: Object [object DOMWindow] has no method '__zone_symbol__requestAnimationFrame' at file:///android_asset/www/build/main.js:76615

[ 04-04 00:56:16.791  3835: 3835 D/SystemWebChromeClient ]
file:///android_asset/www/build/main.js: Line 76618 : ORIGINAL STACKTRACE:

[ 04-04 00:56:16.791  3835: 3835 E/Web Console ]
ORIGINAL STACKTRACE: at file:///android_asset/www/build/main.js:76618

[ 04-04 00:56:16.791  3835: 3835 D/SystemWebChromeClient ]
file:///android_asset/www/build/main.js: Line 76619 : TypeError: Object [object DOMWindow] has no method '__zone_symbol__requestAnimationFrame'
    at Platform.raf (file:///android_asset/www/build/main.js:1476:59)
    at MDTransition.play (file:///android_asset/www/build/main.js:10160:18)
    at Nav._transitionStart (file:///android_asset/www/build/main.js:44090:28)
    at MDTransition._trnsStart (file:///android_asset/www/build/main.js:44007:19)
    at MDTransition.start (file:///android_asset/www/build/main.js:20177:33)
    at Nav._transitionInit (file:///android_asset/www/build/main.js:44021:24)
    at Nav._postViewInit (file:///android_asset/www/build/main.js:43870:14)
    at Nav._viewTest (file:///android_asset/www/build/main.js:43966:25)
    at Nav._nextTrns (file:///android_asset/www/build/main.js:43709:25)
    at Nav._queueTrns (file:///android_asset/www/build/main.js:43659:14)
    at Nav._setPages (file:///android_asset/www/build/main.js:43586:21)
    at Nav.setRoot (file:///android_asset/www/build/main.js:43560:21)
    at Nav.root (file:///android_asset/www/build/main.js:61833:22)
    at Wrapper_Nav.check_root (eval at evalExpression (file:///android_asset/www/build/main.js:107968:12))
    at DebugAppView.detectChangesInternal (eval at evalExpression (file:///android_asset/www/build/main.js:107968:12))

[ 04-04 00:56:16.791  3835: 3835 E/Web Console ]
TypeError: Object [object DOMWindow] has no method '__zone_symbol__requestAnimationFrame'
    at Platform.raf (file:///android_asset/www/build/main.js:1476:59)
    at MDTransition.play (file:///android_asset/www/build/main.js:10160:18)
    at Nav._transitionStart (file:///android_asset/www/build/main.js:44090:28)
    at MDTransition._trnsStart (file:///android_asset/www/build/main.js:44007:19)
    at MDTransition.start (file:///android_asset/www/build/main.js:20177:33)
    at Nav._transitionInit (file:///android_asset/www/build/main.js:44021:24)
    at Nav._postViewInit (file:///android_asset/www/build/main.js:43870:14)
    at Nav._viewTest (file:///android_asset/www/build/main.js:43966:25)
    at Nav._nextTrns (file:///android_asset/www/build/main.js:43709:25)
    at Nav._queueTrns (file:///android_asset/www/build/main.js:43659:14)
    at Nav._setPages (file:///android_asset/www/build/main.js:43586:21)
    at Nav.setRoot (file:///android_asset/www/build/main.js:43560:21)
    at Nav.root (file:///android_asset/www/build/main.js:61833:22)
    at Wrapper_Nav.check_root (eval at evalExpression (file:///android_asset/www/build/main.js:107968:12))
    at DebugAppView.detectChangesInternal (eval at evalExpression (file:///android_asset/www/build/main.js:107968:12)) at file:///android_asset/www/build/main.js:76619

[ 04-04 00:56:16.791  3835: 3835 D/SystemWebChromeClient ]
file:///android_asset/www/build/main.js: Line 76622 : ERROR CONTEXT:

[ 04-04 00:56:16.791  3835: 3835 E/Web Console ]
ERROR CONTEXT: at file:///android_asset/www/build/main.js:76622

[ 04-04 00:56:16.791  3835: 3835 D/SystemWebChromeClient ]
file:///android_asset/www/build/main.js: Line 76623 : [object Object]

[ 04-04 00:56:16.791  3835: 3835 E/Web Console ]
[object Object] at file:///android_asset/www/build/main.js:76623

```

**Expected behavior:**
This error does not occur and the platform onready event is fired.

**Steps to reproduce:**
Run or emulate the ionic-conference-app on an Android 4.2.2 or 4.3 device with all references to crosswalk or CordovaWebViewEngine removed. Here is the config.xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="io.ionic.conferenceapp" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>Ionic Conference</name>
  <description>
        An Ionic Framework application for the Ionic Conference.
  </description>
  <author email="hi@ionicframework" href="http://ionicframework.com/">
      Ionic Framework Team
  </author>
  <content src="index.html"/>
  <access origin="*"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  <allow-intent href="geo:*"/>
  <allow-navigation href="http://*/*"/>
  <allow-navigation href="tel:*"/>
  <allow-navigation href="mailto:*"/>
  <platform name="android">
    <allow-intent href="market:*"/>
    <icon src="resources/android/icon/drawable-ldpi-icon.png" density="ldpi"/>
    <icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
    <icon src="resources/android/icon/drawable-hdpi-icon.png" density="hdpi"/>
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" density="xhdpi"/>
    <icon src="resources/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi"/>
    <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
    <icon src="resources/android/icon/drawable-xhdpi-icon.png"/>
    <splash src="resources/android/splash/drawable-port-ldpi-screen.png" density="port-ldpi"/>
    <splash src="resources/android/splash/drawable-port-mdpi-screen.png" density="port-mdpi"/>
    <splash src="resources/android/splash/drawable-port-hdpi-screen.png" density="port-hdpi"/>
    <splash src="resources/android/splash/drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
    <preference name="orientation" value="default"/>
    <icon src="resources/ios/icon/icon.png" width="57" height="57"/>
    <icon src="resources/ios/icon/icon@2x.png" width="114" height="114"/>
    <icon src="resources/ios/icon/icon-40.png" width="40" height="40"/>
    <icon src="resources/ios/icon/icon-40@2x.png" width="80" height="80"/>
    <icon src="resources/ios/icon/icon-40@3x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-50.png" width="50" height="50"/>
    <icon src="resources/ios/icon/icon-50@2x.png" width="100" height="100"/>
    <icon src="resources/ios/icon/icon-60.png" width="60" height="60"/>
    <icon src="resources/ios/icon/icon-60@2x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-60@3x.png" width="180" height="180"/>
    <icon src="resources/ios/icon/icon-72.png" width="72" height="72"/>
    <icon src="resources/ios/icon/icon-72@2x.png" width="144" height="144"/>
    <icon src="resources/ios/icon/icon-76.png" width="76" height="76"/>
    <icon src="resources/ios/icon/icon-76@2x.png" width="152" height="152"/>
    <icon src="resources/ios/icon/icon-83.5@2x.png" width="167" height="167"/>
    <icon src="resources/ios/icon/icon-small.png" width="29" height="29"/>
    <icon src="resources/ios/icon/icon-small@2x.png" width="58" height="58"/>
    <icon src="resources/ios/icon/icon-small@3x.png" width="87" height="87"/>
    <splash src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" height="1136"/>
    <splash src="resources/ios/splash/Default-667h.png" width="750" height="1334"/>
    <splash src="resources/ios/splash/Default-736h.png" width="1242" height="2208"/>
    <splash src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" height="2048"/>
    <splash src="resources/ios/splash/Default-Portrait~ipad.png" width="768" height="1024"/>
    <splash src="resources/ios/splash/Default@2x~iphone.png" width="640" height="960"/>
    <splash src="resources/ios/splash/Default~iphone.png" width="320" height="480"/>
  </platform>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="StatusBarStyle" value="default" />
  <preference name="SplashScreen" value="screen"/>
  <preference name="orientation" value="default"/>
  <preference name="SplashMaintainAspectRatio" value="true"/>
  <preference name="FadeSplashScreenDuration" value="300"/>
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <preference name="AutoHideSplashScreen" value="false"/>
  <preference name="SplashScreenDelay" value="3000"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
  <plugin name="cordova-plugin-inappbrowser" spec="~1.4.0"/>
  <plugin name="ionic-plugin-keyboard" spec="~2.2.1"/>
  <plugin name="cordova-plugin-whitelist" spec="1.3.1"/>
  <plugin name="cordova-plugin-console" spec="1.0.5"/>
  <plugin name="cordova-plugin-statusbar" spec="2.2.1"/>
  <plugin name="cordova-plugin-device" spec="1.1.4"/>
  <plugin name="cordova-plugin-splashscreen" spec="~4.0.1"/>
  <engine name="ios" spec="4.3.1"/>
  <engine name="android" spec="6.1.0"/>
</widget>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.3 Build version 8E162


```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We do not support Android 2.x at this time based on [its marketshare](https://developer.android.com/about/dashboards/index.html) of 1% that is steadily decreasing. Sorry for any hassle that causes. Im surprised you even have a device running gingerbread to be honest haha.

**Comment by cmorbitzer** [comment]
I'm sorry, that was a typo in the issue. This issue is happening with 4.3 and 4.2. (anything below ICS)
