### ISSUE TITLE
ionic TABS issue could not find it 

### ISSUE THREAD

**Issue by elversace** [driftyco/ionic#11173]
hey 
after i setup ever codes in app.ts and run the ionic serve in GIT BASH  i got this error : 

Runtime Error
Cannot find module "./pages/tabs/tabs"
Stack
Error: Cannot find module "./pages/tabs/tabs"
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at Object.<anonymous> (http://localhost:8100/build/main.js:104715:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:78239:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:115116:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at http://localhost:8100/build/main.js:140:18
    at http://localhost:8100/build/main.js:143:10

and my confg is : 
Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 6.9.1
OS Platform: Windows 7
Navigator Platform: Win32

any help pleas

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by benmcm1994** [comment]
You should'nt have to create a new app everytime this happens. Its happened to me atleast twice.

**Comment by jinuem** [comment]
Tab Template works fine.. 
When i tried to Add New Page outside of Tab (example Login).. This issue Comes..  How to Fix this?
@jgw96  Any Idea?
