### ISSUE TITLE
Deeplink change default root in ion-nav

### ISSUE THREAD

**Issue by cherSan** [driftyco/ionic#11208]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. Deeplink change default _[root]_ in **ion-nav**
2. Possible to make path like: [host]/#/home/home/home/home/other if home Is a IonicPage and have **ion-nav** tag

**Expected behavior:**
1. **ion-nav [root]** don't  changed with deep links.

**Steps to reproduce:**

Create file like at **Related code**
write path like [host]/#/home/home/home/other

**Related code:**

_**APP**_
**app.component.ts**
```
...
this.rootPage = 'HomePage';
...
```
**app.html**
`<ion-nav [root]="rootPage"></ion-nav>`

**_HOME_**
**home.ts**
```
...
@IonicPage()
...
rootPage: any = 'OtherPage';
...
```
**home.module.ts**
```
...
@NgModule({
  declarations: [HomePage],
  imports: [IonicPageModule.forChild(HomePage)],
  exports: [HomePage]
})
export class HomePageModule {}
```
**home.html**
HOME
<ion-nav [root]="rootPage"></ion-nav>

**_OTHER_**
**other.ts**
```
...
@IonicPage()
...
```
**other.module.ts**
```
...
@NgModule({
  declarations: [OtherPage],
  imports: [IonicPageModule.forChild(OtherPage)],
  exports: [OtherPage]
})
export class OtherPageModule {}
```
**other.html**
`Other`

**Other information:**

_Sometimes there is an error:_

Runtime Error
Cannot read property 'indexOf' of null
Stack
TypeError: Cannot read property 'indexOf' of null
    at NavControllerBase._cleanup (http://localhost:8100/build/main.js:44474:59)
    at NavControllerBase._transitionFinish (http://localhost:8100/build/main.js:44376:18)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14529)
    at Object.onInvoke (http://localhost:8100/build/main.js:4498:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14469)
    at n.run (http://localhost:8100/build/polyfills.js:3:9741)
    at NgZone.run (http://localhost:8100/build/main.js:4367:62)
    at Array.<anonymous> (http://localhost:8100/build/main.js:44324:25)
    at MDTransition.Animation._didFinish (http://localhost:8100/build/main.js:23589:29)
    at MDTransition.Animation._playProgress (http://localhost:8100/build/main.js:22928:18)
    at MDTransition.Animation._playDomInspect (http://localhost:8100/build/main.js:22893:14)
Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 7.6.0
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by chancezeus** [comment]
I have come across a even worse variant.

I have a split pane with 2 side menu's and 1 content (it's meant for (really) large tablets and desktops) and as soon as the deeplink is accessed all three get their root set to the nav target (a tabbed page which should display in the content pane not any of the side panes). This results in some unexpected and unwanted behavior, since the tab pane tries to set the menus to correspond to the current view (this actually happens 3 times, once in each pane). This in turn destroys the tab (nav) controller in the 2 side panes which results in a navcontroller destroyed error error because the actual menus get loaded and these in tern try to send some information to the tab nav controller (using observables).

I would expect that (at least in split view) the nav component would either not listen to the current route (and make the developer responsible for triggering the correct side menu) or that each nav component is targeted separately in the deeplink uri (using a separator symbol which targets each nav item individually)...

**Comment by rudaoshi** [comment]
I met the same problem. Deep link definitely should not change the rootPage. Instead, the deep linked page should be a navigated page from the root page. @jgw96
