### ISSUE TITLE
Multiple http requests returning syntax error

### ISSUE THREAD

**Issue by lukeb2014** [driftyco/ionic#11302]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I try to make two `http get` calls to my REST API the app breaks. The first call goes through and returns my json data, but instead I get...
```
ERROR 
SyntaxError
message: "Unexpected token h"
stack: "SyntaxError: Unexpected token h↵    at Object.parse (native)↵    at Response.Body.json (file:///android_asset/www/build/main.js:40717:25)↵    at MapSubscriber.project (file:///android_asset/www/build/main.js:141236:110)↵    at MapSubscriber._next (file:///android_asset/www/build/main.js:51262:35)↵    at MapSubscriber.Subscriber.next (file:///android_asset/www/build/main.js:15799:18)↵    at XMLHttpRequest.onLoad (file:///android_asset/www/build/main.js:41126:38)↵    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15213)↵    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:4415:37)↵    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15134)↵    at n.runTask (file:///android_asset/www/build/polyfills.js:3:10390)↵    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:16170)"
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: Error
```
 Logs taken from chrome://inspect on an Android device.

**Expected behavior:**

The app should be returning my json data in each `subscribe` function.

**Steps to reproduce:**

Build Ionic app and implement an API connection similar to [this](http://blog.ionic.io/10-minutes-with-ionic-2-calling-an-api/)
Request twice.

Whichever request I put first works.

**Related code:**

```typescript
// after importing Http, Headers, RequestOptions, rxjs/add/operator/map, etc
// headerOptions has my API key
this.http.get(`${url}/my-page`, headerOptions).map(res=>res.json()).subscribe(data => {
    // do stuff with data
    console.log(data);
});

// someplace else anywhere in app afterwards
this.http.get(`${url}/my-page-2`, headerOptions).map(res=>res.json()).subscribe(data => {
    // do stuff with data
    console.log(data);
});
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by rapropos** [comment]
Instead of blindly calling `json()`, you could try logging the entire response to see if it gives you any clues. I would suspect the problem lies with the backend service.

**Comment by lukeb2014** [comment]
Will do. I'll let you know if it seems to be backend or frontend.

**Comment by lukeb2014** [comment]
First call:
```
e
_body: "{↵    "specials": [↵         {↵            "id": "8fab1fc0-aad6-4200-8397-378b8a1c02b5",↵            "image":"http://bit.ly/*******",↵            "link_id":"oil-change",↵            "title":"Need a tune up? Check out our Oil and Lube shop."↵        },     {↵            "id": "525ad0a2-8476-424e-917a-0d2151f0619e",↵            "image":"http://bit.ly/*******",↵            "link_id":"full-service-carwash",↵            "title":"Have a look at our featured car wash services!"↵        },     {↵            "id": "f4878ae3-8c52-4f09-b737-b85377b254da",↵            "image":"http://bit.ly/*******",↵            "link_id":"exterior-detail",↵            "title":"Dirty car? Try one of our details!"↵        }        ]↵}"
headers: t
ok: true
status: 200
statusText: "OK"
type: 2
url: "https://**********.execute-api.us-west-1.amazonaws.com/prod/specials"
__proto__: n
constructor: function e(e){var n=t.call(this)||this;return n._body=e.body,n.status=e.status,n.ok=n.status>=200&&n.status<=299,n.statusText=e.statusText,n.headers=e.headers,n.type=e.type,n.url=e.url,n}
toString: function (){return"Response with status: "+this.status+" "+this.statusText+" for URL: "+this.url}
__proto__: t
```
Second call:
```
ERROR 
SyntaxError
message: "Unexpected token u"
stack: "SyntaxError: Unexpected token u↵    at Object.parse (native)↵    at e._next (file:///android_asset/www/build/main.js:20:15491)↵    at e.__tryOrUnsub (file:///android_asset/www/build/main.js:7:2458)↵    at e.next (file:///android_asset/www/build/main.js:7:1784)↵    at e._next (file:///android_asset/www/build/main.js:7:868)↵    at e.next (file:///android_asset/www/build/main.js:7:539)↵    at e._next (file:///android_asset/www/build/main.js:20:790)↵    at e.next (file:///android_asset/www/build/main.js:7:539)↵    at XMLHttpRequest.l (file:///android_asset/www/build/main.js:13:17584)↵    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15213)↵    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:13426)↵    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15134)↵    at n.runTask (file:///android_asset/www/build/polyfills.js:3:10390)↵    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:16170)"
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: Error
```

`curl` commands to our API work fine. I can't think of anything with the backend, I've checked it out and it seems to be set up properly.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
