### ISSUE TITLE
error using of attribute animated inside ion-search (use ionic-angular 3.1.0). If use 3.0.0 - app correct working

### ISSUE THREAD

**Issue by AGENTxXx** [driftyco/ionic#11425]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If use attribute animated inside ion-searchbar return this error (show example to plnkr). Example is work, but if use angular core v 3.1.0 - this example showing this error:
`Runtime Error
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
Stack
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at d (http://localhost:8100/build/polyfills.js:3:3991)
    at viewDebugError (http://localhost:8100/build/main.js:8889:32)
    at expressionChangedAfterItHasBeenCheckedError (http://localhost:8100/build/main.js:8867:12)
    at checkBindingNoChanges (http://localhost:8100/build/main.js:9031:15)
    at checkNoChangesNodeInline (http://localhost:8100/build/main.js:12467:9)
    at checkNoChangesNode (http://localhost:8100/build/main.js:12433:9)
    at debugCheckNoChangesNode (http://localhost:8100/build/main.js:13007:28)
    at debugCheckRenderNodeFn (http://localhost:8100/build/main.js:12947:13)
    at Object.eval [as updateRenderer] (ng:///AppModule/HomePage.ngfactory.js:107:5)
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:8100/build/main.js:12929:21)
    at checkNoChangesView (http://localhost:8100/build/main.js:12293:14)
    at callViewAction (http://localhost:8100/build/main.js:12612:17)
    at execEmbeddedViewsAction (http://localhost:8100/build/main.js:12590:17)
    at checkNoChangesView (http://localhost:8100/build/main.js:12292:5)
    at callViewAction (http://localhost:8100/build/main.js:12612:17)`

**Expected behavior:**
example show/hide search bar in ion-header. 

**Steps to reproduce:**
http://plnkr.co/edit/fsutc5CVoSK2Cqh8ZBkx?p=preview

**Related code:**

```
insert any relevant code here
```

**Other information:**
I think, error including in  "ionic-angular": "^3.1.0". If delete attribute animated - app working correct! 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.3.1 Build version 8E1000a

Angular lib 4.0.2
```

**Comment by AmitMY** [comment]
Known issue. Please use `nightly` for now - `3.1.0-201704272149`, or revert to `3.0.2` to keep using it.
