### ISSUE TITLE
Runtime error - Cannot redefine property: onCreateElementNsReady

### ISSUE THREAD

**Issue by pfefferf** [driftyco/ionic#11441]
**Ionic version:**  (check one with "x")
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
I tried to upgrade a project from Ionic 2 to Ionic 3. Testing the app with "ionic serve" results in the error "Runtime error - Cannot redefine property: onCreateElementsNsReady" in the generated polyfill.js.

```
TypeError: Cannot redefine property: onCreateElementNsReady
    at Function.defineProperty (<anonymous>)
    at n (http://localhost:8100/build/polyfills.js:2:27758)
    at e (http://localhost:8100/build/polyfills.js:2:27878)
    at http://localhost:8100/build/polyfills.js:3:21185
    at http://localhost:8100/build/polyfills.js:3:21621
    at g.name (http://localhost:8100/build/polyfills.js:2:26826)
    at http://localhost:8100/build/polyfills.js:2:26882
    at n (http://localhost:8100/build/polyfills.js:1:65)
    at t.MyBundle (http://localhost:8100/build/polyfills.js:2:26764)
    at http://localhost:8100/build/polyfills.js:3:25344
```

**Expected behavior:**
No runtime error.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework: 3.1.1
Ionic App Scripts: 1.3.5
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 7.8.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
```

**package.json dependencies**

```
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@ionic-native/core": "3.5.0",
    "@ionic-native/in-app-browser": "3.5.0",
    "@ionic-native/splash-screen": "3.5.0",
    "@ionic-native/status-bar": "3.5.0",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.1.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.5",
    "typescript": "~2.2.1"
  },
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
