### ISSUE TITLE
Error: Cannot find module "../pages/tabs/tabs"

### ISSUE THREAD

**Issue by jinuem** [driftyco/ionic#11477]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Tabs Default Template Works Fine. But When i add New page (Example Login page , Using Ionic g Command in CLI) Out of Tabs pages. It shows tabs.module.ts is missing. In Default Template also Module.ts is missing for tabs. Only tabs.html and tabs.ts is found in Starter Template. Why it asks for tabs.module.ts suddenly when i implement new page?

**Expected behavior:**
Is tabs.module.ts should be presented in Tabs Started Template?

**Steps to reproduce:**
Start Ionic V2 project with Tabs starter template.
Add any new page and Mark that as Rootpage. 
The Problem Occurs! 

**Error**
Runtime Error
Cannot find module "../pages/tabs/tabs"
Stack
Error: Cannot find module "../pages/tabs/tabs"
    at d (http://localhost:8100/build/polyfills.js:3:3991)
    at Object.webpackEmptyContext.keys (http://localhost:8100/build/main.js:55628:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:74491:77)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:74228:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:111359:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at http://localhost:8100/build/main.js:140:18
    at http://localhost:8100/build/main.js:143:10

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately, i cannot reproduce this issue. Would you mind posting a minimal repo we could use to reproduce this issue?

**Comment by jinuem** [comment]
@jgw96 Sure.. Thanks for the Interest.

Here is the Repo: https://github.com/jinuem/IonicV2Tabs/

**Comment by jinuem** [comment]
My Mistake.  Location Wrong.. Whew... Closing this Issue.
