### ISSUE TITLE
Modal with templateUrl - 'items' undefined

### ISSUE THREAD

**Issue by royalcheeseburger** [driftyco/ionic#11705]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Receive an undefined error when presenting a modal that has its own .ts file and .html file as templateUrl

**Expected behavior:**
Modal presenting without any error

**Steps to reproduce:**
For Ionic 2 issues - http://plnkr.co/edit/te7JzQj5mxbIIrfSTo62?p=preview

I cannot reproduce the error in the forked Plunker.

**Related code:**

```
// new-location-modal.ts
import { Component } from '@angular/core';
import { Platform, NavParams, ViewController } from 'ionic-angular';

@Component({
  templateUrl: "new-location-modal.html"
})
export class NewLocationModalPage {

  constructor(public platform: Platform, public viewCtrl: ViewController) {
    console.log('NewLocationModal#constructor');
  }

  dismiss() {
    this.viewCtrl.dismiss();
  }
}
```

```
// new-location-modal.html
<ion-header>
  <ion-toolbar>
    <ion-title>
     Title
    </ion-title>
    </ion-toolbar>
</ion-header>
<ion-content>
  Content
</ion-content>
```

```
// new-event.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ModalController, NavController, NavParams } from 'ionic-angular';
import { Platform, ViewController } from 'ionic-angular';

import { NewLocationModalPage } from '../../modals/new-location/new-location-modal';

@Component({
  selector: 'page-new-event',
  templateUrl: 'new-event.html'
})
export class NewEventPage {
  newEventForm: FormGroup;

  timeStarts: string = '';

  constructor(public modalCtrl: ModalController, public formBuilder: FormBuilder) {
    // Creating the newEventForm and specifying controls
    this.newEventForm = this.formBuilder.group({
      title: ['', Validators.required],
      sport: ['', Validators.required],
      timeStarts: ['', Validators.required],
      location: ['', Validators.required]
    });
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad NewEventPage');
  }

  presentNewLocationModal() {
    let modal = this.modalCtrl.create(NewLocationModalPage);
    modal.present();
  }
}
```

**Other information:**
```
EXCEPTION: Error in ./NewLocationModal class NewLocationModal - inline template:22:14 caused by: Cannot read property 'items' of undefined

TypeError: Cannot read property 'items' of undefined
    at CompiledTemplate.proxyViewClass.View_NewLocationModal0.detectChangesInternal (/AppModule/NewLocationModal/component.ngfactory.js:363:46)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:8100/build/main.js:117516:18)
    at CompiledTemplate.proxyViewClass.View_NewLocationModal_Host0.detectChangesInternal (/AppModule/NewLocationModal/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
    at ViewContainer.detectChangesInNestedViews (http://localhost:8100/build/main.js:117863:37)
    at CompiledTemplate.proxyViewClass.View_ModalCmp0.detectChangesInternal (/IonicModule/ModalCmp/component.ngfactory.js:46:14)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:8100/build/main.js:117516:18)
    at CompiledTemplate.proxyViewClass.View_ModalCmp_Host0.detectChangesInternal (/IonicModule/ModalCmp/host.ngfactory.js:30:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
```
StackOverflow:  http://stackoverflow.com/questions/44019627/ionic-2-modal-inline-template-typeerror-cannot-read-property-items-of-unde
Ionic Forum: https://forum.ionicframework.com/t/modalcmp-ionviewpreload-error/73988

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 2.3.0

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind updating to the [latest release of ionic](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#321-2017-05-12) and seeing if you still have this issue?

**Comment by royalcheeseburger** [comment]
Thanks @jgw96  for your fast answer! It worked like a charm. But I have two questions though:

1. Can  I use this version for production?
2. Can I keep relying on the Ionic "current version" doc (https://ionicframework.com/docs/)? It won't differ?

**Comment by jgw96** [comment]
No problem! Yep, you can. Ever release we do that is not marked as nightly, alpha or beta is production ready. Also, docs are updated every release to match the latest api of that release.
