### ISSUE TITLE
Ionic 2 - Error No provider for Native Storage!

### ISSUE THREAD

**Issue by scorpion-3** [driftyco/ionic#11761]
I am using Native Storage plugin as specified in the Ionic documentation ([https://ionicframework.com/docs/native/native-storage/]) however when I deploy on the device or emulator I get a white screen. When I inspected further after connecting it to chrome > Remote Devices > Inspect. In the console I get this error  **ERROR Error: No provider for NativeStorage!** 

Any pointers ?. Please help

below is my error log: 
NativeStorage!
    at Error (native)
    at injectionError (file:///android_asset/www/build/main.js:1509:86)
    at noProviderError (file:///android_asset/www/build/main.js:1547:12)
    at ReflectiveInjector_._throwOrNull (file:///android_asset/www/build/main.js:3048:19)
    at ReflectiveInjector_._getByKeyDefault (file:///android_asset/www/build/main.js:3087:25)
    at ReflectiveInjector_._getByKey (file:///android_asset/www/build/main.js:3019:25)
    at ReflectiveInjector_.get (file:///android_asset/www/build/main.js:2888:21)
    at NgModuleInjector.get (file:///android_asset/www/build/main.js:3835:52)
    at resolveDep (file:///android_asset/www/build/main.js:11202:45)
    at createClass (file:///android_asset/www/build/main.js:11071:32)View_MyApp_Host_0 @ ng:///AppModule/MyApp_Host.ngfactory.js:6

This my version info:

cordova CLI: 6.5.0
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed

**Comment by scorpion-3** [comment]
It turns out that I had to manually add ` "cordova-plugin-nativestorage":"^2.2.2",` under dependencies in package.json.  The rest works out fine in Device and on emulator
