### ISSUE TITLE
'Error: the command “android” failed' using cordova

### ISSUE THREAD

**Issue by gauravsak** [driftyco/ionic#1878]
I'm trying to get the android platform added on cordova. I've added and downloaded the most recent SDK in Android SDK, my path is :export PATH=${PATH}:/Users/xxx/Development/android-sdk-linux/platform-tools:Users/xxx/Development/android-sdk-linux/tools, but I keep getting the following error:

```
Error: The command "android" failed. Make sure you have the latest Android SDK installed, and the "android" command (inside the tools/ folder) is added to your path.
    at /Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/lib/check_reqs.js:85:29
    at _rejected (/Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/node_modules/q/q.js:808:24)
    at /Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/node_modules/q/q.js:834:30
    at Promise.when (/Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/node_modules/q/q.js:752:41)
    at /Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/node_modules/q/q.js:574:44
    at flush (/Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
Error: /Users/xxx/.cordova/lib/android/cordova/3.5.0/bin/create: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**EDIT:**

The "android" command is working fine from the shell. I also have the latest versions of Android SDKs installed. Below screenshot shows my SDK manager.

![screenshot from 2014-07-30 05 54 56](https://cloud.githubusercontent.com/assets/2832258/3745253/69a8d33a-17a6-11e4-9d2c-fb325e35c086.png)

What am I doing wrong? I've searched all over for answers, but nothing seems to work. Thanks in advance!

**Comment by lokeswarcherlopalli** [comment]
HI Mhartington,
I am using windows 64bit and i am also geting the same erroe like



C:\Users\loki\AAA>cordova platform add android
Creating android project...

C:\Users\loki\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\node_modu
les\q\q.js:126
                    throw e;
                          ^
Error: Failed to run "android". Make sure you have the latest Android SDK instal
led, and that the "android" command (inside the tools/ folder) is added to your
PATH.
    at C:\Users\loki\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\li
b\check_reqs.js:43:27
    at exithandler (child_process.js:654:7)
    at ChildProcess.errorhandler (child_process.js:670:5)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:818:12)
Error: C:\Users\loki\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\cr
eate.bat: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\loki\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\src\cordova\superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)


![androidsdk](https://cloud.githubusercontent.com/assets/8844680/6079123/21416324-ae27-11e4-9c1f-d19ad85fc5e8.png)

and can you please   help on this.

Thanks&regards,
Lokeswar
