### ISSUE TITLE
bug: collection-repeat regression issue on IE / WP

### ISSUE THREAD

**Issue by rbarriuso** [driftyco/ionic#2042]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The `collection-repeat` directive does no longer work on Internet Explorer / Windows Phone since Ionic beta7 (saw it working on IE with beta 6).

Tested with Ionic 1.0.0-beta.11 release on an emulated WP8, the error trace is:
<pre>
TypeError: Unable to get property '$index' of undefined or null reference
   at CollectionRepeatDataSource.prototype.attachItemAtIndex (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.js:35619:7)
   at CollectionRepeatManager.prototype.renderItem (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.js:36062:7)
   at CollectionRepeatManager.prototype[key] (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.js:36095:7)
   at doRender (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.js:36056:11)
   at CollectionRepeatManager.prototype.render (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.js:36033:9)
   at CollectionRepeatManager.prototype[key] (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.js:36095:7)
   at CollectionRepeatManager.prototype.resize (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.js:35910:7)
   at CollectionRepeatManager.prototype[key] (http://code.ionicframework.com/1.0.0-beta.11/js/ionic.bundle.j
</pre>

</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
This is fixed now.
