### ISSUE TITLE
Error when executing "ionic run android", fine when building app using Eclipse

### ISSUE THREAD

**Issue by mirko77** [driftyco/ionic#2126]
H there,

when I run my Ionic app manually using `Eclipse, it installs fine on the device.

when I use the command line and run `ionic run android` I get the following error:
```
mirko@mirko-air/Applications/MAMP/htdocs/epicollect5-ionic$ 😝  ionic run android
add to body class: platform-android
Running command: /Applications/MAMP/htdocs/epicollect5-ionic/platforms/android/cordova/run 

/Applications/MAMP/htdocs/epicollect5-ionic/platforms/android/cordova/lib/check_reqs.js:39
        return target.split('=')[1].replace('\n', '').replace('\r', '');
                                    ^
TypeError: Cannot call method 'replace' of undefined
    at Object.module.exports.get_target (/Applications/MAMP/htdocs/epicollect5-ionic/platforms/android/cordova/lib/check_reqs.js:39:37)
    at Object.module.exports.check_android (/Applications/MAMP/htdocs/epicollect5-ionic/platforms/android/cordova/lib/check_reqs.js:71:29)
    at Object.module.exports.run (/Applications/MAMP/htdocs/epicollect5-ionic/platforms/android/cordova/lib/check_reqs.js:94:61)
    at Object.<anonymous> (/Applications/MAMP/htdocs/epicollect5-ionic/platforms/android/cordova/run:31:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
Error: /Applications/MAMP/htdocs/epicollect5-ionic/platforms/android/cordova/run: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

I am using Ionic 1.1.13, cordova 3.5

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
