### ISSUE TITLE
Collection repeat bug on WP8

### ISSUE THREAD

**Issue by mathiasmuller4sh** [driftyco/ionic#2234]
I'am aware that Ionic does not support WP8 yet, but from our internals tests it do not performs so bad.
But we face a problem with colleciton repeat.
We try with default codepen and problem  also exists.
Any clue ?
Thanks

TypeError: Unable to get property '$root' of undefined or null reference
at reconnectScope (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:35506:3)
at CollectionRepeatDataSource.prototype.getItem (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:35401:9)
at CollectionRepeatDataSource.prototype.attachItemAtIndex (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:35419:7)
at CollectionRepeatManager.prototype.renderItem (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:35834:7)
at doRender (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:35828:11)
at CollectionRepeatManager.prototype.render (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:35801:9)
at CollectionRepeatManager.prototype.resize (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:35679:7)
at rerender (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:40350:9)
at Anonymous function (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:40317:9)
at $watchCollectionAction (http://10.33.33.159:9000/lib/js/ionic/release/js/ionic.bundle.js:19801:13)

**Comment by pradeepkumargali** [comment]
Thanks @mathiasmuller4sh. You saved my day!

**Comment by luisrudge** [comment]
@perrygovier just accept this PR already. It's something simple and most likely a bad-practice. Makes no sense not accept this because it doesn't crash other platforms.

**Comment by ajoslin** [comment]
Fixed in nightly builds.
