### ISSUE TITLE
ion-infinite-scroll , as navigating bug 

### ISSUE THREAD

**Issue by derozgurg** [driftyco/ionic#2332]
<ion-infinite-scroll> is used in <ion-nav-view> and after being navigated, the error happens below 

i think that occurs while disposing <ion-infinite-scroll >

the error : 
TypeError: Cannot read property 'off' of null
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:41174:28
    at Scope.$broadcast (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20368:28)
    at Scope.$destroy (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20026:14)
    at updateView (http://localhost:8100/lib/ionic/js/ionic.bundle.js:42420:23)
    at eventHook (http://localhost:8100/lib/ionic/js/ionic.bundle.js:42397:17)
    at Scope.$broadcast (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20368:28)
    at $state.transition.resolved.then.$state.transition (http://localhost:8100/lib/ionic/js/ionic.bundle.js:33645:22)
    at wrappedCallback (http://localhost:8100/lib/ionic/js/ionic.bundle.js:18979:81)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:19065:26
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20089:28)

and here is the using in 

<ion-pane  has-header="true">
	<ion-content  scroll="true">		
		
			<div class="item c-fake-item"></div>
			<div class="item c-fake-item"></div>

			<ul class="list" style="margin-bottom:0px;">

				<li class="item item-button-right " ng-repeat="item in chacheGroups track by $index">
					<div class="item-checkbox" style="display:block;position:relative ">
						<label class="checkbox checkbox-assertive">
							<input type="checkbox" ng-model="item.checked">						
						</label>
						<span>{{item.title}}</span>
					</div>
					<button ng-if="item.checked"class="button button-assertive" ng-click="editGroup({{$index}})">
						<i class="icon ion-arrow-right-a"></i>
					</button>
				</li>
				
			</ul>
			
			<ion-infinite-scroll icon="ion-loading-c" ng-if="!noMoreItemsAvailable"  on-infinite="loadMoreGroup()" distance="10%"></ion-infinite-scroll>	

			<div class="item c-fake-item"></div>
			<div class="item c-fake-item"></div>		

		 
	</ion-content>
</ion-pane>

**Comment by Ionitron** [comment]
This should be fixed in the nightly builds, thanks.
