### ISSUE TITLE
Error when changing to hidden tabs

### ISSUE THREAD

**Issue by jianbo** [driftyco/ionic#2369]
Im getting following error when changing tabs, any idea? It happens when I have a hidden tab, and link to the tab using 

      <a id="head-profile" ui-sref="hidden-tab-state">

TypeError: Cannot read property 'scrollTo' of null
    at http://localhost:8000/lib/ionic/js/ionic.bundle.js:39567:17
    at wrappedCallback (http://localhost:8000/lib/ionic/js/ionic.bundle.js:18802:81)
    at http://localhost:8000/lib/ionic/js/ionic.bundle.js:18888:26
    at Scope.$eval (http://localhost:8000/lib/ionic/js/ionic.bundle.js:19931:28)
    at Scope.$digest (http://localhost:8000/lib/ionic/js/ionic.bundle.js:19743:31)
    at Scope.$apply (http://localhost:8000/lib/ionic/js/ionic.bundle.js:20035:24)
    at http://localhost:8000/lib/ionic/js/ionic.bundle.js:21543:36
    at completeOutstandingRequest (http://localhost:8000/lib/ionic/js/ionic.bundle.js:11627:10)

**Comment by Ionitron** [comment]
Greetings, @jianbo!

My sensors indicate that this issue has been inactive for a while.
Due to this, the issue will be closed in 7 days.

If you believe the issue has not been fixed, please add a comment.
This will notify us so we can assist you, and will prevent the issue from being automatically closed.
Feel free to include the following information about the issue, so that we may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @jianbo!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
