### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by natea** [driftyco/ionic#2517]
When I try to start up ionic using the stock 'tabs' app, the following error occurs:

```
$ ionic serve

Multiple addresses available.
Please select which address to use by entering its number from the list below:
 1) 10.10.20.58 (en0)
 2) localhost
Address Selection:  2
Selected address: localhost
Gulp startup tasks: [ 'sass', 'watch' ]
Running dev server: http://localhost:8100
Running live reload server: http://localhost:35729
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)
```

One thing to note is that when I ran `$ ionic setup sass` it returned `/bin/sh: gulp: command not found`

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
