### ISSUE TITLE
bug: Uncaught TypeError: Failed to construct 'URL': Invalid base URL     at getAssetPath (index.js:2710:1)

### ISSUE THREAD

**Issue by wmadden** [driftyco/ionic#25525]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Using `ion-toast` in React, Ionic fails to lazy load the icon specified by string in the `ToastButton` interface. This is very similar to the bug [reported here](https://github.com/ionic-team/ionic-framework/issues/24480) but in the `ion-toast` instead of the refresher component.

E.g.

```
presentToast({
  color: "danger",
  buttons: [
    {
      icon: "close",
      role: "cancel",
    },
  ],
  message: i18n.t.common.httpsErrorMessage(error),
});
```

Results in no icon being visible and the following error in the console:

```
Uncaught TypeError: Failed to construct 'URL': Invalid base URL
    at getAssetPath (index.js:2710:1)
    at getNamedUrl (icon.js:46:1)
    at getUrl (icon.js:27:1)
    at Icon.mode.loadIcon (icon.js:255:1)
    at icon.js:227:1
    at Icon.mode.waitUntilVisible (icon.js:250:1)
    at Icon.mode.connectedCallback (icon.js:225:1)
    at Icon.mode.connectedCallback (index.js:2310:1)
    at addVnodes (index.js:807:1)
    at patch (index.js:995:1)
```

### Expected Behavior

The named icon should be displayed.

### Steps to Reproduce

Attempt to display a toast with an icon.

```
presentToast({
  color: "danger",
  buttons: [
    {
      icon: "close",
      role: "cancel",
    },
  ],
  message: "Test",
});
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1
   Ionic Framework : @ionic/react 6.1.9

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/Users/wmadden/.nodenv/versions/16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

### Additional Information

* https://github.com/ionic-team/ionic-framework/issues/24480
* https://github.com/ionic-team/ionic-framework/pull/24525

**Comment by wmadden** [comment]
Got it, thanks @liamdebeasi 👍🏻
