### ISSUE TITLE
bug: Collection repeat fails in Internet Explorer 11.0

### ISSUE THREAD

**Issue by tuberlinapp** [driftyco/ionic#2923]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Collection repeat fails in Internet Explorer 11.0
```
TypeError: Die Eigenschaft "$root" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
   at reconnectScope (lib/ionic/release/js/ionic.bundle.js:35987:3)
   at CollectionRepeatDataSource.prototype.getItem (lib/ionic/release/js/ionic.bundle.js:35882:9)
   at CollectionRepeatDataSource.prototype.attachItemAtIndex (lib/ionic/release/js/ionic.bundle.js:35900:7)
   at CollectionRepeatManager.prototype.renderItem (lib/ionic/release/js/ionic.bundle.js:36315:7)
   at doRender (lib/ionic/release/js/ionic.bundle.js:36309:11)
   at CollectionRepeatManager.prototype.render (lib/ionic/release/js/ionic.bundle.js:36282:9)
   at CollectionRepeatManager.prototype.resize (lib/ionic/release/js/ionic.bundle.js:36160:7)
   at rerender (lib/ionic/release/js/ionic.bundle.js:40885:9)
   at Anonymous function (lib/ionic/release/js/ionic.bundle.js:40852:9)
   at $watchCollectionAction (lib/ionic/release/js/ionic.bundle.js:20036:13)
```</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you give the nightly builds a try.

**Comment by tuberlinapp** [comment]
Yes. It is working, but also with any branch before. 
Anyway. Good work and thank you for the good project.
