### ISSUE TITLE
Empty ionic app crashes on windows 8.1 after start.

### ISSUE THREAD

**Issue by caiiiycuk** [driftyco/ionic#2965]
Hi. I'm searching for framework to use with cordova. Before i used Ratchet and cordova to assembly w8 app. This app works fine. Now i want to use ionic. But if i add ```ionic.bundle.min.js``` to my index.html than app crashes at startup. My index.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <!-- compiled css output -->
    <link href="css/ionic.app.css" rel="stylesheet">
    <!--
    <script src="lib/fastclick/fastclick.js"></script>
    -->
    <!-- ionic/angularjs js -->
    <script src="lib/ionic/js/ionic.bundle.min.js"></script>
    

    <!-- cordova script (this will be a 404 during development) -->
    <script src="cordova.js"></script>

    <!-- your app's js
    <script src="js/application.js"></script>
     -->
    
  </head>
  <body ng-app="starter">
    <!--
      The nav bar that will be updated as we navigate between views.
    -->
    <ion-nav-bar class="bar-stable">
      <ion-nav-back-button>
      </ion-nav-back-button>
    </ion-nav-bar>
    <!--
      The views will be rendered in the <ion-nav-view> directive below
      Templates are in the /templates folder (but you could also
      have templates inline in this html file if you'd like).
    -->
    <ion-nav-view></ion-nav-view>
  </body>
</html>
```

I try to use nightly build and latest beta of ionic, but with both versions app doesn't work. 
I build my app with this command:
```sh
ionic build windows8
```
After that i install app with windows power shell.

App logs from windows event viewer:
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2015-01-20T01:58:38.000000000Z" /> 
  <EventRecordID>1708</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>wp8</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data>0</Data> 
  <Data>WWAJSE</Data> 
  <Data>Нет данных</Data>  //No data
  <Data>0</Data> 
  <Data>com.ionicframework.iworld917083_0.0.11.0_neutral__54dbk1tt7zbhy</Data> 
  <Data>com.ionicframework.iworld917083</Data> 
  <Data>a735</Data> 
  <Data>0</Data> 
  <Data>ms-appx://com.ionicframework.iworld917083/www/lib/ionic/js/ionic.bundle.min.js</Data> 
  <Data>200_508</Data> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data>ErrorInfo.3024.5324.txt C:\Program Files\WindowsApps\com.ionicframework.iworld917083_0.0.11.0_neutral__54dbk1tt7zbhy\AppXManifest.xml</Data> 
  <Data /> 
  <Data /> 
  <Data>0</Data> 
  <Data>d96afa0a-a047-11e4-825a-08002779e010</Data> 
  <Data>262144</Data> 
  <Data /> 
  </EventData>
  </Event>
```

```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2015-01-20T01:58:40.000000000Z" /> 
  <EventRecordID>1709</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>wp8</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>98909436602</Data> 
  <Data>5</Data> 
  <Data>WWAJSE</Data> 
  <Data>Нет данных</Data>   //No data
  <Data>0</Data> 
  <Data>com.ionicframework.iworld917083_0.0.11.0_neutral__54dbk1tt7zbhy</Data> 
  <Data>com.ionicframework.iworld917083</Data> 
  <Data>a735</Data> 
  <Data>0</Data> 
  <Data>ms-appx://com.ionicframework.iworld917083/www/lib/ionic/js/ionic.bundle.min.js</Data> 
  <Data>200_508</Data> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data>ErrorInfo.3024.5324.txt C:\Program Files\WindowsApps\com.ionicframework.iworld917083_0.0.11.0_neutral__54dbk1tt7zbhy\AppXManifest.xml C:\Users\Александр\AppData\Local\Temp\WER856C.tmp.WERInternalMetadata.xml</Data> 
  <Data>C:\Users\Александр\AppData\Local\Microsoft\Windows\WER\ReportArchive\NonCritical_com.ionicframewo_de84ee760d0b89d79406a47c7aafc79235df42_00000000_0be18acb</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>d96afa0a-a047-11e4-825a-08002779e010</Data> 
  <Data>0</Data> 
  <Data>0f55c0ff3a890d178eb71949c2ec82bb</Data> 
  </EventData>
  </Event>
```

**Comment by caiiiycuk** [comment]
I`m mistaken. Windows 8 -> Windows 8.1

**Comment by caiiiycuk** [comment]
Another mistake, i build with:
```sh
ionic build windows8
```

**Comment by caiiiycuk** [comment]
I create archive from my Windows App folder: https://drive.google.com/file/d/0B28AXjYMDNZsLWlwd3Q1SGpBd00/view?usp=sharing

When i run this app from browser i have error:
FF:
```
Error: [$injector:modulerr] http://errors.angularjs.org/1.3.6/$injector/modulerr?p0=starter&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.6%2F%24injector%2Fnomod%3Fp0%3Dstarter%0AA%2F%3C%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A37%3A416%0AMd%2F%3C%2F%3C%2F%3C%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A334%0Aa%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A51%3A483%0AMd%2F%3C%2F%3C%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A1%0Ag%2F%3C%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A66%3A275%0Ar%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A38%3A300%0Ag%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A66%3A123%0AOb%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A69%3A360%0Asc%2Fd%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A48%3A350%0Asc%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A49%3A153%0AHd%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A47%3A483%0A%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A280%3A238%0Aa%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A194%3A399%0Ajf%2Fc%40file%3A%2F%2F%2Fhome%2Fcaiiiycuk%2Ftmp%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A63%3A280%0A ionic.bundle.min.js:37
```

chrome:
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.6/$injector/modulerr?p0=starter&p1=Error%3A…rg%2F1.3.6%2F%24injector%2Fnomod%3Fp0%3Dstarter%0A%20%20%20%20at%20Error%2...<omitted>...0) ionic.bundle.min.js:67
Failed to load resource: net::ERR_FILE_NOT_FOUND 
```

**Comment by caiiiycuk** [comment]
More verbose:
```
Error: [$injector:modulerr] Failed to instantiate module starter due to:
[$injector:nomod] Module 'starter' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.6/$injector/nomod?p0=starter
minErr/<@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:7888:12
module/<@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:9576:1
ensure@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:9500:38
module@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:9574:1
loadModules/<@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:11906:22
forEach@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:8147:11
loadModules@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:11890:5
createInjector@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:11816:11
bootstrap/doBootstrap@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:9263:20
bootstrap@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:9284:1
angularInit@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:9178:5
@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:33820:5
trigger@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:10553:7
createEventHandler/eventHandler@file:///C:/Program%20Files/WindowsApps/com.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy/www/lib/ionic/js/ionic.bundle.js:10823:9

http://errors.angularjs.org/1.3.6/$injector/modulerr?p0=starter&p1=%5B%24injector%3Anomod%5D%20Module%20'starter'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.6%2F%24injector%2Fnomod%3Fp0%3Dstarter%0AminErr%2F%3C%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A7888%3A12%0Amodule%2F%3C%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9576%3A1%0Aensure%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9500%3A38%0Amodule%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9574%3A1%0AloadModules%2F%3C%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A11906%3A22%0AforEach%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A8147%3A11%0AloadModules%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A11890%3A5%0AcreateInjector%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A11816%3A11%0Abootstrap%2FdoBootstrap%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9263%3A20%0Abootstrap%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9284%3A1%0AangularInit%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9178%3A5%0A%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A33820%3A5%0Atrigger%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A10553%3A7%0AcreateEventHandler%2FeventHandler%40file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FWindowsApps%2Fcom.ionicframework.iworld917083_0.0.12.0_neutral__54dbk1tt7zbhy%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A10823%3A9%0A ionic.bundle.js:7888

```

**Comment by dkarzon** [comment]
Do you get any other js errors when running the app? I found there were a few random js errors that stopped my app from running.
Checkout my PR for some Windows 8.1 fixes https://github.com/driftyco/ionic/pull/2518

**Comment by caiiiycuk** [comment]
Ups... js errors that i post above occurs because i commented out ```application.js```. When i uncomment application script this errors disappear, but w8 app still crashing.

@dkarzon 
After fixing ```scrollView.__cleanup``` and  ```ionic.keyboard.hide``` my app still crashes. Do you know how can i figure out concrete js error which occurred when my app starts.

**Comment by dkarzon** [comment]
Are you running it from Visual Studio? If so you should just be able to debug it and it will show you the error.

**Comment by caiiiycuk** [comment]
No, i run it as others metro apps. Ok, i will try to debug it frob visual studio. Thank you.

**Comment by caiiiycuk** [comment]
My app crashes on this code:
```
  element.insertBefore(child, index);
```

This is security error: http://msdn.microsoft.com/en-us/library/windows/apps/hh849625.aspx
Looks like i can`t use angularjs without wrapping dynamic content creation with MSApp.execUnsafeLocalFunction. (http://stackoverflow.com/questions/12792383/how-do-you-get-angular-js-to-work-in-a-windows-8-store-app)

Also i try to use ng-csp directive, but angular says that module 'ngLocale' is not available. What should i do?

**Comment by caiiiycuk** [comment]
related to https://github.com/angular/angular.js/issues/1853

**Comment by dkarzon** [comment]
Yes that is the problem that winstore-compat.js fixes.

**Comment by caiiiycuk** [comment]
After including winstore-compat.js security exception was disappear. But now angular says that module 'ngLocale' is not available, in browser there are no such error. I don`t have much experience with angular. I'm sorry if this is a noob question.

**Comment by caiiiycuk** [comment]
There is strange error with modules. If i include my 'starter' module in separate js file, then angular does not see it (.
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <!-- compiled css output -->
    <link href="css/ionic.app.css" rel="stylesheet">

    <!-- ionic/angularjs js -->
    <script src="lib/winstore-jscompat.js"></script>
    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <!-- cordova script (this will be a 404 during development) -->
    <script src="cordova.js"></script>
    <!-- your app's js -->
    <script src="lib/application.js"></script>
```

But when i move my module inside ionic.bundle.js then app starts without error. But it does not work, i see this errors in log:
```js
HTML1300: Произошел переход.
File: index.html
Error: [$compile:tplrt] Template for directive 'ionTabNav' must have exactly one root element. 
http://errors.angularjs.org/1.3.6/$compile/tplrt?p0=ionTabNav&p1=
   at applyDirectivesToNode (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15219:15)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14814:9)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14823:9)
   at compile (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14721:7)
   at link (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:52117:9)
   at invokeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:16025:9)
   at nodeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15537:11)
   at compositeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:
Error: [$compile:tplrt] Template for directive 'ionTabNav' must have exactly one root element. 
http://errors.angularjs.org/1.3.6/$compile/tplrt?p0=ionTabNav&p1=
   at applyDirectivesToNode (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15219:15)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14814:9)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14823:9)
   at compile (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14721:7)
   at link (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:52117:9)
   at invokeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:16025:9)
   at nodeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15537:11)
   at compositeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:
Error: [$compile:tplrt] Template for directive 'ionTabNav' must have exactly one root element. 
http://errors.angularjs.org/1.3.6/$compile/tplrt?p0=ionTabNav&p1=
   at applyDirectivesToNode (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15219:15)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14814:9)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14823:9)
   at compile (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14721:7)
   at link (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:52117:9)
   at invokeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:16025:9)
   at nodeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15537:11)
   at compositeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:
Error: [$compile:tplrt] Template for directive 'ionTabNav' must have exactly one root element. 
http://errors.angularjs.org/1.3.6/$compile/tplrt?p0=ionTabNav&p1=
   at applyDirectivesToNode (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15219:15)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14814:9)
   at compileNodes (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14823:9)
   at compile (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:14721:7)
   at link (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:52117:9)
   at invokeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:16025:9)
   at nodeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:15537:11)
   at compositeLinkFn (ms-appx://8958ccc0-a055-11e4-86f6-3536a2149d08/www/lib/ionic/js/ionic.bundle.js:
```

**Comment by caiiiycuk** [comment]
I found good article: https://www.hoessl.eu/2014/12/on-using-the-ionic-framework-for-windows-phone-8-1-apps/ 

I slove all issues thanks to this article. Exception posted above can be fixed with replacing cleansePropertySetter in winstore-jscompat.

@dkarzon thank you very much for helping me. Actually launching example app on windows 8.1 is big deal for me.

**Comment by dkarzon** [comment]
:+1: Good to here!

**Comment by mattezell** [comment]
Thanks, @caiiiycuk !  You've likely saved me countless hours chasing my tail on this!

Curious as to why this issue has been closed though... It does seem that this is still an issue - I would think the desired 'out of the box' behavior of an Ionic Windows app would be that it would run without requiring additional manual manipulation of the Ionic generated starter project...   As of today (4/30/2015), when generating a starter project and adding Windows as a platform, you're not left with a functional Windows starter app due to either the missing shim (if it is actually 'REQUIRE' to make things work) or due to some other issue in the Ionic project that the shim serves to address (if it's desired by Ionic to not depend on this external lib for base functionality)...  Just my 2 cents...

Anywhos!  Thanks again!  PROGRESS!!!

**Comment by agallen** [comment]
I continue with the same issue

don't work for my ionic app :-\
