### ISSUE TITLE
Bug: Error in History code.

### ISSUE THREAD

**Issue by piffie** [driftyco/ionic#3097]
Hi, this happens sometimes, but is there in our app repeatable.
```javascript
TypeError: Cannot set property 'forwardViewId' of undefined
    at Object.IonicModule.factory.register (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:42502:45)
    at IonicModule.controller.self.register (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:47175:38)
    at updateView (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:50834:23)
    at IonicModule.directive.compile (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:50818:9)
    at invokeLinkFn (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:16019:9)
    at nodeLinkFn (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:15531:11)
    at compositeLinkFn (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:14887:13)
    at nodeLinkFn (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:15526:24)
    at compositeLinkFn (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:14887:13)
    at nodeLinkFn (http://localhost:1337/bower_components/ionic/js/ionic.bundle.js:15526:24) <ion-nav-view animation="slide-left-right" class="view-container" nav-view-transition="android">
```

The issue is in this line of code.
```javascript
     if (viewHistory.backView && historyId == viewHistory.backView.historyId && currentStateId == viewHistory.backView.stateId && url == viewHistory.backView.url) {
        for (x = 0; x < hist.stack.length; x++) {
          if (hist.stack[x].viewId == viewId) {
            action = 'dupNav';
            direction = DIRECTION_NONE;
            hist.stack[x - 1].forwardViewId = viewHistory.forwardView = null;
            viewHistory.currentView.index = viewHistory.backView.index;
            viewHistory.currentView.backViewId = viewHistory.backView.backViewId;
            viewHistory.backView = getBackView(viewHistory.backView);
            hist.stack.splice(x, 1);
            break;
          }
        }
      }
```
the  hist.stack[x - 1] is null.

i actually did not debug it to find out why. but it seems to happen only when traversing back and foreward on the history.

Result is, that the page stays empty.

**Comment by Ionitron** [comment]
Greetings @piffie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3097). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3097)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
This is fixed now in the nightly builds.

**Comment by DEllingsworth** [comment]
@adamdbradley - what commit was this fixed? We have this issue but we are running Beta-14.  I'm hoping that I can cherry pick this fix since RC has some breaking changes for us.

**Comment by DEllingsworth** [comment]
I found the commits: 
https://github.com/driftyco/ionic/commit/bcc4eebfcaca1858a0c2b75c1da24ddce5dd9f50
and
https://github.com/driftyco/ionic/commit/2885258d1299f9c648650548e08f58f049c57447
