### ISSUE TITLE
ionic serve fails on 1.4.1 with TypeError: Object 1.4.1 has no method 'contains'

### ISSUE THREAD

**Issue by ilkkanisula** [driftyco/ionic#3741]
I updated to 1.4.1 (npm update -g ionic) and got following error:
```
/Users/ilkkanisula/.nvm/v0.10.33/lib/node_modules/ionic/lib/cli.js:22
  if (settings.version.contains('dev') || settings.version.contains('beta') ||
                       ^
TypeError: Object 1.4.1 has no method 'contains'
    at Object.dev (/Users/ilkkanisula/.nvm/v0.10.33/lib/node_modules/ionic/lib/cli.js:22:24)
    at reportExtras [as prerequestMethod] (/Users/ilkkanisula/.nvm/v0.10.33/lib/node_modules/ionic/lib/cli.js:442:11)
    at process._uncaughtExceptionListener (/Users/ilkkanisula/.nvm/v0.10.33/lib/node_modules/ionic/node_modules/opbeat-ionic/index.js:124:22)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```
I patched cli.js with following change:
```javascript
Cli.dev = function dev() {
  if (typeof settings.version === 'string' ) { return true; }
  if (settings.version.contains('dev') || settings.version.contains('beta') || settings.version.contains('alpha')) {
    return true;
  }

  return false;
};
```

This resulted in exception:
```
An error occured and was reported to Opbeat undefined

/Users/ilkkanisula/.nvm/v0.10.33/lib/node_modules/ionic/lib/cli.js:449
    console.log(err.stack);
                   ^
TypeError: Cannot read property 'stack' of undefined
    at reportExtras [as prerequestMethod] (/Users/ilkkanisula/.nvm/v0.10.33/lib/node_modules/ionic/lib/cli.js:449:20)
    at process._uncaughtExceptionListener (/Users/ilkkanisula/.nvm/v0.10.33/lib/node_modules/ionic/node_modules/opbeat-ionic/index.js:124:22)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```

My environment:
```
$ ionic info

Your system information:

Cordova CLI: 4.3.0
Gulp version:  CLI version 3.8.10
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.1
Ionic App Lib Version: 0.0.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Lion
Node Version: v0.10.33
Xcode version: Xcode 4.6.3 Build version 4H1503 
```

**Comment by Ionitron** [comment]
Greetings @ilkkanisula!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3741). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3741)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#424
