### ISSUE TITLE
ionic-push error when registering user. $q being used as a function

### ISSUE THREAD

**Issue by dareenzo** [driftyco/ionic#3754]
Hello,

I get the error bellow in chrome and device when running $ionicPush.register({...}) as part of the example code for ionic-push. Detailed error show in chrome is:

```
TypeError: object is not a function
    at Object.register (file:///android_asset/www/lib/ionic-service-push/ionic-push.js:240:14)
    at h.$scope.pushRegister (file:///android_asset/www/js/controllers/ApplicationController.js:225:15)
    at file:///android_asset/www/js/controllers/ApplicationController.js:77:21
    at h.$emit (file:///android_asset/www/lib/angular/angular.min.js:114:437)
    at file:///android_asset/www/js/controllers/AuthenticationController.js:115:33
    at J (file:///android_asset/www/lib/angular/angular.min.js:101:96)
    at file:///android_asset/www/lib/angular/angular.min.js:102:259
    at h.$eval (file:///android_asset/www/lib/angular/angular.min.js:113:32)
    at h.$digest (file:///android_asset/www/lib/angular/angular.min.js:110:117)
    at h.$apply (file:///android_asset/www/lib/angular/angular.min.js:113:362) 
``` 
And going straight to line 240 in ionic-push.js this is what is there.
```javascript
return $q(function(resolve) {
        if (!app) {
          return;
        }
```

From what I understand *$q* should not be used as a function. Please help me with this

**Comment by Ionitron** [comment]
Greetings @dareenzo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3754). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3754)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-push-issues#5
