### ISSUE TITLE
bug: Windows 8 and Windows Phone start Issue

### ISSUE THREAD

**Issue by meron1122** [driftyco/ionic#3820]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

```
TypeError: Nie można ustawić właściwości „backButtonIcon” dla niezdefiniowanego lub pustego odwołania
   at B.createHeaderBar (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:385:28501)
   at B.init (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:385:27469)
   at link (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:388:3587)
   at $ (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:101:149)
   at v (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:90:203)
   at g (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:82:299)
   at g (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:82:316)
   at Anonymous function (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:81:413)
   at Anonymous function (ms-app

Error: [$compile:tplrt] http://errors.angularjs.org/1.3.13/$compile/tplrt?p0=ionTabNav&p1=
   at fa (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:92:311)
   at T (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:82:418)
   at T (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:83:1)
   at E (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:80:430)
   at Anonymous function (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:388:17269)
   at $ (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:101:149)
   at v (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:90:203)
   at g (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic/js/ionic.bundle.min.js:82:299)
   at g (ms-appx://io.cordova.warehousecordova/www/bower_components/ionic
```

Looks like ionic don't support windows 8 back button, right?

I find on internet smillar post:
https://www.hoessl.eu/2014/12/on-using-the-ionic-framework-for-windows-phone-8-1-apps/

But solution didn't work.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @meron1122!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3820). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3820)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @meron1122!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
