### ISSUE TITLE
Unable to sync the scss changes when customizing the ionic.app.scss under scss directory

### ISSUE THREAD

**Issue by Alvinzhao** [driftyco/ionic#3863]
Hi, guys
I encountered one issue like following. Do you have any idea? I was changing the scss on MAC. It seems a permission issue. How to fix it?
Error: EACCES, permission denied '/Users/zhaoguoxin/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/Users/zhaoguoxin/apps/ionic/e8000tabs/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/Users/zhaoguoxin/apps/ionic/e8000tabs/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/Users/zhaoguoxin/apps/ionic/e8000tabs/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/Users/zhaoguoxin/apps/ionic/e8000tabs/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/Users/zhaoguoxin/apps/ionic/e8000tabs/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
An uncaught exception occured and has been reported to Ionic

**Comment by Ionitron** [comment]
Greetings @Alvinzhao!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3863). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3863)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Alvinzhao!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
