### ISSUE TITLE
bug: Could not build a project

### ISSUE THREAD

**Issue by loloof64** [driftyco/ionic#3885]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I could not build my project (only targeted android platform), and I did not add any code or file to the just generated project.

Please, look at this stacktrace :

    $ ionic build
    Updated the hooks directory to have execute permissions
    Running command: /home/laurent-bernabe/Documents/Programmation/ProjetsPersos/Ionic    /ChessPositionsArchiver/hooks/after_prepare/010_add_platform_class.js /home/laurent-bernabe    /Documents/Programmation/ProjetsPersos/Ionic/ChessPositionsArchiver
    add to body class: platform-android
    Running command: /home/laurent-bernabe/Documents/Programmation/ProjetsPersos/Ionic    /ChessPositionsArchiver/platforms/android/cordova/build 
    Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
    Buildfile: /home/laurent-bernabe/Documents/Programmation/ProjetsPersos/Ionic    /ChessPositionsArchiver/platforms/android/build.xml

    -set-mode-check:

    -set-debug-files:

    -check-env:
     [checkenv] Android SDK Tools Revision 24.3.0
     [checkenv] Installed at /home/laurent-bernabe/Android/Sdk

    -setup:
         [echo] Project Name: MainActivity
      [gettype] Project Type: Application

    -set-debug-mode:

    -debug-obfuscation-check:

    -pre-build:

    -build-setup:
    [getbuildtools] Using latest Build Tools: 22.0.1
         [echo] Resolving Build Target for MainActivity...
    [gettarget] Project Target:   Android 5.0.1
    [gettarget] API level:        21
         [echo] ----------
         [echo] Creating output directories if needed...
         [echo] ----------
         [echo] Resolving Dependencies for MainActivity...
    [dependency] Library dependencies:
    [dependency] 
    [dependency] ------------------
    [dependency] Ordered libraries:
    [dependency] 
    [dependency] ------------------
         [echo] ----------
         [echo] Building Libraries with 'debug'...

    nodeps:

    -set-mode-check:

    -set-debug-files:

    -check-env:
     [checkenv] Android SDK Tools Revision 24.3.0
     [checkenv] Installed at /home/laurent-bernabe/Android/Sdk

    -setup:
         [echo] Project Name: MainActivity
      [gettype] Project Type: Android Library

    -set-debug-mode:

    -debug-obfuscation-check:

    -pre-build:

    -build-setup:
    [getbuildtools] Using latest Build Tools: 22.0.1
         [echo] Resolving Build Target for MainActivity...
    [gettarget] Project Target:   Android 5.0.1
    [gettarget] API level:        21
         [echo] ----------
         [echo] Creating output directories if needed...
        [mkdir] Created dir: /home/laurent-bernabe/Documents/Programmation/ProjetsPersos/Ionic    /ChessPositionsArchiver/platforms/android/CordovaLib/ant-build/rsObj
        [mkdir] Created dir: /home/laurent-bernabe/Documents/Programmation/ProjetsPersos/Ionic    /ChessPositionsArchiver/platforms/android/CordovaLib/ant-build/rsLibs
         [echo] ----------
         [echo] Resolving Dependencies for MainActivity...
    [dependency] Library dependencies:
    [dependency] No Libraries
    [dependency] 
    [dependency] ------------------

    -code-gen:
    [mergemanifest] No changes in the AndroidManifest files.
         [echo] Handling aidl files...
         [aidl] No AIDL files to compile.
         [echo] ----------
         [echo] Handling RenderScript files...
         [echo] ----------
         [echo] Handling Resources...
         [aapt] Generating resource IDs...

    BUILD FAILED
    /home/laurent-bernabe/Android/Sdk/tools/ant/build.xml:597: The following error occurred while     executing this line:
    /home/laurent-bernabe/Android/Sdk/tools/ant/build.xml:649: The following error occurred while     executing this line:
    /home/laurent-bernabe/Android/Sdk/tools/ant/build.xml:694: Execute failed: java.io.IOException:     Cannot run program "/home/laurent-bernabe/Android/Sdk/build-tools/22.0.1    /aapt" (in directory "/home/laurent-bernabe/Documents/Programmation/ProjetsPersos    /Ionic/ChessPositionsArchiver/platforms/android/CordovaLib"): error=2, Aucun     fichier ou dossier de ce type
    	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    	at java.lang.Runtime.exec(Runtime.java:620)
    	at     org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.    java:58)
    	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
    	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	    at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
    	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
    	at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
    	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	    at org.apache.tools.ant.Task.perform(Task.java:348)
	    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	    at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
    	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	    at org.apache.tools.ant.Task.perform(Task.java:348)
	    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	    at org.apache.tools.ant.Task.perform(Task.java:348)
	    at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	    at org.apache.tools.ant.Task.perform(Task.java:348)
	    at org.apache.tools.ant.Target.execute(Target.java:435)
	    at org.apache.tools.ant.Target.performTasks(Target.java:456)
	    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	    at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:306)
	    at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:221)
	    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	    at org.apache.tools.ant.Task.perform(Task.java:348)
	    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	    at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
	    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	    at org.apache.tools.ant.Task.perform(Task.java:348)
	    at org.apache.tools.ant.Target.execute(Target.java:435)
	    at org.apache.tools.ant.Target.performTasks(Target.java:456)
	    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	    at org.apache.tools.ant.Main.runBuild(Main.java:851)
	    at org.apache.tools.ant.Main.startAnt(Main.java:235)
	    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
    Caused by: java.io.IOException: error=2, Aucun fichier ou dossier de ce type
	    at java.lang.UNIXProcess.forkAndExec(Native Method)
	    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	    ... 68 more

    Total time: 2 seconds

    /home/laurent-bernabe/Documents/Programmation/ProjetsPersos/Ionic/ChessPositionsArchiver    /platforms/android/cordova/node_modules/q/q.js:126
                        throw e;
                          ^
    Error code 1 for command: ant with args: debug,-f,/home/laurent-bernabe/Documents    /Programmation/ProjetsPersos/Ionic/ChessPositionsArchiver/platforms/android/build.xml,-    Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
    ERROR building one of the platforms: Error: /home/laurent-bernabe/Documents/Programmation    /ProjetsPersos/Ionic/ChessPositionsArchiver/platforms/android/cordova/build: Command failed with     exit code 8
    You may not have the required environment or OS to build this project
    Error: /home/laurent-bernabe/Documents/Programmation/ProjetsPersos/Ionic    /ChessPositionsArchiver/platforms/android/cordova/build: Command failed with exit code 8
        at ChildProcess.whenDone (/home/laurent-bernabe/.nvm/v0.10.37/lib/node_modules/cordova    /node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:766:16)
        at Process.ChildProcess._handle.onexit (child_process.js:833:5)

Also, if this can help you, I've just installed a new Ubuntu on my post (Ubuntu 15.04 x64 on top of Kubuntu 14.10 x64)  , but with keeping my /home partition instead of replacing it !

Regards</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#462
