### ISSUE TITLE
bug: Push notifications : AdMobPro && phonegap PushPlugin seems incompatible

### ISSUE THREAD

**Issue by prisonier** [driftyco/ionic#4049]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,

I run into an issue today that not directly concern Ionic but if I was an ionic dev, I would have liked to know it as many users wants to use both PushNotifications and monetization. And as AdMobPro is the best cordova plugin and Ionic offer easy notifications with PushPlugin, I think that you are concerned.
It took me few hours to spot the problem and I finally found it when I decided to start a fresh app to find the step where it fails.

So I started an app, [installed the PushPlugin](http://docs.ionic.io/v1.0/docs/push-from-scratch).
Then add platform and build. Everything is ok.

Then add the AdMobPro plugin
```
cordova plugin add cordova-plugin-admobpro
```

Then try to build then everything breaks. 

```java
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        /home/prisonier/dev/dependencies/android-sdk-linux/build-tools/22.0.1/dx --dex --no-optimize --output /home/prisonier/dev/testapp/platforms/android/build/intermediates/dex/debug --input-list=/home/prisonier/dev/testapp/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
        2
  Output:
        
        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)
        


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 41.392 secs

/home/prisonier/dev/testapp/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/prisonier/dev/testapp/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/prisonier/dev/testapp/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/prisonier/dev/testapp/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /home/prisonier/dev/testapp/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

``` 

I also tried to remove the PushPlugin after that and keep the AdMobPro and everything run smooth again. I really don't know how to manage this incompatability. 

I see issues which looks similar [here (ionic-cli)](https://github.com/driftyco/ionic-cli/issues/182), [here (PushPlugin)](https://github.com/phonegap-build/PushPlugin/issues/492) and [here (Phonegap-facebook)](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1028).

It looks like there is some solutions but I'm really not familiar with manifest edit and touching inside plugins. I hope that there is another solution. 

Regards

```
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
OS: Distributor ID:     Debian Description:     Debian GNU/Linux 7.8 (wheezy) 
Node Version: v0.12.6
```

**Comment by Ionitron** [comment]
Greetings @prisonier!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4049). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4049)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @prisonier!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
