### ISSUE TITLE
bug: Error clone repository cordova pushPlugin

### ISSUE THREAD

**Issue by devtosystems** [driftyco/ionic#4244]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>browser</span>

<span ionic-description>Hello guys!

I do not running pushNotification plugin of the ionic tutorial. ;(
The error log appears below.
Should they need more information, please do not forget to ask.

```bash
$ cordova plugin add https://github.com/phonegap-build/PushPlugin.git
Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone
Repository "https://github.com/phonegap-build/PushPlugin.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/tmp/git/1439840584782/Example'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
```

The tutorial I push then you need the cord push the plugin is as follows:
http://docs.ionic.io/v1.0/docs/push-from-scratch

Clicking on the button "push" in the browser displays the error below:

```
TypeError: Cannot read property 'pushNotification' of undefined
    at Object.register (http://172.16.200.210:8101/lib/ngCordova/dist/ng-cordova.js:5701:24)
    at init (http://172.16.200.210:8101/lib/ionic-service-push/ionic-push.js:146:20)
    at http://172.16.200.210:8101/lib/ionic-service-push/ionic-push.js:309:21
    at new Q (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:23650:5)
    at Q (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:23637:14)
    at Object.register (http://172.16.200.210:8101/lib/ionic-service-push/ionic-push.js:270:14)
    at Scope.$scope.identifyUser.$scope.pushRegister (http://172.16.200.210:8101/js/controllers.js:36:28)
    at fn (eval at <anonymous> (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:21972:15), <anonymous>:4:227)
    at http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:57514:9
    at Scope.$get.Scope.$eval (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:24673:28)(anonymous function) @ ionic.bundle.js:21157$get @ ionic.bundle.js:17936$get.Scope.$apply @ ionic.bundle.js:24774(anonymous function) @ ionic.bundle.js:57513eventHandler @ ionic.bundle.js:12098triggerMouseEvent @ ionic.bundle.js:2865tapClick @ ionic.bundle.js:2854tapMouseUp @ ionic.bundle.js:2927
```

Please, help me!
Thank you!
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @devtosystems!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4244). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4244)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please try to update your version of cordova-cli to the latest, 5.2.

**Comment by Ionitron** [comment]
Greetings @devtosystems!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
