### ISSUE TITLE
bug: ion-nav-buttons - change visibility (version ionic bundle 1.1.0)

### ISSUE THREAD

**Issue by joaolori** [driftyco/ionic#4343]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Im facing a issue, im chaging visiblity of nav buttons on ion-nav bar...
It works first time... but when change view to another view that should show buttons getting below error...

 <ion-nav-bar ng-if="showHeader"  ng-class="bar-header" >
        <ion-nav-buttons side="right" ng-show="_MODE==='REGISTRATION' || _MODE ==='RECPWD' || _MODE==='ADDCARD' || _MODE==='EDITCARD'">
            <span class="button button-clear textWhite mtmm-xs" ng-click="cancelActionHome()">
                {{"cancel" | translate }}
            </span>
        </ion-nav-buttons>
    </ion-nav-bar>

Im chaing variable with $rootScope

TypeError: Cannot read property 'outerHTML' of null
    at pre (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:57149:58)
    at invokeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:17477:9)
    at nodeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16956:11)
    at compositeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16368:13)
    at nodeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16972:24)
    at compositeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16368:13)
    at publicLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16243:30)
    at boundTranscludeFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16387:16)
    at controllersBoundTransclude (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:17004:18)
    at 
File: ionic.bundle.js, Line: 21157, Column: 24
   "TypeError: Cannot read property 'outerHTML' of null
    at pre (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:57149:58)
    at invokeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:17477:9)
    at nodeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16956:11)
    at compositeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16368:13)
    at nodeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16972:24)
    at compositeLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16368:13)
    at publicLinkFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16243:30)
    at boundTranscludeFn (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:16387:16)
    at controllersBoundTransclude (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:17004:18)
    at Object.ngIfWatchAction [as fn] (file:///android_asset/www/angular/vendors/ionic/release/js/ionic.bundle.js:32639:15)"
   "<ion-nav-buttons side="right" ng-show="_MODE==='REGISTRATION' || _MODE ==='RECPWD' || _MODE==='ADDCARD' || _MODE==='EDITCARD'" class="hide">"
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @joaolori!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4343). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4343)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by joaolori** [comment]
Is not visibility error, i change that to always appear and still getting the error... works at 1st time... after that gaves the error and never appear the nav-buttons

**Comment by joaolori** [comment]
Ok, i have identified the problem, its related cause i control visibility of ther nav-header, and based on that i show or not the header... i guess its related cause i remove the nav header visiblitiy and show always and works fine

**Comment by perrygovier** [comment]
Hey @joaolori, could you put this in a codepen?

**Comment by Ionitron** [comment]
Greetings @joaolori!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @joaolori!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
