### ISSUE TITLE
bug: ionic -v undefined:0

### ISSUE THREAD

**Issue by ceo-mint-soft** [driftyco/ionic#4397]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>ionic doesn't run any command.

```
$ ionic address
undefined:0

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.module.exports.load (/usr/local/share/npm/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:11:24)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/stats.js:517:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/info.js:8:18)
```

please help me..</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ceo-mint-soft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4397). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4397)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Mind posting over here and trying new version of CLI? https://github.com/driftyco/ionic-cli/issues
