### ISSUE TITLE
bug: cordova add platform error!!!

### ISSUE THREAD

**Issue by arist1213** [driftyco/ionic#4401]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I was testing with xcode7 on iOS9 sdk. After I update ionic version to 1.6.4. This error appears.

This is mine currently version:
ionic -v
1.6.4
cordova -v
5.0.0

This is mine error:
ionic start testing blank
cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@3.8.0
Running command: /Users/yanming/Desktop/ionicDemo/testing/hooks/after_prepare/010_add_platform_class.js /Users/yanming/Desktop/ionicDemo/testing
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:100:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @arist1213!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4401). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4401)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by richardsun29** [comment]
Is `010_add_platform_class.js` executable? Try running: 
```
chmod +x /Users/yanming/Desktop/ionicDemo/testing/hooks/after_prepare/010_add_platform_class.js
```

**Comment by jgw96** [comment]
Thanks for opening this issue with us! As this issue is more related to the ionic-cli i will be moving this issue over to that repo, please feel free to continue the conversation on this issue there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#844
