### ISSUE TITLE
bug: Getting error on before_prepare hook

### ISSUE THREAD

**Issue by FrikkinLazer** [driftyco/ionic#4406]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I have any js file present in the before_prepare hook folder (even when the js file is completely empty), I am getting this error:

Error: spawn UNKNOWN
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (C:\Users\Bertus\AppData\Roaming\npm\node_modules\co
rdova\node_modules\cordova-lib\src\cordova\superspawn.js:100:31)
    at runScriptViaChildProcessSpawn (C:\Users\Bertus\AppData\Roaming\npm\node_m
odules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:189:23)
    at runScript (C:\Users\Bertus\AppData\Roaming\npm\node_modules\cordova\node_
modules\cordova-lib\src\hooks\HooksRunner.js:132:16)
    at C:\Users\Bertus\AppData\Roaming\npm\node_modules\cordova\node_modules\cor
dova-lib\src\hooks\HooksRunner.js:115:20
    at _fulfilled (C:\Users\Bertus\AppData\Roaming\npm\node_modules\cordova\node
_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Bertus\AppData\Roaming\npm\node_modul
es\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Bertus\AppData\Roaming\npm\node
_modules\cordova\node_modules\q\q.js:749:13)

I have given the folders full control access to the Everyone user in windows.</span>

<span is-issue-template></span>

**Comment by FrikkinLazer** [comment]
The problem was the the script has to start with this line:
#!/usr/bin/env node

**Comment by mlynch** [comment]
Thanks for letting us know!
