### ISSUE TITLE
bug: Uncaught TypeError: Cannot set property 'content'

### ISSUE THREAD

**Issue by webmak** [driftyco/ionic#4523]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When change device orientation got 

Uncaught TypeError: Cannot set property 'content' of undefined

viewportTagUpdate @ ionic.bundle.js:4370
viewportUpdate @ ionic.bundle.js:4358</span>

<span is-issue-template></span>

**Comment by Neophy7e** [comment]
I'm having the same issue. My ionic version is 1.1.0.

**Comment by pratikpalashikar** [comment]
yes I am facing it too.
0     197140   error    TypeError: Cannot set property 'btn_add' of undefined
    at new <anonymous> (http://localhost:8100/js/controller.js:222:20)
    at invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13277:17)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13285:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17841:28
    at self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52255:24)
    at Object.switcher.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50449:41)
    at Object.switcher.init (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50369:20)
    at self.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52115:14)
    at self.register (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52073:10)
    at updateView (http://localhost:8100/lib/ionic/js/ionic.bundle.js:57485:23)

**Comment by mhartington** [comment]
Please provide a codepen or some example of this.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by bcabs** [comment]
I had this occur for me as well.
