### ISSUE TITLE
bug: Android app crashes after updating Ionic CLI to 1.7.8

### ISSUE THREAD

**Issue by noldotar** [driftyco/ionic#4636]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, after updating Ionic CLI to 1.7.8 Android app crashes (iOS and browser versions works correctly).

My conf:
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.8
Ionic App Lib Version: 0.6.4
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.1.1 Build version 7B1005

cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
ionic-plugin-keyboard 1.0.7 "Keyboard"
phonegap-facebook-plugin 0.12.0 "Facebook Connect"
phonegap-plugin-push 1.4.2 "PushPlugin"</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @noldotar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4636). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4636)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by noldotar** [comment]
Here is my log (adb logcat) while running the app on my Samsung Galaxy S5 SM-G00F (Android 5.0)
```
I/chromium( 3688): [INFO:CONSOLE(173)] "JSON file loaded: it/list.json", source: file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js (173)
D/PluginManager( 3688): exec() call to unknown plugin: Console
I/chromium( 3688): [INFO:CONSOLE(173)] "All files cached", source: file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js (173)
V/StatusBar( 3688): Executing action: backgroundColorByHexString
V/PushPlugin( 3688): execute: action=init
V/PushPlugin( 3688): execute: data=[{"android":{"senderID":"906249436416","sound":true,"vibrate":true},"ios":{"sound":true,"badge":true,"alert":true}}]
V/PushPlugin( 3688): execute: jo={"senderID":"906249436416","sound":true,"vibrate":true}
V/PushPlugin( 3688): execute: senderID=906249436416
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
E/AndroidRuntime( 3688): FATAL EXCEPTION: pool-2-thread-2
E/AndroidRuntime( 3688): Process: com.unidea.skiword, PID: 3688
E/AndroidRuntime( 3688): java.lang.NoSuchMethodError: No virtual method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.unidea.skiword-1/base.apk)
E/AndroidRuntime( 3688): 	at com.google.android.gms.iid.zzd.zzdL(Unknown Source)
E/AndroidRuntime( 3688): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime( 3688): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime( 3688): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
E/AndroidRuntime( 3688): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
E/AndroidRuntime( 3688): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:72)
E/AndroidRuntime( 3688): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 3688): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 3688): 	at java.lang.Thread.run(Thread.java:818)
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
V/ApplicationPolicy(  921): isApplicationStateBlocked userId 0 pkgname com.unidea.skiword
W/ActivityManager(  921):   Force finishing activity com.unidea.skiword/.MainActivity
D/FocusedStackFrame(  921): Set to : 0
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/SSRM:m  (  921): SIOP:: AP = 330, PST = 305, CUR = 450
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
I/SQLiteSecureOpenHelper( 3799): getWritableDatabase(pwd)
I/SQLiteSecureOpenHelper( 3799): getDatabaseLocked(b,b,pwd)...
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/StatusBarManagerService(  921): manageDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams
I/SQLiteSecureOpenHelper( 3799): getWritableDatabase(pwd)
I/SQLiteSecureOpenHelper( 3799): getDatabaseLocked(b,b,pwd)...
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
W/ActivityManager(  921): mDVFSHelper.acquire()
I/dumpstate( 3788): begin
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/SurfaceWidgetView( 1495): destroyHardwareResources():691982078
V/WindowOrientationListener(  921): mSContextAutoRotationListener.getProposedRotation, mbResultFaceDectection: false
V/WindowOrientationListener(  921): mSContextAutoRotationListener.getProposedRotation, Rotation: -1
V/WindowManager(  921): rotationForOrientationLw(orient=1, last=0); user=0  sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false
V/WindowOrientationListener(  921): mSContextAutoRotationListener.getProposedRotation, mbResultFaceDectection: false
V/WindowOrientationListener(  921): mSContextAutoRotationListener.getProposedRotation, Rotation: -1
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/Launcher( 1495): onRestart, Launcher: 120085039
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/CrashAnrDetector(  921): processName: com.unidea.skiword
D/CrashAnrDetector(  921): broadcastEvent : com.unidea.skiword data_app_crash
W/ContextImpl(  921): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1643 com.android.server.analytics.data.collection.application.CrashAnrDetector.broadcastEvent:296 com.android.server.analytics.data.collection.application.CrashAnrDetector.processDropBoxEntry:254 com.android.server.analytics.data.collection.application.CrashAnrDetector.access$100:60 com.android.server.analytics.data.collection.application.CrashAnrDetector$1.onReceive:102 
D/Launcher( 1495): onStart, Launcher: 120085039
D/Launcher.HomeView( 1495): onStart
I/SQLiteSecureOpenHelper( 3799): getWritableDatabase(pwd)
I/SQLiteSecureOpenHelper( 3799): getDatabaseLocked(b,b,pwd)...
D/Launcher( 1495): onResume, Launcher: 120085039
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/SettingsProvider(  921): name = kids_home_mode
D/SettingsProvider(  921): edmUri: content://com.sec.knox.provider/RestrictionPolicy3
D/SettingsProvider(  921): projectionArgs: isSettingsChangesAllowed
D/SettingsProvider(  921): selectionArgs: false
D/SettingsProvider(  921): selectionArgs: 10010
D/SecContentProvider(  921): uri = 17 selection = isSettingsChangesAllowed
D/SettingsProvider(  921): ret = -1
D/LockPatternUtilsCache( 1171): value : false
D/Launcher.HomeView( 1495): onResume
I/SurfaceFlinger(  250): id=162 createSurf (49x49),1 flag=4, Application Error: com.unidea.skiword
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
I/OpenGLRenderer(  921): Initialized EGL, version 1.4
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/Launcher( 1495): setSystemUiTransparency.SettingNotFoundException : set as TRUE
D/Launcher( 1495): Launcher::setSystemUiTransparency(): getSystemUiVisibility() after setting  = 8000
D/MenuAppsGridFragment( 1495): onResume
D/SurfaceWidgetClient$ISurfaceWidgetStub( 2143): [237392/6] Surface widget visibility changed visibility = true on instance = 1
D/SurfaceWidget.Renderer( 2143): [237392/6] SurfaceWidget drawing first frame
I/OpenGLRenderer(  921): HWUI protection enabled for context ,  &this =0x9fa72088 ,&mEglDisplay = 1 , &mEglConfig = 8 
D/ActivityManager(  921): handle home activity for 0
I/WallpaperManagerService(  921): switchPersonaWallpaper is called for personaId-0
D/ActivityManager(  921): post active user change for 0
D/WallpaperManagerService(  921):  force update = false; persona id = 0; current user =0; current persona = 0
D/KnoxTimeoutHandler(  921): postActiveUserChange for user 0
D/KnoxTimeoutHandler(  921): handleActiveUserChange for user 0
I/SurfaceFlinger(  250): id=163 createSurf (1080x1920),1 flag=4, com.sec.android.app.launcher/com.android.launcher2.Launcher
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/ConnectivityService(  921): returning getNetworkInfo(networkType - 1) :[type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "unideadevel", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/SurfaceWidgetView( 1495): getHardwareLayer being called directly
D/accuweather( 2143): [KK AccuPhone]>>> SIV:179 [0:0] cancelA
V/audio_hw_primary(  285): out_standby: enter: usecase(1: low-latency-playback)
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
I/Timeline( 1495): Timeline: Activity_idle id: android.os.BinderProxy@576bb4d time:157101579
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
W/BroadcastQueue(  921): Permission Denial: broadcasting Intent { act=com.sec.android.intent.action.HOME_RESUME flg=0x10 } from com.sec.android.app.launcher (pid=1495, uid=10010) is not exported from uid 1000 due to receiver com.android.settings/.accessibilitywidget.AccessibilityEasyWidgetProviderAssistiveLight
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/StatusBarManagerService(  921): manageDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams
V/audio_hw_primary(  285): stop_output_stream: enter: usecase(1: low-latency-playback)
V/audio_hw_primary(  285): disable_audio_route: enter: usecase(1)
V/audio_hw_primary(  285): disable_audio_route: reset mixer path: low-latency-playback
D/audio_route(  285): ++++ audio_route_update_mixer ==============
D/audio_route(  285): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia5
D/audio_route(  285): Setting mixer control: value: 0
D/audio_route(  285): ------ audio_route_update_mixer ==============
V/audio_hw_primary(  285): disable_audio_route: exit
V/audio_hw_primary(  285): disable_snd_device: snd_device(2: speaker)
D/audio_route(  285): ++++ audio_route_update_mixer ==============
D/audio_route(  285): Setting mixer control: SPK DRV Volume
D/audio_route(  285): Setting mixer control: value: 0
D/audio_route(  285): Setting mixer control: RX7 Digital Volume
D/audio_route(  285): Setting mixer control: value: 0
D/audio_route(  285): Setting mixer control: COMP0 Switch
D/audio_route(  285): Setting mixer control: value: 0
D/audio_route(  285): Setting mixer control: RX7 MIX1 INP1, value: 0
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/audio_route(  285): Setting mixer control: DAC1 Switch
D/audio_route(  285): Setting mixer control: value: 0
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/audio_route(  285): ------ audio_route_update_mixer ==============
V/audio_hw_primary(  285): stop_output_stream: exit: status(0)
V/audio_hw_primary(  285): out_standby: exit
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/GalleryCacheReady(20870): Receive : home resume
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/Mms/UIEventReceiver(20666): ui event
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjRATu9ZqRwmv7A7uEos9Q9mvO4YDA6qaoxYEtGEMNH1w
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjRej64htfcxG5kL3SHyGYDnr4brh3hp83PTv8sTeWgfzb09Wu8w+l9FeW3bXb18r1tcp17zAuCthjNMD7/ctUpMsPOZWZzY9gg1XBOkZWTGk
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjfFK6n2WxeJSk2pAGNbQ5p0X1S2Rcjfuoz/uR69LW7q4dRvDIbb+p93sEFNr9NIFsA==
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjYXOqDX8ezzeYFlqIugeVh9tddYklHQaYJQeZ5D1n0CWhpLwjVw6z1MjJ35DMCBpaiDarp/XHnFoZkDEv7L3KA0=
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjfFK6n2WxeJSk2pAGNbQ5p22QnYVOq7PKBLe2qMCpGYydjAdGQcIiahEY/ZKpSgLLdWk9sWz2GyOXv6qxHaW2H26fDXZ20X1h16kWUzITBbTh7G11qed9LU9uS7nht+c434ovyAFMeLCkHYTLVI5fwY=
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjfFK6n2WxeJSk2pAGNbQ5p3XGW9731/b3rcTnBUpVV7cdjAdGQcIiahEY/ZKpSgLLdWk9sWz2GyOXv6qxHaW2H26fDXZ20X1h16kWUzITBbTuusrI/cx+kAef/132msRDOjT1uSoU6fTNM2FcLdxHvc=
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjfFK6n2WxeJSk2pAGNbQ5p2JyN4reRVmsjd9hDStHSrotCc+mJqVQceay8W/Aon4dQ==
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjfFK6n2WxeJSk2pAGNbQ5p1uWsUHzWsv+tlyIgF4nsoYQRDW3di+2lqtjRvD6Foc0OSK79yglawLMq2qfKHF0t+rzoiO7awSXeKcgiSJMfNZu89EQ821mpIbyCdOp1WNyQ==
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjfFK6n2WxeJSk2pAGNbQ5p3cXw/c05/SMEtFN8iBNLnY4tvU5wsp5Dwccfz++DFQoQ==
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjfFK6n2WxeJSk2pAGNbQ5p1QdJyd/p15/7HTe6I45I69M4svW0ahfvr+YIey5W092wGcTlQvpBSgOqyfO72Z3wUxq59dXfXVWbt+zgy3TJ0U
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjRATu9ZqRwmv7A7uEos9Q9mvO4YDA6qaoxYEtGEMNH1w
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjRej64htfcxG5kL3SHyGYDnr4brh3hp83PTv8sTeWgfzb09Wu8w+l9FeW3bXb18r1tcp17zAuCthjNMD7/ctUpMsPOZWZzY9gg1XBOkZWTGk
D/GeoLookout(31880): H: oG7yKmvlgCB+MeB9ScCFjVjhROowReQZ6uZ83+PHbxXxfrUuNQHmPlY4PsIKqeHXpHMfmw7BKa8EvZP1XFE95vEpSHlOxg9XQoR6KQvcMJUezCj+VlRSvYmiaFKv4yMdF9ANJ7ri8t1rvBR++sDAZA==
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
V/TaskCloserActivity(31864): TaskCloserActivity onReceive() - com.sec.android.intent.action.HOME_RESUME
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
E/android.os.Debug(  921): !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
W/ActivityManager(  921): mDVFSHelper.release()
I/ActivityManager(  921): Killing 31188:com.samsung.android.intelligenceservice/u0a45 (adj 15): bgCount ##41
I/Timeline(  921): Timeline: Activity_windows_visible id: ActivityRecord{361ad170 u0 com.sec.android.app.launcher/com.android.launcher2.Launcher t514} time:157101880
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
W/libprocessgroup(  921): failed to open /acct/uid_10045/pid_31188/cgroup.procs: No such file or directory
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
I/SurfaceFlinger(  250): id=161 Removed com.unidea.skiword/com.unidea.skiword.MainActivity (6/10)
I/SurfaceFlinger(  250): id=161 Removed com.unidea.skiword/com.unidea.skiword.MainActivity (-2/10)
I/SurfaceFlinger(  250): id=160 Removed com.unidea.skiword/com.unidea.skiword.MainActivity (6/9)
I/SurfaceFlinger(  250): id=160 Removed com.unidea.skiword/com.unidea.skiword.MainActivity (-2/9)
D/LockPatternUtilsCache( 1171): getCarrierLockPlusMode()
D/LockPatternUtilsCache( 1171): value : false
```

**Comment by noldotar** [comment]
Updating on 1.7.10 it works again
