### ISSUE TITLE
bug: Promise is not defined

### ISSUE THREAD

**Issue by germgerm** [driftyco/ionic#4689]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I just ran into this issue with ionic 1.1.1 on android 4.4.2
The same app installed on 5.1.1 or run via ripple does not encounter this error

Promise is not defined
 at file:///android_asset/www/js/bundle.js:5156:25
 at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:23399:28)
 at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:23415:27
 at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24678:28)
 at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24489:31)
 at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24783:24)
 at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19196:47)
 at completeRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19368:7)
 at XMLHttpRequest.requestLoaded (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19309:9)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @germgerm!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4689). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4689)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Very odd, do you have a demo or some code to see? From what I can gather from a forum post (yours?) and other info on the web, you might be using Angular's promise's incorrectly, which would explain why the work on 5.1 which might have native Promise support already.

You'll want to do this:

```
controller('MyCtrl', ['$q', function($q) {
  var q = $q.defer();
  return q.promise;
}])
```

Don't use the native `new Promise` yet.
