### ISSUE TITLE
Swipper in modal give strange exception on modal open

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#4851]
I'm getting strange exception when opening modal with swipper inside.

Error: [filter:notarray] Expected array but received: 1436171
http://errors.angularjs.org/1.4.3/filter/notarray?p0=1436171
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13248:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:31431:31
    at fn (eval at <anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:26325:15), <anonymous>:4:221)
    at trackByIdExpFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:40253:20)
    at ngRepeatAction (http://localhost:8100/lib/ionic/js/ionic.bundle.js:40310:25)
    at Object.$watchCollectionAction [as fn] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:28728:13)
    at Scope.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:28863:29)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:29131:24)
    at done (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23544:47)
    at completeRequest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23716:7)(anonymous function) @ ionic.bundle.js:25510(anonymous function) @ ionic.bundle.js:22289Scope.$digest @ ionic.bundle.js:28881Scope.$apply @ ionic.bundle.js:29131done @ ionic.bundle.js:23544completeRequest @ ionic.bundle.js:23716requestLoaded @ ionic.bundle.js:23657
ionic.bundle.js:25510 Device ID has being randomly generated

**Comment by Ionitron** [comment]
Greetings @szuzul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4851). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4851)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by szuzul** [comment]
Fixed
