### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bluecitymoon** [driftyco/ionic#4958]
Hi Team,

I am running into an issue with error of 'RangeError: Maximum call stack size exceeded' when I have two collection-repeat in a single page.

detailed information
```javascript
RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at render (http://localhost:8101/lib/ionic/js/ionic.bundle.js:59659:12)
    at RepeatController.scrollView.__callback [as __$callback] (http://localhost:8101/lib/ionic/js/ionic.bundle.js:59483:9)
    at RepeatController.scrollView.__callback [as __$callback] (http://localhost:8101/lib/ionic/js/ionic.bundle.js:59485:18)
    at RepeatController.scrollView.__callback [as __$callback] (http://localhost:8101/lib/ionic/js/ionic.bundle.js:59485:18)
    at RepeatController.scrollView.__callback [as __$callback] (http://localhost:8101/lib/ionic/js/ionic.bundle.js:59485:18)
    at RepeatController.scrollView.__callback [as __$callback] (http://localhost:8101/lib/ionic/js/ionic.bundle.js:59485:18)
```

This is really interesting that if I only get one collection-repeat, everything works well, but.. if I get two, I will have the error.

Here is what my page looks like:

```javascript
<ion-item collection-repeat="category in categories" class="tadpole-noborder" collection-item-width="'20%'" style="text-align: center">
      <a class="button button-clear" ng-href="#/searchreport/{{type.id}}">
        <i class="{{category.icon}} {{category.color}}"></i>
      </a>
      <br>
      {{category.name}}

    </ion-item>

    <ion-item collection-repeat="product in highlightProducts" collection-item-width="'50%'" style="text-align: center">
      <a class="button button-clear">
        <i class="{{product.pic}} {{product.c}}"></i>
      </a>
      <br>
      {{product.productName}}

    </ion-item>
```

The data in the controller.

```javascript
.controller('DashCtrl', function($scope) {

    $scope.categories = [
      {name: '瓜子', icon: 'ion-log-in', id: 'signin', color: 'balanced'},
      {name: '水果', icon: 'ion-log-out', id: 'signout', color: 'assertive'},
      {name: '啤酒', icon: 'ion-ios-compose-outline', id: 'taskPlan', color: 'positive'},
      {name: '花生', icon: 'ion-ios-color-wand', id: 'executePlan', color: 'royal'},
      {name: '鸭子', icon: 'ion-ios-paper-outline', id: 'tempWork', color: 'energized '},
      {name: '鸡翅', icon: 'ion-ios-personadd-outline', id: 'newCustomer', color: 'calm'},
      {name: '瓜子', icon: 'ion-log-in', id: 'signin', color: 'balanced'},
      {name: '水果', icon: 'ion-log-out', id: 'signout', color: 'assertive'},
      {name: '啤酒', icon: 'ion-ios-compose-outline', id: 'taskPlan', color: 'positive'},
      {name: '花生', icon: 'ion-ios-color-wand', id: 'executePlan', color: 'royal'}
    ];

    $scope.highlightProducts = [
      {productName : 'Nike', pic: 'ion-log-in', c: 'balanced'}
    ];
  })
```

Thanks a lot for your good framework. Hopefully ionic getting better in the new year!

Regards,
Jerry

**Comment by bluecitymoon** [comment]
additionally, my ionic information looks like this:

```javascript

$: ionic info

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.4
Xcode version: Xcode 7.2 Build version 7C68 

```

**Comment by bluecitymoon** [comment]
```javascript
<div class="row row-wrap">
      <div class="col col-50" ng-repeat="item in items">     
       //elements
      </div>
    </div>
```

I solved it with such kind of code structure. hopefully be helpful for guys who need it.

**Comment by xgzl87** [comment]
double collection-repeat How to solve
