### ISSUE TITLE
failed installing ionic2 on a fresh windows 10 so

### ISSUE THREAD

**Issue by KabluBR** [driftyco/ionic#5140]
It just not install... tried with many versions of npm.

LOG

```
C:\Users\Kablu\AppData\Roaming\npm\ionic -> C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\bin\ionic

> fsevents@1.0.6 install C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-watch\node_modules\chokidar\node_modules\fsevents
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-watch\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32\fse.node --module_name=fse --module_path=C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-watch\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32' (1)

> fsevents@1.0.6 install C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32\fse.node --module_name=fse --module_path=C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32' (1)

> ionic@2.0.0-beta.17 postinstall C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic
> node lib/tasks/postinstall


> spawn-sync@1.0.15 postinstall C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall


> node-sass@3.4.2 install C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js


> node-sass@3.4.2 postinstall C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-46\binding.node exists. 
 testing binary.
Binary is fine; exiting.
spawn-sync@1.0.15 C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\cross-spawn\node_modules\spawn-sync
node-sass@3.4.2 C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-sass\node_modules\node-sass
- npm node_modules\ionic\node_modules\npm
C:\Users\Kablu\AppData\Roaming\npm
└── ionic@2.0.0-beta.17 

```

AND MORE LOG

```
    return gyp_main(args)
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Kablu\AppData\Roaming\npm\
node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Kablu\\
AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.
js" "configure" "--fallback-to-build" "--module=C:\\Users\\Kablu\\AppData\\Roami
ng\\npm\\node_modules\\ionic\\node_modules\\ionic-app-lib\\node_modules\\gulp-wa
tch\\node_modules\\chokidar\\node_modules\\fsevents\\lib\\binding\\Release\\node
-v46-win32-ia32\\fse.node" "--module_name=fse" "--module_path=C:\\Users\\Kablu\\
AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\ionic-app-lib\\node_mo
dules\\gulp-watch\\node_modules\\chokidar\\node_modules\\fsevents\\lib\\binding\
\Release\\node-v46-win32-ia32"
gyp ERR! cwd C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\
ionic-app-lib\node_modules\gulp-watch\node_modules\chokidar\node_modules\fsevent
s
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\
node.exe C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-g
yp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Kablu\AppData
\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-wat
ch\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v46-win3
2-ia32\fse.node --module_name=fse --module_path=C:\Users\Kablu\AppData\Roaming\n
pm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-watch\node_mo
dules\chokidar\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32' (1
)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Kablu\AppData\
Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-watc
h\node_modules\chokidar\node_modules\fsevents\node_modules\node-pre-gyp\lib\util
\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users
\\Kablu\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\ionic-app-lib
\\node_modules\\gulp-watch\\node_modules\\chokidar\\node_modules\\fsevents\\node
_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node
_modules\ionic-app-lib\node_modules\gulp-watch\node_modules\chokidar\node_module
s\fsevents
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
npm WARN install:fsevents@1.0.6 fsevents@1.0.6 install: `node-pre-gyp install --
fallback-to-build`
npm WARN install:fsevents@1.0.6 Exit status 1
Traceback (most recent call last):
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Kablu\AppData\Roaming\npm\
node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Kablu\\
AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.
js" "configure" "--fallback-to-build" "--module=C:\\Users\\Kablu\\AppData\\Roami
ng\\npm\\node_modules\\ionic\\node_modules\\ionic-app-lib\\node_modules\\webpack
\\node_modules\\watchpack\\node_modules\\chokidar\\node_modules\\fsevents\\lib\\
binding\\Release\\node-v46-win32-ia32\\fse.node" "--module_name=fse" "--module_p
ath=C:\\Users\\Kablu\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\
ionic-app-lib\\node_modules\\webpack\\node_modules\\watchpack\\node_modules\\cho
kidar\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32"
gyp ERR! cwd C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node_modules\
ionic-app-lib\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\
node_modules\fsevents
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\
node.exe C:\Users\Kablu\AppData\Roaming\npm\node_modules\npm\node_modules\node-g
yp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Kablu\AppData
\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\
node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\R
elease\node-v46-win32-ia32\fse.node --module_name=fse --module_path=C:\Users\Kab
lu\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_module
s\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib
\binding\Release\node-v46-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Kablu\AppData\
Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\n
ode_modules\watchpack\node_modules\chokidar\node_modules\fsevents\node_modules\n
ode-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users
\\Kablu\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\ionic-app-lib
\\node_modules\\webpack\\node_modules\\watchpack\\node_modules\\chokidar\\node_m
odules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fa
llback-to-build"
node-pre-gyp ERR! cwd C:\Users\Kablu\AppData\Roaming\npm\node_modules\ionic\node
_modules\ionic-app-lib\node_modules\webpack\node_modules\watchpack\node_modules\
chokidar\node_modules\fsevents
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
npm WARN install:fsevents@1.0.6 fsevents@1.0.6 install: `node-pre-gyp install --
fallback-to-build`
npm WARN install:fsevents@1.0.6 Exit status 1

```

**Comment by tlancina** [comment]
What version of npm do you have? Looks like it may be https://github.com/npm/npm/issues/10768

**Comment by KabluBR** [comment]
I tried to use v 3.3.12 and it didn't worked too...  other versions like 0.x versions didn`t worked too.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#746
