### ISSUE TITLE
bug: nav.pop(); is getting error!!!!

### ISSUE THREAD

**Issue by vedhagiri** [driftyco/ionic#5226]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I m getting error while pop the screen from view or use the default back button from navigation bar.

Preserve log
.
app.bundle.js:5133 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

app.bundle.js:32060 EXCEPTION: This view has already been destroyed!

app.bundle.js:32051 EXCEPTION: This view has already been destroyed!
app.bundle.js:32051 STACKTRACE:
app.bundle.js:32051 Error: This view has already been destroyed!
    at new BaseException (http://localhost:8100/build/js/app.bundle.js:7707:24)
    at AppView.destroy (http://localhost:8100/build/js/app.bundle.js:18104:20)
    at AppViewManager_.destroyViewInContainer (http://localhost:8100/build/js/app.bundle.js:19901:15)
    at ViewContainerRef_.remove (http://localhost:8100/build/js/app.bundle.js:19303:20)
    at Array.<anonymous> (http://localhost:8100/build/js/app.bundle.js:48085:45)
    at ViewController.destroy (http://localhost:8100/build/js/app.bundle.js:45789:31)
    at http://localhost:8100/build/js/app.bundle.js:48034:19
    at Array.forEach (native)
    at Array.forEach (http://localhost:8100/build/js/app.bundle.js:67:16879)
    at NavController._cleanup (http://localhost:8100/build/js/app.bundle.js:48032:19)
app.bundle.js:7852 Uncaught This view has already been destroyed!
.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
This is a known issue that should be fixed in the latest release. Could you try updating to 2.0.0-alpha.52?

**Comment by vedhagiri** [comment]
@adamdbradley thanks. it works for me. :+1:
