### ISSUE TITLE
feat: issue regarding start ionic applicatiion

### ISSUE THREAD

**Issue by mohsin111** [driftyco/ionic#5366]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I am using Ubuntu 14.04. I have followed all instruction as given on ionic website for install.everything works fine.But when i start application by following command 
 $ sudo ionic start myApp tabs.it shows me an below error 
module.js:341
    throw err;
    ^
Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! As this issue is related to issues with the cli I am going to be moving this issue to that repo. Please feel free to continue with this issue there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#841
