### ISSUE TITLE
CRITICAL Error with Cordova 6

### ISSUE THREAD

**Issue by vcajes** [driftyco/ionic#5369]
Hi, I am having a problem with the new version 6.0 of cordova with IONIC framework (version 1.7.14).

After executing the command on My MAC OSX El Capitan with the latest version of cordova and ionic:

sudo ionic state reset

I get the following error:

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device

/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add cordova-plugin-device":
Fetching plugin "cordova-plugin-device@~1.1.1" via npm
Installing "cordova-plugin-device" for ios
Failed to install 'cordova-plugin-device':TypeError: Cannot read property 'nodeValue' of undefined
    at parsePlistXML (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/plist/lib/parse.js:158:30)
    at parsePlistXML (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/plist/lib/parse.js:134:17)
    at parsePlistXML (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/plist/lib/parse.js:136:26)
    at parsePlistXML (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/plist/lib/parse.js:136:26)
    at parsePlistXML (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/plist/lib/parse.js:136:26)
    at parsePlistXML (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/plist/lib/parse.js:122:23)
    at Object.parse (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/plist/lib/parse.js:48:15)
    at Object.cachedProjectFiles.(anonymous function).getPackageName (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/lib/projectFile.js:82:26)
    at /Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/lib/plugman/Plugman.js:90:61
    at _fulfilled (/Users/vcajes/Documents/Repo/PayAppP2P/platforms/ios/cordova/node_modules/cordova-common/node_modules/q/q.js:834:54)
Error: Cannot read property 'nodeValue' of undefined

AND THIS IS MY package.json file:

{
  "name": "sdfsdfsdf",
  "version": "1.1.1",
  "description": "sdfsdfsdf",
  "dependencies": {
    "gulp": "^3.9.0",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^2.0.4"
  },
  "devDependencies": {
    "bower": "^1.3.3",
    "gulp": "^3.9.0",
    "gulp-angular-templatecache": "^1.8.0",
    "gulp-clean": "^0.3.1",
    "gulp-concat": "^2.6.0",
    "gulp-html-replace": "^1.5.5",
    "gulp-imagemin": "^2.4.0",
    "gulp-jshint": "^2.0.0",
    "gulp-ng-annotate": "^1.1.0",
    "gulp-uglify": "^1.5.1",
    "gulp-util": "^2.2.14",
    "jshint": "^2.9.1",
    "shelljs": "^0.3.0"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-whitelist",
    "com.telerik.plugins.nativepagetransitions",
    "cordova-plugin-actionsheet",
    "cordova-plugin-contacts",
    "cordova-plugin-inappbrowser",
    "de.appplant.cordova.plugin.local-notification",
    "cordova-plugin-pin-dialog",
    "https://github.com/Wizcorp/phonegap-facebook-plugin.git --variable APP_ID=\"23454234235\" --variable APP_NAME=\"asdasdfsdf\"",
    "cordova-plugin-sms",
    "cordova-plugin-globalization"
  ],
  "cordovaPlatforms": [
    "android",
    "ios"
  ]
}

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#743
