### ISSUE TITLE
Bug on Windows Phone 8.1 start

### ISSUE THREAD

**Issue by diogenesjf** [driftyco/ionic#5433]
I'm using ionic with an app and I'm experiencing some problems on starting the app on Windows Phone. I did this steps: https://www.hoessl.eu/2014/12/on-using-the-ionic-framework-for-windows-phone-8-1-apps/ and these https://taco.visualstudio.com/en-us/docs/tutorial-ionic/#configWindows
but still not success. The error is above:

adding proxy for Device
adding proxy for InAppBrowser
adding proxy for SplashScreen
adding proxy for StatusBar
adding proxy for Keyboard
TypeError: Unable to get property 'children' of undefined or null reference
   at B.createHeaderBar (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:443:29455)
   at B.init (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:443:28573)
   at link (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:445:5126)
   at Y (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:104:89)
   at S (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:93:52)
   at g (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:85:384)
   at S (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:92:498)
   at g (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.js:85:384)
   at S (ms-appx://com.ionicframework.notapiauiense275808/www/lib/ionic/js/ionic.bundle.min.j
CSS3111: @font-face encountered unknown error.
ionicons.eot
CSS3111: @font-face encountered unknown error.
ionicons.eot

I tried to use the non minified version and the error is on this code:

    // add header-item to the root children
    for (var x = 0; x < headerBarEle[0].children.length; x++) {
      headerBarEle[0].children[x].classList.add('header-item');
    }

It appears that headerBarEle[0] is undefined.

Thank you for the help in advance.

**Comment by mhartington** [comment]
We do not support windows phone 8/8.1
