### ISSUE TITLE
Exception when using 'ionic emulate ios'

### ISSUE THREAD

**Issue by syedtariq2013** [driftyco/ionic#5464]
The following was generated. There were two things wrong: 

1. The message in line 2 was generated even if the platform had been successfully installed before.

2. Exception was generated in cordova.js or node.js

$ ionic emulate ios
• You're trying to build for ios, but don't have the platform installed yet.
∆ Installing ios for you.
√ Installed platform ios

∆ Compiling Sass to CSS
√ Matching patterns: app/theme/app.+(ios|md).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-framework/fonts/**/*.+(ttf|woff|woff2)

∆ Copying HTML
√ Matching patterns: app/**/*.html

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file
√ Sass compilation complete
√ HTML copied to www/build
√ Fonts copied to www/build/fonts
√ Compiling files complete.

Hash: 6b76d4593a8f22448bd1
Version: webpack 1.12.10
Time: 9419ms
        Asset     Size  Chunks             Chunk Names
app.bundle.js  2.55 MB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 356 hidden modules

√ Webpack complete

An Error occurred trying to fall back to Cordova-lib execution: TypeError: Cannot read property 'then' of undefined
    at Object.IonicTask.runCordova (/usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:296:21)
    at /usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:162:19
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Error happened [TypeError: Cannot read property 'then' of undefined]
TypeError: Cannot read property 'then' of undefined
    at Object.IonicTask.runCordova (/usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:296:21)
    at /usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:162:19
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by tlancina** [comment]
This issue was moved to driftyco/ionic-cli#772
