### ISSUE TITLE
Cannot find module 'archiver' just after installation 

### ISSUE THREAD

**Issue by bussiere** [driftyco/ionic#5468]
I'am on ubuntu 14.04 and nodejs4

ussiere@dagobert:~/WorkspaceSafe/anansimobile$ ionic start anansiMobile blank
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

```

**Comment by cyprusglobe** [comment]
@bussiere can you run ```ionic info```

should look something like this

```
Your system information:

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.57
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.4
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2.1 Build version 7C1002

```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#779
