### ISSUE TITLE
Error on npm update

### ISSUE THREAD

**Issue by clayew** [driftyco/ionic#5496]
#### Short description of the problem:
Error when updating using 
sudo nam update ionic -g

#### What behavior are you expecting?
Installation failure, with a message that it is likely a problem with the ionic package (please see message in code area below).

**Steps to reproduce:**
1. sudo npm update ionic -g

```
$ sudo npm update ionic -g
npm http GET https://registry.npmjs.org/ionic
npm http 304 https://registry.npmjs.org/ionic
npm http GET https://registry.npmjs.org/ionic/2.0.0-beta.17
npm http 304 https://registry.npmjs.org/ionic/2.0.0-beta.17
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic

> ionic@2.0.0-beta.17 postinstall /usr/local/lib/node_modules/ionic
> node lib/tasks/postinstall


/usr/local/lib/node_modules/ionic/lib/tasks/postinstall.js:9
execSync(cmd, {stdio: [0,1,2]});
^
TypeError: undefined is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/tasks/postinstall.js:9:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! ionic@2.0.0-beta.17 postinstall: `node lib/tasks/postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ionic@2.0.0-beta.17 postinstall script.
npm ERR! This is most likely a problem with the ionic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/tasks/postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls ionic
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 15.3.0
npm ERR! command "node" "/usr/local/bin/npm" "update" "ionic" "-g"
npm ERR! cwd /Users/clayew/Documents/Development/cCure
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/clayew/Documents/Development/cCure/npm-debug.log
npm ERR! not ok code 0
```

**Ionic Version**: latest? 

**Browser & Operating System**: Safari 9.0.3 / Mac OS 10.11.3

**Run `ionic info` from terminal/cmd prompt:**

```
-bash: /usr/local/bin/ionic: No such file or directory
```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#783
