### ISSUE TITLE
bug: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#5523]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I cant prepare an iOS app. And even though I install Cordova, ionic info still says it's not installed.

**Steps:**
-----------------------

ionic start TestIonic2Beta --v2
cd TestIonic2Beta
ionic platform add iOS
ionic prepare iOS

**Results:**
An Error occurred trying to fall back to Cordova-lib execution: TypeError: Cannot read property 'then' of undefined
    at Object.IonicTask.runCordova (/usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:296:21)
    at /usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:162:19
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Error happened [TypeError: Cannot read property 'then' of undefined]
TypeError: Cannot read property 'then' of undefined
    at Object.IonicTask.runCordova (/usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:296:21)
    at /usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:162:19
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

Anthonys-iMac:TestIonic2Beta anthony$ **ionic info**

Your system information:

Cordova CLI: **Not installed**
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.5.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly suggested to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Anthonys-iMac:TestIonic2Beta anthony$ **sudo npm install -g cordova**
Password:
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
cordova@6.0.0 /usr/local/lib/node_modules/cordova
├── ansi@0.3.1
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.7)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, chalk@1.1.1, repeating@1.1.3, configstore@1.4.0, latest-version@1.0.1)
└── cordova-lib@6.0.0 (valid-identifier@0.0.1, opener@1.4.1, properties-parser@0.2.3, nopt@3.0.6, semver@4.3.6, shelljs@0.3.0, dep-graph@1.1.0, npmconf@2.1.2, xcode@0.8.0, request@2.47.0, init-package-json@1.9.3, tar@1.0.2, cordova-serve@1.0.0, aliasify@1.9.0, cordova-app-hello-world@3.10.0, cordova-js@4.1.3, npm@2.14.20)
Anthonys-iMac:TestIonic2Beta anthony$ ionic info

Your system information:

Cordova CLI: **Not installed**
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.5.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly suggested to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
Anthonys-iMac:TestIonic2Beta anthony$</span>

<span is-issue-template></span>

**Comment by tones411** [comment]
Using sudo produces better results. I think it's a permissions issue with my installation of Cordova.
