### ISSUE TITLE
Cannot load module Xmlbuilder

### ISSUE THREAD

**Issue by karajrish** [driftyco/ionic#5524]
#### Short description of the problem:
I have installed ionic on my Ubuntu 14.04 machine as per instructions from the official site. However, when I run the ionic command from my terminal for starting a new application it gives an error with the following stacktrace : 

module.js:327
    throw err;
    ^

Error: Cannot find module 'xmlbuilder'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:12:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:436:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

I have also tried installing xmlbuilder through the npm package installer but to no avail

Please help me in resolving this problem

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#785
