### ISSUE TITLE
bug: 'MSVSProject' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by eidng8** [driftyco/ionic#5661]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Not sure if this is a bug. I'm on a Windows 7 x64, with Visual Studio 2015, Python 2.7, node.js 4.3.1, and npm 3.8.0.

When i install ionic@beta, the following error occurs:

```
D:\>npm i -g ionic@beta
C:\Users\Administrator\AppData\Roaming\npm\ionic -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\bin\ionic

> fsevents@1.0.8 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents
> node-pre-gyp install --fallback-to-build

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build
" "--module=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-x64\\fse.node" "--module_name=fse" "--module_path=C:\\Us
ers\\Administrator\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\bin\node-gyp.js configure --fallb
ack-to-build --module=C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64\fse.node --module_name=fse --module_path=C:\Users\Admin
istrator\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre
-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents
node-pre-gyp ERR! node -v v4.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.21
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\
Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64\fse.node --module_name=fse --module_path=C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\ionic\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64' (1)
npm WARN install:fsevents@1.0.8 fsevents@1.0.8 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:fsevents@1.0.8 Exit status 1

> ionic@2.0.0-beta.18 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic
> node lib/tasks/postinstall


> spawn-sync@1.0.15 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\spawn-sync
> node postinstall


> node-sass@3.4.2 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass
> node scripts/install.js


> node-sass@3.4.2 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass
> node scripts/build.js

` C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
spawn-sync@1.0.15 C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\spawn-sync
node-sass@3.4.2 C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass
C:\Users\Administrator\AppData\Roaming\npm
`-- ionic@2.0.0-beta.18
```</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#802
