### ISSUE TITLE
installing 2.0.0-beta.18 fails

### ISSUE THREAD

**Issue by sclausen** [driftyco/ionic#5662]
#### Short description of the problem:

Installing ionic fails.

#### What behavior are you expecting?

Installing ionic doesn't fail.

**Steps to reproduce:**
``` shell
sudo npm install -g ionic@2.0.0-beta.18
```

**Browser & Operating System**: 
Ubuntu 15.10
npm: 3.7.5
node: v5.7.0
```
npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/ionic/node_modules/.bin/npm" "rebuild" "node-sass" "spawn-sync"
npm ERR! node v5.7.0
npm ERR! npm  v2.14.21
npm ERR! path /usr/lib/node_modules/ionic/node_modules/.bin/node-sass
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/usr/lib/node_modules/ionic/node_modules/.bin/node-sass'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/lib/node_modules/ionic/node_modules/.bin/node-sass']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/lib/node_modules/ionic/node_modules/.bin/node-sass' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/ionic/npm-debug.log
child_process.js:512
    throw err;
    ^

Error: Command failed: npm rebuild node-sass spawn-sync
    at checkExecSyncError (child_process.js:469:13)
    at execSync (child_process.js:509:13)
    at Object.<anonymous> (/usr/lib/node_modules/ionic/lib/tasks/postinstall.js:9:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
/usr/lib
└── (empty)

npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic@2.0.0-beta.18"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE

npm ERR! ionic@2.0.0-beta.18 postinstall: `node lib/tasks/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic@2.0.0-beta.18 postinstall script 'node lib/tasks/postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/tasks/postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/project/npm-debug.log
npm ERR! code 1
sudo npm install -g ionic@2.0.0-beta.18  54,78s user 10,90s system 104% cpu 1:03,07 total
```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#801

**Comment by sclausen** [comment]
sorry, obviously wrong project…
