### ISSUE TITLE
Can not able to add android@4.1.1  giving Internal Error

### ISSUE THREAD

**Issue by mrunwal** [driftyco/ionic#5685]
#### Short description of the problem:
When I try to following commands its giving me error.

```
$ ionic platform add android@4.1.1
Updated the hooks directory to have execute permissions
Adding android project...
Running command: /home/manish/.cordova/lib/npm_cache/cordova-android/4.1.1/package/bin/create /Projects/ionic/MyPrj/platforms/android com.ionicframework.MyPrj918819 MyPrj --cli
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.ionicframework.MyPrj918819
	Name: MyPrj
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
Running command: /Projects/ionic/MyPrj/hooks/before_prepare/update_version.js /Projects/ionic/MyPrj
Build number successfully incremented
shell.js: internal error
Error: ENOENT: no such file or directory, stat '/Projects/ionic/MyPrj/www/*'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at /usr/local/lib/node_modules/shelljs/src/cp.js:148:21
    at Array.forEach (native)
    at Object._cp (/usr/local/lib/node_modules/shelljs/src/cp.js:144:13)
    at Object.cp (/usr/local/lib/node_modules/shelljs/src/common.js:240:23)
    at android_parser.update_www (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/metadata/android_parser.js:330:11)
    at PlatformApiPoly.prepare (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:209:18)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:100:32
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
$ Projects/ionic/MyPrj ls /Projects/ionic/MyPrj/www/*

```

**Ionic Version**: 1.x 

**Browser & Operating System**: Android

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.0.0

```

**Comment by mrunwal** [comment]
Just to add one more points. Directory www/* which is already their on given location. Still I am doubtful why such error is showing it. Even permission for the directory is same as user logged in. for the same directory structure it was working (before update) but after update ionic its giving error.

**Comment by mrunwal** [comment]
It looks like issue is not with shelljs. Its issue with version of node. Once I updated the node to v5.6.0 and reinstalled ionic and cordova then everything works smoothly.

so closing this.
