### ISSUE TITLE
NgSwitch, NgSwitchWhen, NgSwitchDefault not work: Unexpected directive value 'undefined' 

### ISSUE THREAD

**Issue by SoaringTiger** [driftyco/ionic#5717]
#### Short description of the problem:
When try to test NgSwitch directive follow the code in 
https://angular.io/docs/js/latest/api/common/NgSwitch-directive.html

```
//insert any relevant code between the above and below backticks
import {
  Component,
  View,
  NgSwitch,
  NgSwitchWhen,
  NgSwitchDefault
} from 'angular2/core';

@Component({
  selector: 'test-component',
})
@View({
  template: `
    <p>Value = {{value}}</p>
    <button (click)="inc()">Increment</button>
    <div [ngSwitch]="value">
      <p *ngSwitchWhen="'init'">increment to start</p>
      <p *ngSwitchWhen="0">0, increment again</p>
      <p *ngSwitchWhen="1">1, increment again</p>
      <p *ngSwitchWhen="2">2, stop incrementing</p>
      <p *ngSwitchDefault>&gt; 2, STOP!</p>
    </div>
  `,
  directives: [NgSwitch, NgSwitchWhen, NgSwitchDefault]
})

export class TestComponent {

  constructor() {
    this.value = 'init';
  }

  inc() {
    this.value = this.value === 'init' ? 0 : this.value + 1;
  }
}
```

**Ionic Version**: 2.0.0-beta.17/19

**Browser & Operating System**: Chrome

**Run from Chrome console**

```
EXCEPTION: Unexpected directive value 'undefined' on the View of component 'TestComponent'
app.bundle.js:33836 EXCEPTION: Unexpected directive value 'undefined' on the View of component 'TestComponent'BrowserDomAdapter.logError @ app.bundle.js:33836BrowserDomAdapter.logGroup @ app.bundle.js:33846ExceptionHandler.call @ app.bundle.js:7816(anonymous function) @ app.bundle.js:16945NgZone._notifyOnError @ app.bundle.js:17604NgZone._createInnerZone.collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17499run @ app.bundle.js:1164NgZone._createInnerZone.zone.fork.fork.$run @ app.bundle.js:17517zoneBoundFn @ app.bundle.js:1134lib$es6$promise$$internal$$tryCatch @ app.bundle.js:2534lib$es6$promise$$internal$$invokeCallback @ app.bundle.js:2546lib$es6$promise$$internal$$publish @ app.bundle.js:2517(anonymous function) @ app.bundle.js:1266NgZone._createInnerZone.zone.fork.fork.$scheduleMicrotask.microtask @ app.bundle.js:17557run @ app.bundle.js:1161NgZone._createInnerZone.zone.fork.fork.$run @ app.bundle.js:17517zoneBoundFn @ app.bundle.js:1134lib$es6$promise$asap$$flush @ app.bundle.js:2328
app.bundle.js:33836 STACKTRACE:BrowserDomAdapter.logError @ app.bundle.js:33836ExceptionHandler.call @ app.bundle.js:7818(anonymous function) @ app.bundle.js:16945NgZone._notifyOnError @ app.bundle.js:17604NgZone._createInnerZone.collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17499run @ app.bundle.js:1164NgZone._createInnerZone.zone.fork.fork.$run @ app.bundle.js:17517zoneBoundFn @ app.bundle.js:1134lib$es6$promise$$internal$$tryCatch @ app.bundle.js:2534lib$es6$promise$$internal$$invokeCallback @ app.bundle.js:2546lib$es6$promise$$internal$$publish @ app.bundle.js:2517(anonymous function) @ app.bundle.js:1266NgZone._createInnerZone.zone.fork.fork.$scheduleMicrotask.microtask @ app.bundle.js:17557run @ app.bundle.js:1161NgZone._createInnerZone.zone.fork.fork.$run @ app.bundle.js:17517zoneBoundFn @ app.bundle.js:1134lib$es6$promise$asap$$flush @ app.bundle.js:2328
app.bundle.js:33836 Error: Unexpected directive value 'undefined' on the View of component 'TestComponent'
    at new BaseException (http://192.168.99.100:9200/build/js/app.bundle.js:7694:24)
    at RuntimeMetadataResolver.getViewDirectivesMetadata (http://192.168.99.100:9200/build/js/app.bundle.js:40690:24)
    at TemplateCompiler._compileNestedComponentRuntime (http://192.168.99.100:9200/build/js/app.bundle.js:35343:66)
    at http://192.168.99.100:9200/build/js/app.bundle.js:35328:88
    at Array.forEach (native)
    at Array.forEach (http://192.168.99.100:9200/build/js/app.bundle.js:66:16879)
    at http://192.168.99.100:9200/build/js/app.bundle.js:35328:44
    at Zone.run (http://192.168.99.100:9200/build/js/app.bundle.js:1161:18)
    at Zone.NgZone._createInnerZone.zone.fork.fork.$run [as run] (http://192.168.99.100:9200/build/js/app.bundle.js:17517:43)
    at zoneBoundFn (http://192.168.99.100:9200/build/js/app.bundle.js:1134:20)
```

**Comment by SoaringTiger** [comment]
remove the line:
directives: [NgSwitch, NgSwitchWhen, NgSwitchDefault]
and component will work
