### ISSUE TITLE
Ionic v2 - Unable to use generated service using Ionic g provider Service - Exception thrown by ionic serve

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#5811]
#### Short description of the problem:
When I include a new service that is generated by
```ionic g provider test```
I am unable to import / inject it and use it.

#### What behavior are you expecting?
I am expecting ionic serve to launch the page properly.

**Steps to reproduce:**
1. ionic g provider test
2. Crete the following page
3. ionic serve
```
import {Page, NavController,NavParams} from 'ionic-angular';
import {Inject} from 'angular2/core';
import {ItemDetailsPage} from '../item-details/item-details';
import {Test} from '../../providers/test/test';
/*
  Generated class for the FeaturedPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Page({
  templateUrl: 'build/pages/featured/featured.html',
  providers: [Test]
})
export class Featured {
  

  static get parameters() {
    return [[NavController], [NavParams]];
  }

  constructor(nav, navParams) {
    this.nav = nav;
    // If we navigated to this page, we will have an item available as a nav param
    //this.selectedItem = navParams.get('item');
    
  }
  openDetails(item){
    this.nav.push(ItemDetailsPage, {
       item: item
     });
  }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 ./app/providers/test/test.js
Module build failed: SyntaxError: /Users/antoineawad/WebstormProjects/ionic2_beta19/app/providers/test/test.js: Unexpected token (12:14)
  10 | @Injectable()
  11 | export class Test {
> 12 |   constructor(@Inject(Http) http) {
     |               ^
  13 |     this.http = http;
  14 |     this.data = null;
  15 |   }
  at Parser.pp.raise (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:1412:13)
    at Parser.pp.unexpected (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:2895:8)
    at Parser.pp.parseBindingAtom (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:1583:12)
    at Parser.pp.parseMaybeDefault (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:1622:23)
    at Parser.pp.parseBindingList (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:1605:23)
    at Parser.pp.parseMethod (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:1092:22)
    at Parser.pp.parseClassMethod (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:2573:8)
    at Parser.pp.parseClassBody (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:2534:10)
    at Parser.pp.parseClass (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:2417:8)
    at Parser.pp.parseStatement (/Users/antoineawad/WebstormProjects/ionic2_beta19/node_modules/babel-core/node_modules/babylon/index.js:1881:19)
 @ ./app/pages/featured/featured.js 18:12-48 (CLI v2.0.0-beta.19)

**Which Ionic Version?** Version 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
$ ionic info
Your system information:
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by jgw96** [comment]
Thanks for all the detailed information! We really appreciate detailed issues like this! As this is an issue that is related to the ionic cli i am going to be moving this issue over to the ionic-cli repo. Please feel free to continue the conversation on this bug over there.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#834
