### ISSUE TITLE
Ionic launching blank app for W10

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic#5988]
Today I formatted my computer and re-installed did a fresh install on node, ionic, cordova and gulp. Now I'm having issues running a fresh app on windows.

I created a fresh app with ionic start, which works with ionic serve. I added windows as a platform and when I try to run it I only get a blank app. The same happens with ionic conference app. I remember running these two apps a few weeks ago and it worked properly on windows.

Running `ionic run windows` will launch a blank app.

Running the app on Visual Studio also launches a blank app and also throws a few errors:

```

APPHOST9601: Can't load <http://maps.googleapis.com/maps/api/js?sensor=false>. An app can't load remote web content in the local context.
index.html

EXCEPTION: SyntaxError: The use of a keyword for an identifier is invalid
SyntaxError: The use of a keyword for an identifier is invalid
   at evalExpression (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:28519:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:10319:13)
   at Anonymous function (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:10279:21)
   at Zone.prototype.run (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:1243:14)
   at Anonymous function (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:27170:25)
   at zoneBoundFn (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:1220:14)
   at lib$es6$promise$$internal$$tryCatch (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:468:10)
   at lib$es6$promise$$internal$$invokeCallback (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:480:10)
   at Anonymous function (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:1028:14)
   at Anonymous function (ms-

SyntaxError: Expected ';'
   at evalExpression (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:28519:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:10319:13)
   at Anonymous function (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:10279:21)
   at Zone.prototype.run (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:1243:14)
   at Anonymous function (ms-appx://io.ionic.conference/www/build/js/app.bundle.js:27170:25)
   at zoneBoundFn (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:1220:14)
   at lib$es6$promise$$internal$$tryCatch (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:468:10)
   at lib$es6$promise$$internal$$invokeCallback (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:480:10)
   at Anonymous function (ms-appx://io.ionic.conference/www/build/js/angular2-polyfills.js:1028:14)
   at Anonymous function (ms-appx://io.ionic.conference/www/build/
```

Current `ionic info`

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS:
Node Version: v5.9.1
```

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! As this issue is more related to the CLI and not the framework I will be moving your issue to the CLI repo. Please feel free to continue the conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#880
