### ISSUE TITLE
angular setAttribute Error in tab directive (title html binding)

### ISSUE THREAD

**Issue by D3CK3R** [driftyco/ionic#610]
When using the new title html binding feature in tabs, i'm getting an angularjs error:

`<tab title="<img src='{{logo}}' id='logo'/>" href="#/main/home/"></tab>`

This doesn't help:
https://github.com/angular/angular.js/issues/3868

Error:
`TypeError: Object #<Comment> has no method 'setAttribute'
    at forEach.attr (http://127.0.0.1:9000/components/angular/angular.js:2476:15)
    at Object.JQLite.(anonymous function) [as attr] (http://127.0.0.1:9000/components/angular/angular.js:2583:9)
    at Object.Attributes.$set (http://127.0.0.1:9000/components/angular/angular.js:5482:28)
    at Object.interpolateFnWatchAction [as fn] (http://127.0.0.1:9000/components/angular/angular.js:6616:28)
    at Scope.$digest (http://127.0.0.1:9000/components/angular/angular.js:11898:29)
    at Scope.$apply (http://127.0.0.1:9000/components/angular/angular.js:12151:24)
    at done (http://127.0.0.1:9000/components/angular/angular.js:7909:45)
    at completeRequest (http://127.0.0.1:9000/components/angular/angular.js:8110:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://127.0.0.1:9000/components/angular/angular.js:8053:11)`

**Comment by karahisarli** [comment]
we are having same error when we try title="{{model.name}}". any idea?
