### ISSUE TITLE
Error when trying to build or run on iOS

### ISSUE THREAD

**Issue by norenma** [driftyco/ionic#6735]
When doing "ionic run ios": 
```
Caught exception:
 TypeError: Cannot read property 'slice' of undefined
    at Object.run (/Users/Markus/.npm-packages/lib/node_modules/ionic/lib/ionic/run.js:44:32)
    at Promise.apply (/Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

And when "ionic build ios"

```
Caught exception:
 TypeError: Cannot read property 'slice' of undefined
    at Object.run (/Users/Markus/.npm-packages/lib/node_modules/ionic/lib/ionic/build.js:29:32)
    at Promise.apply (/Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/Users/Markus/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

Tried using sudo, with the same result. 

Thanks in advance, 
Markus

**Comment by PimCoumans** [comment]
Yup, getting the exact same error. Something broke in the latest version I guess

**Comment by trinhvanhuy** [comment]
Hello, i have same problem when running "ionic platform" 
OS : Windows 10
ionic-cli : v2.0.0-beta.26
cordova-cli : v6.2.0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Very sorry you ran into this issue! It is fixed in the release of the ionic-cli we did this morning, so you just need to update your ionic cli by running `npm install -g ionic@beta` and the issue will be gone (: Thanks for using Ionic!
