### ISSUE TITLE
An Error occurred trying to fall back to Cordova-lib execution: TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#6864]
I am trying to emulate my ionic2 project in iOS/xCode by running the following:

> ionic emulate ios

 however, I receive this:

> Running 'emulate:before' gulp task before emulate
[09:30:04] Starting 'clean'...
[09:30:04] Finished 'clean' after 18 ms
[09:30:04] Starting 'build'...
[09:30:04] Starting 'sass'...
[09:30:04] Starting 'html'...
[09:30:04] Starting 'fonts'...
[09:30:04] Starting 'scripts'...
[09:30:04] Finished 'scripts' after 42 ms
[09:30:04] Finished 'html' after 71 ms
[09:30:04] Finished 'fonts' after 68 ms
[09:30:04] Finished 'sass' after 797 ms
[09:30:10] Finished 'build' after 6.49 s
[09:30:10] Starting 'emulate:before'...
[09:30:10] Finished 'emulate:before' after 4.36 μs

An Error occurred trying to fall back to Cordova-lib execution: TypeError: Cannot read property 'then' of undefined
    at Object.IonicTask.runCordova (/Users/Hamza/.npm-packages/lib/node_modules/ionic/lib/ionic/cordova.js:261:21)
    at /Users/Hamza/.npm-packages/lib/node_modules/ionic/lib/ionic/cordova.js:127:19
    at _fulfilled (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
Error happened TypeError: Cannot read property 'then' of undefined
    at Object.IonicTask.runCordova (/Users/Hamza/.npm-packages/lib/node_modules/ionic/lib/ionic/cordova.js:261:21)
    at /Users/Hamza/.npm-packages/lib/node_modules/ionic/lib/ionic/cordova.js:127:19
    at _fulfilled (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
TypeError: Cannot read property 'then' of undefined
    at Object.IonicTask.runCordova (/Users/Hamza/.npm-packages/lib/node_modules/ionic/lib/ionic/cordova.js:261:21)
    at /Users/Hamza/.npm-packages/lib/node_modules/ionic/lib/ionic/cordova.js:127:19
    at _fulfilled (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/Users/Hamza/.npm-packages/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)

**I am running under IONIC2**

----

Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.2 Build version 7C68 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
 Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************

Any idea about what's going wrong?

**Comment by iosfeng** [comment]
so clear~~~~~


it is highly recommended to install/upgrade the following: 

Please install your Cordova CLI to version >=4.2.0 npm install -g cordova
Install ios-sim to deploy iOS applications. npm install -g ios-sim (may require sudo)
Install ios-deploy to deploy iOS applications to devices. npm install -g ios-deploy (may require sudo)

**Comment by HamzaLJ** [comment]
@iosfeng 
Already tried to do that but I received:

> npm install -g cordova
npm WARN checkPermissions Missing write access to /Users/Hamza/.npm-packages/lib/node_modules/cordova
/Users/Hamza/.npm-packages/lib
└── cordova@6.2.0 

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! path /Users/Hamza/.npm-packages/lib/node_modules/cordova
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/Hamza/.npm-packages/lib/node_modules/cordova'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/Hamza/.npm-packages/lib/node_modules/cordova']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/Hamza/.npm-packages/lib/node_modules/cordova' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Hamza/Documents/new/flavy/npm-debug.log

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. As this is an issue with the Ionic CLI and not the Ionic framework I will be moving this issue to the correct repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1069
