### ISSUE TITLE
Popover Dismiss Causes “RangeError: Maximum call stack size exceeded” on Android Device

### ISSUE THREAD

**Issue by ehussain** [driftyco/ionic#6918]
I am using ionic2 beta8. 

I have copied exact usage example from http://ionicframework.com/docs/v2/2.0.0-beta.8/api/components/popover/Popover/#usage

The only thing I changed is I have created separate files for `popover.ts` `popover.html`. 

After all those changes everything worked fine in browser. But when I test that in Android device, when I try to dismiss the popover (either by calling `this.viewController.dismiss()` method or clicking on backdrop) I see that UI hung up and nothing happens. 

I checked logs in Android Monitoring tool then I found following exception in log.

----------

```text

[INFO:CONSOLE(34947)] "EXCEPTION: Error in ./PopoverCmp class PopoverCmp - inline template:0:14", source: file:///android_asset/www/build/js/app.bundle.js (34947)
[INFO:CONSOLE(34947)] "ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded", source: file:///android_asset/www/build/js/app.bundle.js (34947)
[INFO:CONSOLE(34947)] "ORIGINAL STACKTRACE:", source: file:///android_asset/www/build/js/app.bundle.js (34947)
[INFO:CONSOLE(34947)] "RangeError: Maximum call stack size exceeded
    at Object.re.RequireObjectCoercible (file:///android_asset/www/build/js/es6-shim.min.js)
    at Object.re.ToObject (file:///android_asset/www/build/js/es6-shim.min.js:10:4947)
    at Function.keys (file:///android_asset/www/build/js/es6-shim.min.js:10:24378)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69658:27)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)", source: file:///android_asset/www/build/js/app.bundle.js (34947)
[INFO:CONSOLE(34947)] "ERROR CONTEXT:", source: file:///android_asset/www/build/js/app.bundle.js (34947)
[INFO:CONSOLE(34947)] "[object Object]", source: file:///android_asset/www/build/js/app.bundle.js (34947)
[INFO:CONSOLE(260)] "Uncaught EXCEPTION: Error in ./PopoverCmp class PopoverCmp - inline template:0:14
ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded
ORIGINAL STACKTRACE:
RangeError: Maximum call stack size exceeded
    at Object.re.RequireObjectCoercible (file:///android_asset/www/build/js/es6-shim.min.js)
    at Object.re.ToObject (file:///android_asset/www/build/js/es6-shim.min.js:10:4947)
    at Function.keys (file:///android_asset/www/build/js/es6-shim.min.js:10:24378)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69658:27)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:69665:17)
ERROR CONTEXT:
[object Object]", source: file:///android_asset/www/build/js/zone.js (260)
Debugger is no longer active


```

Here is code I am using

```
import { Component } from '@angular/core';
import { App, NavController, NavParams, MenuController, Popover, ViewController } from "ionic-angular";
import { Storage, LocalStorage } from 'ionic-angular';

import { AuthService } from "./../../../services/user/auth";
import { AuthModel } from "./../../../models/user/auth";


@Component({
	template: `
		<ion-list>
			<ion-list-header>Welcome</ion-list-header>
			<button ion-item (click)="onLogout($event)">Logout</button>
		</ion-list>
	`,
	providers: []
})
class PopoverPage {
	private storage;

	constructor(private viewController: ViewController, private nav: NavController, private authService: AuthService, private auth: AuthModel) {
		this.storage = new Storage(LocalStorage);
	}

	close() {
		console.log('On Close Popover');
		this.viewController.dismiss();
	}

	onLogout() {
		this.close();
	}
}

@Component({
	templateUrl: "build/pages/app/dashboard/dashboard.html",
	providers: []
})
export class DashboardNewPage {
	private storage;

	constructor(protected app: App, protected nav: NavController, protected navParams: NavParams, private menu: MenuController, private authService: AuthService, private auth: AuthModel) {
		this.storage = new Storage(LocalStorage);
	}

	public onPopover(event) {
		let popover = Popover.create(PopoverPage);
		this.nav.present(popover, {
			ev: event
		});
	}
}
```

onPopover function is getting called when nav button is triggered and that markup is present in dashboard.html

This page is rootPage of app and it gets loaded immediately.

Last thing I see in logcat is 'console.log('On Close Popover');' execution. After that it shows exception.

Let me know if I did something wrong here. Please note that this works perfectly fine in browser. But fails in android device.

---------------

I guess that the possible cause might be that:

The object that is passed to ToObject() method is too big - this will work on a desktop browser because it has bigger stack so it could handle it but obviously fails on mobile.

It might be an issue with the es6-shim ToObject() method (either a bug or it's not very effective or not optimized) - most desktop browsers should have a native implementation of this method and therefore it works fine but obviously on mobile there's no native implementation yet.

**Comment by henritoivar** [comment]
Try accessing the specific popover ViewController instance.

`let popover = Popover.create(PopoverPage);` popover is a ViewController instance which is presented by NavController: `this.nav.present(popover, {ev: event });`

You can access it like this for example: `this.nav.last().dismiss();`

**Comment by jgw96** [comment]
Hello @ehussain I can't seem to reproduce this issue with either my Nexus 6, Nexus 7 or Moto X 2014. Would you mind posting a plunker or repo I can use to reproduce this issue? Thanks for using Ionic!

**Comment by iignatov** [comment]
I'm just referencing the related forum discussion for more details: [https://forum.ionicframework.com/t/54511](https://forum.ionicframework.com/t/popover-dismiss-causes-rangeerror-maximum-call-stack-size-exceeded/54511)

**Comment by jgw96** [comment]
Thanks @iignatov

**Comment by Geoffrey-D** [comment]
Hello,

I have the exact same issue that @ehussain . Everything work fine on browser, but when I run it on my android, I have the following error when I close the popup : 

Uncaught EXCEPTION: Error in ./PopoverCmp class PopoverCmp - inline template:0:14
ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded
ORIGINAL STACKTRACE:
RangeError: Maximum call stack size exceeded
    at Object (<anonymous>)
    at Object.ES.ToObject (file:///android_asset/www/build/js/app.bundle.js:39130:14)
    at Function.keys (file:///android_asset/www/build/js/app.bundle.js:40396:36)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:72972:27)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:72982:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:72982:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:72982:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:72982:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:72982:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js:72982:26)
ERROR CONTEXT:
[object Object] 

Can't wait to have a fix :)

**Comment by jgw96** [comment]
Hello @Geoffrey-D do you have a minimal example that I can use to test, like a plunker or test repo? Thanks for using Ionic!

**Comment by Geoffrey-D** [comment]
Hey @jgw96, here is the repo : https://github.com/Geoffrey-D/issue-6918-temp. Everything should be in there (I did it fast). Tell me if you have any issue with it

**Comment by Geoffrey-D** [comment]
Hey @jgw96, I made an other test, the application of the repo is not working on an low-end phone (Wiko highway) but is working on an Samsung S6.

**Comment by bea91** [comment]
Hello @Geoffrey-D same issue on Elephone P7000 android version 5.0, but works fine on Samsung S6 too.

**Comment by rossmartin** [comment]
I'm having the same issue in beta 9.  It happens to me while testing in Chrome and the iOS simulator.

**Comment by Ionitron** [comment]
Greetings @ehussain!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @ehussain!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by tomgallagher** [comment]
You can't close this issue - two other issues have been closed and referenced to this issue, at least 10 people are reporting this problem. Ionitron you don't know what you're doing!

**Comment by Geoffrey-D** [comment]
I can't agree more. This issue is an important one as it crashes smartphones with low memory, even though it works on recent phones. There is a memory leak that needs to be fixed!

**Comment by theskhan** [comment]
I am also getting the exact same issue. Ionic Team, please do not close this issue as this is very important one.  I have tried all sort of fix, but still couldn't found a way to fix it.

You can also replicate this issue on a Genymotion Android Emulator:

Genymotion Android Image: Google Nexus 10 - 5.1.0 - API 22, 2560x1600, 320 DPI, 
Ionic CLI Version:
 v2.0.0-beta.32

Sample Code:
**Template:**
```<ion-header>
  <ion-navbar>
      <ion-buttons end="">
        <button class="disable-hover bar-button bar-button-default bar-button-icon-only">
          <span class="button-inner">
            <ion-icon name="search" role="img" class="ion-ios-search" aria-label="search" ng-reflect-name="search"></ion-icon>
          </span>
          <ion-button-effect></ion-button-effect>
        </button>

        <button class="disable-hover bar-button bar-button-default bar-button-icon-only" (click)="more($event)">
          <span class="button-inner">
            <ion-icon name="more" role="img" class="ion-ios-more" aria-label="more" ng-reflect-name="more"></ion-icon>
          </span>
          <ion-button-effect></ion-button-effect>
        </button>
      </ion-buttons>
      <div class="toolbar-content">
        <ion-title>Popular Stations</ion-title>
      </div>
  </ion-navbar>
</ion-header>
```

Popover Page:
```
import {Component} from '@angular/core';
import {NavController, ViewController} from 'ionic-angular';

@Component({
  template: '
    <ion-list>
      <ion-list-header>Ionic</ion-list-header>
      <button ion-item (click)="close()">Learn Ionic</button>
      <button ion-item (click)="close()">Documentation</button>
      <button ion-item (click)="close()">Showcase</button>
      <button ion-item (click)="close()">GitHub Repo</button>
    </ion-list>'
})

export class MoreOptionsPage {
  constructor(private viewCtrl: ViewController) {}

  close() {
    this.viewCtrl.dismiss();
  }
}
```
Displaying the Popover:
````more(e){
    let popover = Popover.create(MoreOptionsPage);    
    this.nav.present(popover, {ev: e});
  }```

**Comment by henritoivar** [comment]
+1 Using a genymotion Nexus 5 - android 6.0.0 - API 23 emulator.

**Comment by schlaus** [comment]
+1, testing on a Huawei Honor 6, Android 5.1.1.

**Comment by thgfrzm** [comment]
+1 using a Moto G (2013) XT1032, Android 4.4.4. No problems in browser or in Sony Xperia Z3 Compact D5833, Android 5.x.

**Comment by Geoffrey-D** [comment]
Using crosswalk solved the issue for me. For my part, I will use crosswalk in production as I have other issues that crosswalk fixed (the material design animations was also not working without crosswalk). For those that also want to use crosswalk and do https calls, be aware that it will not accept self-signed certificat.

**Comment by pjsb** [comment]
Same problem here with Galasy S6 when passing data on dismiss.

> popover.present({ ev: null }); // <- pass 'null' to event and adjust the CSS
did also work for me. @thgfrzm can you post your css ajustments?

**Comment by thgfrzm** [comment]
hi Jens @pjsb, actually I'm just overwriting the popover-style class. This solution needs some adjustments.
```
.popover-style{
  .popover-content{
    top: 10px !important;
    left: 23% !important;
    transform-origin: right top 0px !important;
  }
}
```

**Comment by bea91** [comment]
Hi @pjsb and @thgfrzm, I think it would be better to set this css adjustments:

` .popover-content{
    top: 44px !important;
    margin-left: auto !important;
    right: 10px !important;
    transform-origin: right top 0px !important;
  }`

**Comment by martijnlutgens** [comment]
I am testing my app with some beta testers and at least one of them has reported this problem. I also have it on my iWork8 tablet which is not a low-spec tablet. I am using ionic2 beta11. Please fix this in the beta12 beceaude this is a mayor release blocker for my app.

**Comment by Geoffrey-D** [comment]
hey @martijnlutgens , be aware that using [crosswalk ](http://ionicframework.com/docs/cli/browsers.html) solve this issue, as well as using some css as explained by @bea91.

Cheers

**Comment by martijnlutgens** [comment]
I know but I didn't want to resort to using crosswalk because I have never used it and that would cost me extra time to figure that out.

I also tried the css but it didn't seem to help. But I found out that I had forgotten to change the event to NULL. The CSS solution from bea91 solved it eventually. Tnx!

**Comment by Geoffrey-D** [comment]
@martijnlutgens I am glad that it helped you, but be aware that crosswalk can be added in 1 code line and will improve (a lot) performances on Android 4.x and fix many issues (like material design on Android 4.x)

**Comment by tomgallagher** [comment]
with the proviso that Crosswalk won't work with Ionic Cloud Package

**Comment by chcaru** [comment]
Still happening for me in rc0 when passing an event into PopupController.present options.

```    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@bapidesign/library-font": "^1.0.0",
    "@ionic/storage": "1.0.3",
    "adal-angular": "^1.0.12",
    "fs": "0.0.1-security",
    "ionic-angular": "2.0.0-rc.0",
    "ionic-native": "2.0.3",
    "ionicons": "3.0.0",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21",```

**Comment by mobinius-shreesha** [comment]
Hi everyone,
           I am working on ionic2 project.but i am facing one issue IOS like,suppose if we open popover or sidemenu continuesly then next time if we open sidemenu or popover it automatically closes.this happens only in IOS.please suggest.

**Comment by mbakker96** [comment]
I've this problem with `ion-refresh`. I added the code from the documentation but got the error `MainPage.html:20 ERROR RangeError: Maximum call stack size exceeded`. I receive this error also when I remove all the other stuff on the page.
