### ISSUE TITLE
error when building ios application ionic 2

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic#7216]
#### Short description of the problem:

I get a error when building the application for iOS. Updated cordova and ionic-cli@beta to latest.

#### What behavior are you expecting?

building iOS application

**Steps to reproduce:**
1.  run ionic build ios

```
$ ionic build ios

Running 'build:before' gulp task before build
[11:52:50] Starting 'clean'...
[11:52:50] Finished 'clean' after 59 ms
[11:52:50] Starting 'build'...
[11:52:50] Starting 'sass'...
[11:52:50] Starting 'html'...
[11:52:50] Starting 'fonts'...
[11:52:50] Starting 'scripts'...
[11:52:51] Finished 'scripts' after 84 ms
[11:52:51] Finished 'fonts' after 93 ms
[11:52:51] Finished 'html' after 101 ms
[11:52:51] Finished 'sass' after 875 ms
[11:53:00] Finished 'build' after 9.52 s
[11:53:00] Starting 'build:before'...
[11:53:00] Finished 'build:before' after 6.07 μs

• You're trying to build for iosbut don't have the platform installed yet.
∆ Installing ios for you.
Installing cordova-plugin-device
Installing cordova-plugin-console
Installing cordova-plugin-whitelist
Installing cordova-plugin-splashscreen
Installing cordova-plugin-statusbar
Installing ionic-plugin-keyboard
Caught exception:
 Error: Command failed: cordova platform add ios
Error: Failed to fetch platform ios
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: Failed to parse json
No data, empty input at 1:1

^

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I reinstalled codova and ionic becease i first got a warning that cordova was deprecated and he could not find cordova-ios and I needed to have version >=4.0.0
 

**Which Ionic Version?** 
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this seems to be an issue with the Ionic CLI and not the framework I will be moving this issue to the appropriate repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1151

**Comment by mbakker96** [comment]
Thanks!
-- 
Met vriendelijke groet  / Regards,

Martijn Bakker

Software (web) development
www.mar-bakker.nl - www.marbakkerdev.nl - www.zapion.nl
