### ISSUE TITLE
bug: ionic serve -l,  not working

### ISSUE THREAD

**Issue by shubhamsinghrajput** [driftyco/ionic#7262]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>shell.js: internal error
Error: EBUSY: resource busy or locked, open 'C:\Users\MORGEN~1\AppData\Local\Temp\shelljs_f346f45a91a42db0d0bc'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at execSync (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\exec.js:67:57)
    at Object._exec (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\exec.js:179:12)
    at Object.exec (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\common.js:168:23)
    at Object.gatherGulpInfo (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\info.js:201:24)
    at Object.t (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:148:15)
    at Object.run (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:123:16)
    at Object.<anonymous> (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\bin\ionic:13:10)</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1165
