### ISSUE TITLE
ORIGINAL EXCEPTION: Error: unsafe value used in a resource URL context

### ISSUE THREAD

**Issue by mangz001** [driftyco/ionic#7453]
after upgraded to beta 10, using existing code from beta 2

the iframe stopped working

**this is my code :**

```
<ion-row style="padding:0;">
    <iframe id="player" align="center" 
      type="text/html" 
      width="640" height="390"
      src="{{content.youtube_url}}?enablejsapi=1&autoplay=0&origin=http://example.com"
      frameborder="0"
      style="width:100%; height:auto;">
    </iframe>
  </ion-row>
```

**this is the error :** 

browser_adapter.js:77 EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in build/pages/listing-detail/listing-detail.html:34:6
ORIGINAL EXCEPTION: Error: unsafe value used in a resource URL context
ORIGINAL STACKTRACE:
Error: unsafe value used in a resource URL context
    at DomSanitizationServiceImpl.sanitize (http://localhost:8101/build/js/app.bundle.js:41319:23)
    at DebugAppView._View_ListingDetailPage0.detectChangesInternal (ListingDetailPage.template.js:571:95)
    at DebugAppView.AppView.detectChanges (http://localhost:8101/build/js/app.bundle.js:30512:14)
    at DebugAppView.detectChanges (http://localhost:8101/build/js/app.bundle.js:30617:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:8101/build/js/app.bundle.js:30538:19)
    at DebugAppView._View_ListingDetailPage_Host0.detectChangesInternal (ListingDetailPage_Host.template.js:44:8)
    at DebugAppView.AppView.detectChanges (http://localhost:8101/build/js/app.bundle.js:30512:14)
    at DebugAppView.detectChanges (http://localhost:8101/build/js/app.bundle.js:30617:44)
    at ViewRef_.detectChanges (http://localhost:8101/build/js/app.bundle.js:30955:65)
    at ViewController.fireWillEnter (http://localhost:8101/build/js/app.bundle.js:56266:22)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by mangz001** [comment]
where can i find plunker`s link for ur latest version (beta 10) ?

**Comment by jgw96** [comment]
Here you go http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview . Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Anujmoglix** [comment]
Here you go http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview . Thanks!

In it i am not able to get any  info about that issue , can you check once ?
