### ISSUE TITLE
Ionic 2: cannot run tests

### ISSUE THREAD

**Issue by fknop** [driftyco/ionic#7770]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

I'm trying to make a PR but I cannot run the tests with `gulp karma` as the `CONTRIBUTING` guide says. I tried to run `gulp bundle.system` before but it still does not work.
#### What behavior are you expecting?

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Here is the output:

```
$ gulp karma
[15:10:32] Warning: gulp version mismatch:
[15:10:32] Global gulp is 3.9.1
[15:10:32] Local gulp is 3.8.11
[15:10:33] Using gulpfile ~\Documents\Projects\ionic\gulpfile.js
[15:10:33] Starting 'tests'...
[15:10:34] Finished 'tests' after 1.31 s
[15:10:34] Starting 'karma'...
WARN [watcher]: Pattern "C:/Users/Zyn/Documents/Projects/ionic/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js" does not match any file.
WARN [web-server]: 404: /base/dist/src
WARN [web-server]: 404: /base/dist/src/util/mock-providers
WARN [web-server]: 404: /base/dist/src/components/modal/modal-component
WARN [web-server]: 404: /base/dist/src/components/nav/nav-controller-base
WARN [web-server]: 404: /base/dist/src/components/virtual-scroll/virtual-util
WARN [web-server]: 404: /base/dist/src/gestures/ionic-gesture-config
WARN [web-server]: 404: /base/dist/src/gestures/recognizers
WARN [web-server]: 404: /base/dist/src/gestures/simulator
WARN [web-server]: 404: /base/dist/src/util/datetime-util
WARN [web-server]: 404: /base/dist/src/util
Chrome 51.0.2704 (Windows 10 0.0.0) ERROR: 'Error: XHR error (404 Not Found) loading http://localhost:9876/base/dist/src
    at o (http://localhost:9876/base/node_modules/systemjs/dist/system.js?ea2d7cecbce9a5de1b6777fa755578976b7f3e2b:4:12694)
    at XMLHttpRequest.I.s.onreadystatechange (http://localhost:9876/base/node_modules/systemjs/dist/system.js?ea2d7cecbce9a5de1b6777fa755578976b7f3e2b:4:13219)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?d334dae1da3b416119643b05435f160ee3725dcf:789:30)
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?d334dae1da3b416119643b05435f160ee3725dcf:365:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?d334dae1da3b416119643b05435f160ee3725dcf:265:48)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?d334dae1da3b416119643b05435f160ee3725dcf:432:34)'

Chrome 51.0.2704 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0 secs / 0 secs)
[15:10:38] 'karma' errored after 4.41 s
[15:10:38] Error: Karma exited with an error
  at C:\Users\Zyn\Documents\Projects\ionic\gulpfile.js:730:19
  at removeAllListeners (C:\Users\Zyn\Documents\Projects\ionic\node_modules\karma\lib\server.js:215:7)
  at Server.<anonymous> (C:\Users\Zyn\Documents\Projects\ionic\node_modules\karma\lib\server.js:226:9)
  at Server.g (events.js:273:16)
  at emitNone (events.js:85:20)
  at Server.emit (events.js:179:7)
  at emitCloseNT (net.js:1523:8)
  at nextTickCallbackWith1Arg (node.js:463:9)
  at process._tickCallback (node.js:385:17)

```

**Which Ionic Version?** 2

**Comment by jgw96** [comment]
Hello @fknop glad to hear that your working on a PR 😃 . Would you try running `gulp package build --typecheck` and then running `gulp karma` again? Thanks!

**Comment by fknop** [comment]
@jgw96 Thanks for you reply. I tried `gulp package build --typecheck`, no errors on this one. But the `gulp karma` exits with the same error than before.

It looks like karma is looking for the `src` folder in `dist`. And I don't see it.

**Comment by jgw96** [comment]
Hmm thanks for the info. Could you try running `gulp watch.e2e` instead please?

**Comment by fknop** [comment]
Not sure I understand what to do next after I open the `http://localhost:8000/dist/e2e`.

**Comment by fknop** [comment]
The tests that are compiled in dist are requiring: `var util = require('../../../src/util');` for example which is targeting `dist/src/util` but there is only a `dist/util` folder.

**Comment by jgw96** [comment]
Hello @fknop ! So actually our testing setup is going through big changes right now. Because of this we are going to ask that you hold off for just a little while until you submit your pull request. I will keep this issue open for now until that refactor is done. Thanks for using Ionic and sorry for any hassle this causes! We really appreciate the work on your pull request and i cant wait for when you submit it!

**Comment by fknop** [comment]
No problem. Thanks for the information!

**Comment by trkoch** [comment]
I'd like to run tests to explore Ionic and learn how to write my own tests for an application I'm developing. Is there an older version I can run for the time being?

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic! You can now run tests in the ionic source by running `npm test`.
