### ISSUE TITLE
Ionic Beta 11 and Angular Forms - Cannot find control ''

### ISSUE THREAD

**Issue by donaldhook** [driftyco/ionic#7785]
I needed to rebuild my project and am having an issue displaying a login form.  When I run my app, I get an error in my login.html.  It looks as though there was an issue with the migration to angular forms.  I tried rebuilding ionic and copying the ion-angular module to my project node_modules, but that did not work,

Any insight would be appreciated. 

**Here is the exception:**
zone.js:461 Unhandled Promise rejection: EXCEPTION: Error in build/pages/login/login.html:19:38
ORIGINAL EXCEPTION: Cannot find control ''

**Here is the Form**
```
<form [formGroup]="loginForm" (ngSubmit)="login(loginForm.value)">
    <ion-item [class.error]="!username.valid && username.touched">
      <ion-label>Username:</ion-label>
      <ion-input type="text" value="" [formControlName]="username"></ion-input>
    </ion-item>
    <div *ngIf="username.hasError('required') && username.touched"
         class="error-box">* Username is required!</div>
    <div *ngIf="username.hasError('minlength') && username.touched"
         class="error-box">* Minimum username length is 8!</div>
    <div *ngIf="username.hasError('checkFirstCharacterValidator') && username.touched"
         class="error-box">* Username cant't start with number!</div>
    <div *ngIf="!username.valid && username.touched"
         class="error-box">* Invalid username, please reenter.</div>
    <ion-item [class.error]="!password.valid && password.touched">
      <ion-label>Password:</ion-label>
      <ion-input type="password" value="" [formControlName]="password" ></ion-input>
    </ion-item>
    <div *ngIf="password.hasError('required') && password.touched"
         class="error-box">* Password is required</div>
    <div *ngIf="password.hasError('minlength') && password.touched"
         class="error-box">* Minimum password length is 8!</div>
    <div *ngIf="password.hasError('checkFirstCharacterValidator') && password.touched"
         class="error-box">* Password cant't start with number!</div>
    <br/><br/>
    <button clear text-center><span dark>Forgot your password?</span></button>
    <br/><br/>
    <button type="submit" class="custom-button" [disabled]="!loginForm.valid" block>Submit</button>
  </form>
```

Here is the typescript
```
import {Page, Events, NavController, Platform} from 'ionic-angular';
import {Control, ControlGroup} from '@angular/common';
import {REACTIVE_FORM_DIRECTIVES, FORM_DIRECTIVES, FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';

......

@Page({
  templateUrl: 'build/pages/login/login.html',
  directives: [REACTIVE_FORM_DIRECTIVES, FORM_DIRECTIVES]
})
export class LoginPage {

  loginForm: FormGroup;
  username: FormControl;
  password: FormControl;
  logo:string;

  constructor(public nav: NavController, public events:Events, public formBuilder:FormBuilder, public    public userService:UserService, public public userCustomerService:UserCustomerService,  public global:Global) {

    this.loginForm = formBuilder.group({
      'username': ['', Validators.compose([Validators.required, Validators.minLength(5)])],
      'password': ['', Validators.compose([Validators.required, Validators.minLength(5)])]
    })

    this.username = this.loginForm['username'];
    this.password = this.loginForm['password'];

    this.logo = global.getLogo();
  }

  login(value:string): void {

    // Call the backend service to log the user in
    this.sessionService.login(this.loginForm.controls['username'].value, this.loginForm.controls['password'].value)
      .then(data => {

        // Get the objects from the response
        let error = data['error'];

        // If the error wad returned, exit the method
        if (error) {
          this.loginForm.controls['username'].setErrors({"valid": false});
          return;
        }

        this.events.publish('loggedIn');

        //this.nav.push(SelectCatalogPage,{userId:6});
        this.nav.setRoot(OrdersPage);

      });

  }
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Did you follow our [update instructions](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) when updating your app? Thanks!

**Comment by donaldhook** [comment]
Sorry, I did not  I will review and give it a shot.  Thanks!

**Comment by jgw96** [comment]
@donaldhook Awesome! Let me know if it works for you after you go through that guide. Thanks!

**Comment by donaldhook** [comment]
I have started from a new sidemenu project and added my pages, models, providers, etc.   I modified the login html and login.ts based on the angular/forms reference in your doc...... still have the same issue... 

Here is the ts file

```
import {Page, Events, NavController, Platform} from 'ionic-angular';
import {Control, ControlGroup} from '@angular/common';
import {REACTIVE_FORM_DIRECTIVES, FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
....

@Page({
  templateUrl: 'build/pages/login/login.html',
  directives: [REACTIVE_FORM_DIRECTIVES]
})
export class LoginPage {

  loginForm: FormGroup;
  username: FormControl;
  password: FormControl;
  logo:string;

  constructor(public nav: NavController, public events:Events, public formBuilder:FormBuilder, public sessionService:SessionService, 
public global:Global) {

    this.loginForm = new FormGroup({
        username: new FormControl('',[
          Validators.required,
          Validators.minLength(3)
        ]),
        password: new FormControl('',[
          Validators.required,
          Validators.minLength(3)
        ])
    });


    this.logo = global.getLogo();
  }

  login(value:string): void {

    // Call the backend service to log the user in
    this.sessionService.login(this.loginForm.controls['username'].value, this.loginForm.controls['password'].value)
      .then(data => {

        // Get the objects from the response
        let error = data['error'];

        // If the error wad returned, exit the method
        if (error) {
          this.loginForm.controls['username'].setErrors({"valid": false});
          return;
        }

        this.events.publish('loggedIn');

        //this.nav.push(SelectCatalogPage,{userId:6});
        this.nav.setRoot(OrdersPage);

      });

    // Prevent the default action
    //event.preventDefault();

  }
}
```
Here is the HTML

```
<ion-navbar *navbar>
  <ion-title>Login</ion-title>
</ion-navbar>

<ion-content class="login" padding>
  <div class="row">
    <div class="login-image">
      <img src="{{logo}}">
    </div>
  </div>

  <form [formGroup]="loginForm" (ngSubmit)="login(loginForm.value)">
    <ion-item [class.error]="!username.valid && username.touched">
      <ion-label>Username:</ion-label>
      <ion-input type="text" value="" [formControlName]="username"></ion-input>
    </ion-item>
    <div *ngIf="username.hasError('required') && username.touched"
         class="error-box">* Username is required!</div>
    <div *ngIf="username.hasError('minlength') && username.touched"
         class="error-box">* Minimum username length is 8!</div>
    <div *ngIf="username.hasError('checkFirstCharacterValidator') && username.touched"
         class="error-box">* Username cant't start with number!</div>
    <div *ngIf="!username.valid && username.touched"
         class="error-box">* Invalid username, please reenter.</div>
    <ion-item [class.error]="!password.valid && password.touched">
      <ion-label>Password:</ion-label>
      <ion-input type="password" value="" [formControlName]="password" ></ion-input>
    </ion-item>
    <div *ngIf="password.hasError('required') && password.touched"
         class="error-box">* Password is required</div>
    <div *ngIf="password.hasError('minlength') && password.touched"
         class="error-box">* Minimum password length is 8!</div>
    <div *ngIf="password.hasError('checkFirstCharacterValidator') && password.touched"
         class="error-box">* Password cant't start with number!</div>
    <br/><br/>
    <button clear text-center><span dark>Forgot your password?</span></button>
    <br/><br/>
    <button type="submit" class="custom-button" [disabled]="!loginForm.valid" block>Submit</button>
  </form>
</ion-content>
```

**Comment by donaldhook** [comment]
@jgw96 I reviewed the angular forms doc that was referenced, made a few minor tweaks and still no luck.  In making these tweaks, I have an error referencing the assignment of a validator.... so have some code from previous version that is not quite correct.

I created a new sidemenu project and moved my pages, services, models to the new project.   The login form is the first page that is presented in the app.   


**Here is the exception:**

```
browser_adapter.js:84EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in build/pages/login/login.html:17:8
ORIGINAL EXCEPTION: TypeError: Cannot create property 'validator' on string 'loginForm'
ORIGINAL STACKTRACE:
TypeError: Cannot create property 'validator' on string 'loginForm'
    at FormGroupDirective.ngOnChanges (http://localhost:8100/build/js/app.bundle.js:40703:33)
    at DebugAppView._View_LoginPage0.detectChangesInternal (LoginPage.template.js:486:59)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33872:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33977:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:8100/build/js/app.bundle.js:33898:19)
    at DebugAppView._View_LoginPage_Host0.detectChangesInternal (LoginPage.template.js:45:8)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33872:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33977:44)
    at ViewRef_.detectChanges (http://localhost:8100/build/js/app.bundle.js:34329:65)
    at ViewController.fireWillEnter (http://localhost:8100/build/js/app.bundle.js:63945:22)
ERROR CONTEXT:
```

Here is the form:

```
  <form formGroup="loginForm" (ngSubmit)="login(loginForm.value)">
    <ion-item [class.error]="!username.valid && username.touched">
      <ion-label>Username:</ion-label>
      <ion-input type="text" value="" [formControlName]="username"></ion-input>
    </ion-item>
    <div *ngIf="username.hasError('required') && username.touched"
         class="error-box">* Username is required!</div>
    <div *ngIf="username.hasError('minlength') && username.touched"
         class="error-box">* Minimum username length is 8!</div>
    <div *ngIf="username.hasError('checkFirstCharacterValidator') && username.touched"
         class="error-box">* Username cant't start with number!</div>
    <div *ngIf="!username.valid && username.touched"
         class="error-box">* Invalid username, please reenter.</div>
    <ion-item [class.error]="!password.valid && password.touched">
      <ion-label>Password:</ion-label>
      <ion-input type="password" value="" [formControlName]="password" ></ion-input>
    </ion-item>
    <div *ngIf="password.hasError('required') && password.touched"
         class="error-box">* Password is required</div>
    <div *ngIf="password.hasError('minlength') && password.touched"
         class="error-box">* Minimum password length is 8!</div>
    <div *ngIf="password.hasError('checkFirstCharacterValidator') && password.touched"
         class="error-box">* Password cant't start with number!</div>
    <br/><br/>
    <button clear text-center><span dark>Forgot your password?</span></button>
    <br/><br/>
    <button type="submit" class="custom-button" [disabled]="!loginForm.valid" block>Submit</button>
  </form>
```

Here is the typescript:

```
import {Page, Events, NavController, Platform} from 'ionic-angular';
import {Control, ControlGroup} from '@angular/common';
import {REACTIVE_FORM_DIRECTIVES, FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
import {HomePage} from '../../pages/home/home';
......

@Page({
  templateUrl: 'build/pages/login/login.html',
  directives: [REACTIVE_FORM_DIRECTIVES]
})
export class LoginPage {

  loginForm: FormGroup;
  username: FormControl;
  password: FormControl;
  logo:string;

  constructor(public nav: NavController, public events:Events, public formBuilder:FormBuilder, public sessionService:SessionService, public userService:UserService,  public global:Global) {

    this.loginForm = new FormGroup({
        username: new FormControl('',[
          Validators.required,
          Validators.minLength(3)
        ]),
        password: new FormControl('',[
          Validators.required,
          Validators.minLength(3)
        ])
    });

    this.logo = global.getLogo();
  }

  login(value:string): void {

    // Call the backend service to log the user in
    this.sessionService.login(this.loginForm.controls['username'].value, this.loginForm.controls['password'].value)
      .then(data => {

        // Get the objects from the response
        let error = data['error'];

        // If the error wad returned, exit the method
        if (error) {
          this.loginForm.controls['username'].setErrors({"valid": false});
          return;
        }

        this.events.publish('loggedIn');

        //this.nav.push(SelectCatalogPage,{userId:6});
        this.nav.setRoot(OrdersPage);

      });

    // Prevent the default action
    //event.preventDefault();

  }
}
```

**Comment by nikhilknoldus** [comment]
@jgw96 Hey Justin Can you have a look here please.

**Comment by mhartington** [comment]
So this looks like it's using older forms syntax. Try this.

```typescript
import {Component} from '@angular/core';
import {FormBuilder, Validators} from '@angular/forms';
@Component({
  template: `
<ion-content>
  <form [formGroup]="loginForm">
    <ion-item>
      <ion-label>Username:</ion-label>
      <ion-input type="text" formControlName="username"></ion-input>
    </ion-item>

    <ion-item>
      <ion-label>Password:</ion-label>
      <ion-input type="password" formControlName="password"></ion-input>
    </ion-item>
    <button type="submit" class="custom-button" [disabled]="!loginForm.valid" block>Submit</button>
  </form>
  <div *ngIf="username.hasError('required') && username.touched" class="error-box">* Username is required!</div>
  <div *ngIf="username.hasError('minlength') && username.touched" class="error-box">* Minimum username length is 8!</div>
  <div *ngIf="username.hasError('checkFirstCharacterValidator') && username.touched" class="error-box">* Username cant't start with number!</div>
  <div *ngIf="!username.valid && username.touched" class="error-box">* Invalid username, please reenter.</div>


  <div *ngIf="password.hasError('required') && password.touched"
         class="error-box">* Password is required</div>
    <div *ngIf="password.hasError('minlength') && password.touched"
         class="error-box">* Minimum password length is 8!</div>
    <div *ngIf="password.hasError('checkFirstCharacterValidator') && password.touched"
         class="error-box">* Password cant't start with number!</div>
</ion-content>
  `
})
export class HomePage {

  loginForm;
  username = this.formBuilder.control('', [Validators.required, Validators.minLength(3)]);
  password = this.formBuilder.control('', [Validators.required, Validators.minLength(3)]);
  constructor(public formBuilder: FormBuilder) {
    this.loginForm = this.formBuilder.group({
      username: this.username,
      password: this.password
    });

  }

}
```

**Comment by donaldhook** [comment]
Thanks, made the mods and added the ngSubmit on the form and looks like it works.  Thank you!
