### ISSUE TITLE
AlertController not working if alert or toast is in background

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#7917]
#### Short description of the problem:
If there is some Alert or Toast in background and I open a new alert, new alert doesn't respond and you have to kill the app to get control back.

#### How I found this problem and Use case
In my app, I have push notifications enabled. So if app is in foreground and push notification arrives, it shows an alert to view or ignore notification. That's how I get alerts asynchronously and if there is some alert or toast in background, you can't click on alert. Please see gif below

#### What behavior are you expecting?
Background stuff should not affect whatever is in foreground. 

**Steps to reproduce:**
1. Open an alert with some alert or toast in background
Please refer to this commit https://github.com/aggarwalankush/ionic-inappbrowser-issue/commit/afd92b1295d672fb2018d54227d01f9551f825dd

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
- With alert in background, no error in console
- With toast in background, following error in console

```

browser_adapter.js:93 EXCEPTION: Error in ./AppRoot class AppRoot_Host - inline template:0:0
browser_adapter.js:84 EXCEPTION: Error in ./AppRoot class AppRoot_Host - inline template:0:0BrowserDomAdapter.logError @ browser_adapter.js:84BrowserDomAdapter.logGroup @ browser_adapter.js:94ExceptionHandler.call @ exception_handler.js:65(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:74(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:77(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 Error: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
    at ExpressionChangedAfterItHasBeenCheckedException.BaseException [as constructor] (http://localhost:8100/build/js/app.bundle.js:2760:23)
    at new ExpressionChangedAfterItHasBeenCheckedException (http://localhost:8100/build/js/app.bundle.js:32113:16)
    at checkBinding (http://localhost:8100/build/js/app.bundle.js:33266:19)
    at DebugAppView._View_AppRoot_Host0.detectChangesInternal (AppRoot.template.js:33:7)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:32642:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:32747:44)
    at ViewRef_.checkNoChanges (http://localhost:8100/build/js/app.bundle.js:33100:66)
    at http://localhost:8100/build/js/app.bundle.js:26587:88
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:8100/build/js/app.bundle.js:26587:42)BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:78(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:81(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 DebugContext {_view: _View_AppRoot_Host0, _nodeIndex: 0, _tplRow: 0, _tplCol: 0}BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:82(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:463 ViewWrappedException {_wrapperMessage: "Error in ./AppRoot class AppRoot_Host - inline template:0:0", _originalException: ExpressionChangedAfterItHasBeenCheckedException, _originalStack: "Error: Expression has changed after it was checked…//localhost:8100/build/js/app.bundle.js:26587:42)", _context: DebugContext, _wrapperStack: "Error: Error in ./AppRoot class AppRoot_Host - inl…e (http://localhost:8100/build/js/zone.js:323:29)"}consoleError @ zone.js:463drainMicroTaskQueue @ zone.js:477ZoneTask.invoke @ zone.js:426
```

**Which Ionic Version?** 
Ionic 2 beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

<img src="https://cloud.githubusercontent.com/assets/8744282/18111397/3765ef02-6ed4-11e6-85a5-7ac3504d258e.gif" width="250"/>

<img src="https://cloud.githubusercontent.com/assets/8744282/18111459/9baf76d6-6ed4-11e6-9c7b-d2027b361e55.gif" width="250"/>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This issue has already been already been solved and will be in the beta.12 release. Thanks for using Ionic!

**Comment by aggarwalankush** [comment]
@jgw96 any workaround before beta 12?

**Comment by jgw96** [comment]
The current workaround is to make sure that only one overlay component is displayed at a time. So you just have to dismiss each overlay component before presenting another one. Thanks!
