### ISSUE TITLE
ionic $ Caught exception

### ISSUE THREAD

**Issue by amrayoub** [driftyco/ionic#7962]
Hello, after I run npm install and try to ionic serve the app.
it shows me this messege 
ionic $ Caught exception:
Error: watch /home/amr/Desktop/ionic2 parctice/truckjee-truck-owner-master/node_modules/rxjs/add/operator/concatMapTo.js ENOSPC
at exports._errnoException (util.js:856:11)
at FSWatcher.start (fs.js:1313:19)
at Object.fs.watch (fs.js:1341:11)
at createFsWatchInstance (/home/amr/Desktop/ionic2 parctice/truckjee-truck-owner-master/node_modules/chokidar/lib/nodefs-handler.js:37:15)
at setFsWatchListener (/home/amr/Desktop/ionic2 parctice/truckjee-truck-owner-master/node_modules/chokidar/lib/nodefs-handler.js:80:15)
at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/amr/Desktop/ionic2 parctice/truckjee-truck-owner-master/node_modules/chokidar/lib/nodefs-handler.js:228:14)
at FSWatcher.NodeFsHandler._handleFile (/home/amr/Desktop/ionic2 parctice/truckjee-truck-owner-master/node_modules/chokidar/lib/nodefs-handler.js:255:21)
at FSWatcher. (/home/amr/Desktop/ionic2 parctice/truckjee-truck-owner-master/node_modules/chokidar/lib/nodefs-handler.js:473:21)
at FSReqWrap.oncomplete (fs.js:82:15)

CLI

cordova 6.3.1
ionic 2.0.0-beta.37
Node v5.4.1
npm 3.3.12

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1335

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because this issue is more related to the Ionic cli than the Ionic framework I have moved this issue over to the cli repo. Thanks for using Ionic!
