### ISSUE TITLE
ionic2 -bug(virtualscroll) - Virtual scroll does not work in modals

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#8142]
#### Short description of the problem:

When presenting a modal with a virtual scroll list, I receive the following error.

<pre><code>
`VM658 zone.min.js:1 Unhandled Promise rejection: EXCEPTION: Error in ./SelectionModal class SelectionModal - inline template:16:16
ORIGINAL EXCEPTION: No provider for Content!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/facade/exceptions.js:27:23)
    at NoProviderError.AbstractProviderError [as constructor] (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/di/reflective_exceptions.js:43:16)
    at new NoProviderError (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/di/reflective_exceptions.js:80:16)
    at ReflectiveInjector_._throwOrNull (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/di/reflective_injector.js:786:19)
    at ReflectiveInjector_._getByKeyDefault (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/di/reflective_injector.js:814:25)
    at ReflectiveInjector_._getByKey (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/di/reflective_injector.js:777:25)
    at ReflectiveInjector_.get (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/di/reflective_injector.js:586:21)
    at ElementInjector.get (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/linker/element_injector.js:30:48)
    at ElementInjector.get (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/linker/element_injector.js:30:48)
    at ReflectiveInjector_._getByKeyDefault (https://npmcdn.com/@angular/core@2.0.0-rc.4/src/di/reflective_injector.js:811:24)
ERROR CONTEXT:
[object Object] ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedException {_wrapperMessage: "Error in ./SelectionModal class SelectionModal - inline template:16:16", _originalException: NoProviderError, _originalStack: "Error: DI Exception↵    at NoProviderError.BaseExc…@2.0.0-rc.4/src/di/reflective_injector.js:811:24)", _context: DebugContext, _wrapperStack: "Error: Error in ./SelectionModal class SelectionMo…ar@2.0.0-beta.10/bundles/ionic.system.js:16259:64"} undefined`
</code></pre>

**Which Ionic Version?**
2.0@beta.10 and 11
#### Plunker that shows an example of your issue

http://plnkr.co/edit/kRTqAU33ZBgflrI5bGJu?p=preview

**Comment by malvarezhcr** [comment]
Not sure if this is the best solution but wrapping your modal component into a ion-content tag it will show the modal with the virtual scroll

http://plnkr.co/edit/bTWB1l74SEKJ3qHAjcOH?p=preview

**Comment by zakton5** [comment]
Well that removes the error and it loads. However, there are some serious display issues with virtual scroll if there are more items in the list. Hopefully it is fixed in the next beta

**Comment by zakton5** [comment]
Alright, so at this point I have it loading in a modal. But when I scroll down the list the other items do not load. It seems like the scroll event is not getting fired

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since the original issue was solved by adding `ion-content`, which should be there, I am going to close this issue for now. Please open another issue for any further issues. Thanks!
