### ISSUE TITLE
[V2 rc0] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic#8280]
#### RangeError: Maximum call stack size exceeded

I cant figure out how to reporduce it reliably but i am getting below error. The app still compiles however. 

Did someone see this before?

```
[00:52:28]  RangeError: Maximum call stack size exceeded
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:153:20)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/barbarian/TS/greenkey/greenkey-tabs-rc0/node_modules/rollup/dist/rollup.js:165:18)

```

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 8.0 Build version 8A218a 

```

**Comment by baffleinc** [comment]
I got the same - with a stack trace: 

```[15:12:46]  bundle dev update started ...
[15:12:46]  RangeError: Maximum call stack size exceeded
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:153:20)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:165:18)

[15:12:46]  templateUpdate finished in 94 ms
<--- Last few GCs --->
 1700553 ms: Mark-sweep 1279.1 (1440.3) -> 1276.2 (1440.3) MB, 1112.5 / 0.0 ms [allocation failure] [GC in old space requested].
 1701766 ms: Mark-sweep 1276.2 (1440.3) -> 1276.3 (1440.3) MB, 1213.1 / 0.0 ms [allocation failure] [GC in old space requested].
 1703048 ms: Mark-sweep 1276.3 (1440.3) -> 1284.2 (1424.3) MB, 1281.5 / 0.0 ms [last resort gc].
 1704385 ms: Mark-sweep 1284.2 (1424.3) -> 1292.2 (1424.3) MB, 1336.5 / 0.0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x2424511cfb51 <JS Object>
    1: /* anonymous */(aka /* anonymous */) [/Users/Harley/Apps/doorlist-app/node_modules/rollup/dist/rollup.js:~8332] [pc=0x22b8cdb8ca03] (this=0x242451104381 <undefined>,line=0x2b03e4d14c81 <JS Array[21]>)
    2: arguments adaptor frame: 3->1
    3: map [native array.js:~994] [pc=0x22b8cdbf9f92] (this=0x6de1c995d9 <JS Array[116815]>,bq=0x142b93ae7769 <JS Function (SharedFunctionInfo 0x3c56268...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1:
node::Abort() [/Users/Harley/.nvm/versions/node/v6.7.0/bin/node]
 2:
node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/Harley/.nvm/versions/node/v6.7.0/bin/node]
 3:
v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/Harley/.nvm/versions/node/v6.7.0/bin/node]
 4:
v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/Harley/.nvm/versions/node/v6.7.0/bin/node]
 5:
v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/Harley/.nvm/versions/node/v6.7.0/bin/node]
 6:
0x22b8cb2079a7```

**Comment by Manduro** [comment]
I'm seeing this regularly. Sometimes this probably related error:
```
 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[0] 
[0] <--- Last few GCs --->
[0]   666257 ms: Mark-sweep 1393.5 (1457.6) -> 1397.1 (1457.6) MB, 3054.8 / 0 ms [allocation failure] [GC in old space requested].
[0]   668874 ms: Mark-sweep 1397.1 (1457.6) -> 1397.1 (1457.6) MB, 2617.3 / 0 ms [allocation failure] [GC in old space requested].
[0]   671357 ms: Mark-sweep 1397.1 (1457.6) -> 1391.0 (1457.6) MB, 2482.4 / 0 ms [last resort gc].
[0]   673634 ms: Mark-sweep 1391.0 (1457.6) -> 1393.3 (1457.6) MB, 2277.6 / 0 ms [last resort gc].
[0] <--- JS stacktrace --->
[0] ==== JS stack trace =========================================
[0] Security context: 0x326c657b4629 <JS Object>
[0]     1: decode(aka decode) [PROJECT_FOLDER/node_modules/rollup/dist/rollup.js:~304] [pc=0x30adb0dbc5cb] (this=0x326c657041b9 <undefined>,mappings=0x3ac2e6b04101 <Very long string[3621421]>)
[0]     2: render [PROJECT_FOLDER/node_modules/rollup/dist/rollup.js:8938] [pc=0x30adb0d0838c] (this=0xbcef7eb721 <a Bundle with map 0xea1ac4270f9>,options=0xbcef7ebee1 <an...
```

**Comment by Aristona** [comment]
+1

**Comment by arv10singh** [comment]
me too .

**Comment by okonon** [comment]
Yeah, in addition to Maximum stack error getting this too:
```
[08:36:53]  bundle dev update started ...
<--- Last few GCs --->
 3466571 ms: Mark-sweep 1274.0 (1435.0) -> 1272.4 (1435.0) MB, 1445.4 / 0 ms [allocation failure] [GC in old space requested].
 3468039 ms: Mark-sweep 1272.4 (1435.0) -> 1272.4 (1435.0) MB, 1467.7 / 0 ms [allocation failure] [GC in old space requested].
 3469589 ms: Mark-sweep 1272.4 (1435.0) -> 1272.4 (1435.0) MB, 1549.6 / 0 ms [last resort gc].
 3471091 ms: Mark-sweep 1272.4 (1435.0) -> 1272.4 (1435.0) MB, 1502.6 / 0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x361bce9c9e31 <JS Object>
    1: Join(aka Join) [native array.js:179] [pc=0x4b0bbe181f5] (this=0x361bce904189 <undefined>,w=0x1905f65f2399 <JS Array[94699]>,x=94699,N=0x89790b28e99 <String[1]: ;>,M=0x361bce9b4ab1 <JS Function ConvertToString (SharedFunctionInfo 0x361bce94ef79)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:~343] [pc=0x4b0bce12b6c] (this=0x361bce904189 <undefined>,N=0x89790b28e99 <String[1]...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/Cellar/node/6.3.1/bin/node]
 2: 
node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>)
 [/usr/local/Cellar/node/6.3.1/bin/node]
 3: 
v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/Cellar/node/6.3.1/bin/node]
 4: 
v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/Cellar/node/6.3.1/bin/node]
 5: 
v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/Cellar/node/6.3.1/bin/node]
 6: 
v8::internal::Runtime_StringBuilderJoin(int, v8::internal::Object**, v8::internal::Isolate*)
 [/usr/local/Cellar/node/6.3.1/bin/node]


 7: 
0x4b0bb00961b

```

**Comment by okonon** [comment]
Created https://github.com/driftyco/ionic-cli/issues/1433 issue for `ionic-cli` i think that is more appropriate place for it.

**Comment by hoodaajay99** [comment]
[19:06:24]  RangeError: Maximum call stack size exceeded
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:163:2)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/home/ajay/a/ionic2RC-2.1.0/cashbox/node_modules/rollup/dist/rollup.js:165:18)

[19:06:24]  sass started ...

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic. We are currently aware of this issue an are actively looking into it. I am going to be closing this issue for now as there is already an issue open about it in the cli repo that is linked too in the above comment. Thanks!
