### ISSUE TITLE
[V2 RC.0] Geolocation is not defined

### ISSUE THREAD

**Issue by bm-software** [driftyco/ionic#8305]
I've just ugraded my project to the new Ionic version (RC.0) and if I try to run it either with _serve_ or _run android_ command my app doesn't start throwing this exception:

```
EXCEPTION: Uncaught (in promise): ReferenceError: Geolocation is not defined
3     208806   error    ORIGINAL STACKTRACE:
4     208807   error    Error: Uncaught (in promise): ReferenceError: Geolocation is not defined
    at s (http://192.168.0.123:8100/build/polyfills.js:3:8546)
    at http://192.168.0.123:8100/build/polyfills.js:3:8918
    at t.invokeTask (http://192.168.0.123:8100/build/polyfills.js:3:14029)
    at Object.inner.inner.fork.onInvokeTask (http://192.168.0.123:8100/build/main.js:7:28771)
    at t.invokeTask (http://192.168.0.123:8100/build/polyfills.js:3:13965)
    at e.runTask (http://192.168.0.123:8100/build/polyfills.js:3:11389)
    at i (http://192.168.0.123:8100/build/polyfills.js:3:8006)
    at invoke (http://192.168.0.123:8100/build/polyfills.js:3:15182)
5     208814   error    Unhandled Promise rejection:, Geolocation is not defined, ; Zone:, angular, ; Task:, Promise.then, ; Value:, [object Object], ReferenceError: Geolocation is not defined
    at http://192.168.0.123:8100/build/main.js:35:1332
    at t.invoke (http://192.168.0.123:8100/build/polyfills.js:3:13400)
    at Object.inner.inner.fork.onInvoke (http://192.168.0.123:8100/build/main.js:7:28871)
    at t.invoke (http://192.168.0.123:8100/build/polyfills.js:3:13351)
    at e.run (http://192.168.0.123:8100/build/polyfills.js:3:10787)
    at http://192.168.0.123:8100/build/polyfills.js:3:8889
    at t.invokeTask (http://192.168.0.123:8100/build/polyfills.js:3:14029)
    at Object.inner.inner.fork.onInvokeTask (http://192.168.0.123:8100/build/main.js:7:28771)
    at t.invokeTask (http://192.168.0.123:8100/build/polyfills.js:3:13965)
    at e.runTask (http://192.168.0.123:8100/build/polyfills.js:3:11389)
```

I've already added the Geolocation plugin following [this](http://ionicframework.com/docs/v2/native/geolocation/) and in the previous version (beta.11) all works fine.

Any solution?

**Comment by mhartington** [comment]
Hi there. We need more information. Please provide the steps needed in order to reproduce this error.

**Comment by bm-software** [comment]
I think this issue can be closed. I've unistalled and reinstalled the plugin and now everything works fine.

**Comment by mhartington** [comment]
👍  Glad to hear.
