### ISSUE TITLE
updating ionic breaks my project

### ISSUE THREAD

**Issue by fablife** [driftyco/ionic#8308]
This issue report has been published also as a question on stackoverflow:
http://stackoverflow.com/questions/39774318/ionic-npm-node-updating-ionic-breaks-my-project

I know it's probably easy to solve, but I am a bit nervous as I am close to delivery (aaaaaaargh, NEVER run an update so close to delivery....)

Always when issuing` ionic serve`, I was getting a message that there was a new version of ionic ready to download.

Yesterday I gave in, and hit

`npm install -g ionic`
This went fine. But now this morning, when issuing ionic serve again, I get

```
$ ionic serve
module.js:340
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    ...
```
I've found issue reports on the web like this one: https://github.com/driftyco/ionic-cli/issues/574

but I dare to say it does not apply to my case. I am using nvm on linux, and which nvm reports

`/home/me/.nvm/versions/node/v5.1.0/bin/npm`
which should be the same as yesterday.

Do I maybe need to run npm install in my project directory again? node_modules is there, as is for example the colors package.

Thanks for any advice.

**Comment by fablife** [comment]
I ran `npm install -g ionic` again, and this is what I get:
```
...
- dezalgo@1.0.3 node_modules/ionic/node_modules/npm/node_modules/dezalgo
- realize-package-specifier@3.0.1 node_modules/ionic/node_modules/npm/node_modules/realize-package-specifier
- readdir-scoped-modules@1.0.2 node_modules/ionic/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules
- read-installed@4.0.3 node_modules/ionic/node_modules/npm/node_modules/read-installed
- async-some@1.0.2 node_modules/ionic/node_modules/npm/node_modules/async-some
- write-file-atomic@1.1.4 node_modules/ionic/node_modules/npm/node_modules/write-file-atomic
/home/me/.nvm/versions/node/v5.1.0/lib
└── (empty)

npm ERR! code 1
>$
```

This looks frightening. Why does the update stop like this? No error message...

**Comment by fablife** [comment]
"Solved" it by installing a new version of node with nvm, and then "npm install -g ionic" again...
