### ISSUE TITLE
Build: Process Out of memory after 3-4 rebuilds

### ISSUE THREAD

**Issue by pascalwhoop** [driftyco/ionic#8349]
#### Short description of the problem:

I can't really explain much. It pops up after 3,4 sometimes more build cycles on `ionic serve`. 
Ticket is created to see if some people have the same issue. I am using _.cloneDeep which sometimes also throws me errors (also below). Not sure if they belong together. 

#### What behavior are you expecting?

```
[10:47:48]  templateUpdate started ...
[10:47:48]  bundle dev update started ...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->
 3386911 ms: Scavenge 1402.6 (1457.9) -> 1402.6 (1457.9) MB, 7.8 / 0 ms (+ 2.4 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
 3388061 ms: Mark-sweep 1402.6 (1457.9) -> 1395.6 (1457.9) MB, 1150.9 / 0 ms (+ 3.6 ms in 2 steps since start of marking, biggest step 2.4 ms) [last resort gc].
 3389186 ms: Mark-sweep 1395.6 (1457.9) -> 1398.2 (1457.9) MB, 1124.1 / 0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0xf6a6d5e3ac1 <JS Object>
    2: /* anonymous */(aka /* anonymous */) [/Users/me/Documents/Code/work/projext/frontend_tablet/node_modules/rollup/dist/rollup.js:8342] [pc=0x27a63aad6d0a] (this=0xf6a6d504189 <undefined>,segment=0x2d98d1e37be1 <JS Array[4]>)
    3: arguments adaptor frame: 3->1
    4: InnerArrayForEach(aka InnerArrayForEach) [native array.js:~942] [pc=0x27a63aa39a65] (this=0xf6a6d504189 <undefin...
^Cpbr frontend_tablet $ ionic serve

Running 'serve:before' npm script before serve
> frontend_tablet@ watch /Users/me/Documents/Code/work/projext/frontend_tablet
> ionic-app-scripts watch
```

```
[10:45:57]  bundle dev update started ...
[10:45:57]  RangeError: Maximum call stack size exceeded
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:163:2)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)
    at deepClone (/Users/pbr/Documents/Code/OC/dai_produktionsforum/frontend_tablet/node_modules/rollup/dist/rollup.js:165:18)

[10:45:57]  sass started ...
...

```

#### Ionic Info

```
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by marcoturi** [comment]
I got the same problem yesterday on Windows 10.

**Comment by Manduro** [comment]
This has been reported here: https://github.com/driftyco/ionic-cli/issues/1433
Fix is on the way.

**Comment by pascalwhoop** [comment]
alright fair, better for the CLI so closing because of duplicate

**Comment by AnkitMaheshwariIn** [comment]
Is this error fixed for anyone ..?
Facing same problem here : https://stackoverflow.com/questions/44897670/error-in-ionic-cordova-build-android-prod
