### ISSUE TITLE
`gulp e2e.watch` and `gulp watch.demos` commands are not working as said in `CONTRIBUTING.md` doc

### ISSUE THREAD

**Issue by msaelices** [driftyco/ionic#8411]
#### Short description of the problem:

The `e2e.watch` and `gulp watch.demos` commands are not working in RC0.

Also the `e2e.watch` command signature is not well documented (needs a `-f componentname` argument).
#### What behavior are you expecting?

To be executed successfully.

**Steps to reproduce:**
1. Clone the ionic repo.
2. Run `npm install`
3. Run `gulp e2e.watch -f componentname` (i.e. `gulp e2e.watch -f checkbox`)
4. Run `gulp watch.demos` command.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

This is an example shell session:

```
$ gulp watch.demos
[00:40:09] Using gulpfile ~/src/ionic-msaelices/gulpfile.js
[00:40:09] Task 'watch.demos' is not in your gulpfile
[00:40:09] Please check the documentation for proper gulpfile formatting

$ gulp e2e.watch -f checkbox
[00:35:51] Using gulpfile ~/src/ionic-msaelices/gulpfile.js
[00:35:51] Starting 'e2e.copyExternalDependencies'...
[00:35:51] Finished 'e2e.copyExternalDependencies' after 6.51 ms
[00:35:51] Starting 'e2e.sass'...
[00:35:51] Starting 'e2e.fonts'...
[00:35:51] Finished 'e2e.fonts' after 27 ms
[00:35:52] Finished 'e2e.sass' after 1.81 s
[00:35:52] Starting 'e2e.watch'...
[00:35:53] 'e2e.watch' errored after 169 ms
[00:35:53] Error: Cannot find module '../../e2e/webpack.config.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at e2eWatch (/home/msaelices/src/ionic-msaelices/scripts/gulp/tasks/e2e.ts:259:18)
    at Gulp.<anonymous> (/home/msaelices/src/ionic-msaelices/scripts/gulp/tasks/e2e.ts:245:5)
    at module.exports (/home/msaelices/src/ionic-msaelices/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/msaelices/src/ionic-msaelices/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/msaelices/src/ionic-msaelices/node_modules/orchestrator/index.js:214:10)
    at /home/msaelices/src/ionic-msaelices/node_modules/orchestrator/index.js:279:18
    at finish (/home/msaelices/src/ionic-msaelices/node_modules/orchestrator/lib/runTask.js:21:8)
    at /home/msaelices/src/ionic-msaelices/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/home/msaelices/src/ionic-msaelices/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/home/msaelices/src/ionic-msaelices/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
```

 **Which Ionic Version?** 1.x or 2.x

2.0-RC0

**Comment by manucorporat** [comment]
@msaelices  thanks! we are aware of this issue!

In the meantime, you can:
```
gulp e2e --folder component/test
```
and open the generated .html directly.

**Comment by brandyscarney** [comment]
`gulp e2e` and `gulp e2e.watch` will now work. I haven't updated the demo task yet. Updated documentation here: https://github.com/driftyco/ionic/blob/master/scripts/README.md#building--running-e2e-tests

**Comment by brandyscarney** [comment]
I updated the documentation and both the e2e and demo tasks should work fine now. Thanks!
