### ISSUE TITLE
 ngc error: Compilation failed - ionic build android

### ISSUE THREAD

**Issue by h2qutc** [driftyco/ionic#8479]
Hi, 
When I tried to "ionic build android", I got this error: 

[16:34:07]  ngc error: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 168:19 in the original .ts file), resolving symbol AppModule in c:/MCNEXT/Vinci/Vinci-RSC%20Mobile/.tmp/app/app.module.ts
    at simplifyInContext (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\static_reflector.js:469:23)
    at StaticReflector.simplify (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\static_reflector.js:472:22)
    at StaticReflector.annotations (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\static_reflector.js:61:36)
    at _loop_1 (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:53:54)
    at CodeGenerator.readFileMetadata (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:66:13)
    at c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:100:35)
    at codegen (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\tsc-wrapped\src\main.js:30:16)

[16:34:07]  ngc error: Compilation failed
[16:34:07]  NGC encountered an error

Can anyone help me pls?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by vardas-bill** [comment]
Some guidance as to how to track down this problem would be helpful. In my case my app worked fine with Beta 10 but when updating to RC0 I get this problem. Any suggestions where I should look?
