### ISSUE TITLE
Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config). metadata_resolve.js

### ISSUE THREAD

**Issue by dragonahao** [driftyco/ionic#8495]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### What behavior are you expecting?

**Steps to reproduce:**
ionic-app-scripts watch
7:09:23]  ionic-app-scripts 0.0.28
7:09:23]  watch started ...
7:09:23]  build dev started ...
7:09:23]  clean started ...
7:09:23]  clean finished in 76 ms
7:09:23]  copy started ...
7:09:23]  typescript compiler started ...
7:09:23]  lint started ...
7:09:23]  lint failed:  Unable to find "tslint" command: null

```
 lint failed:  Unable to find "tslint" command: null

then  browser occurred it 
metadata_resolver.js:499Uncaught Error: Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config).
metadata_resolve.js 

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by nkalinov** [comment]
Same problem here

**Comment by JRizzle88** [comment]
I replaced tslint with tsify version 0.16.0 and was able to get past my tslint error. I was getting 

```
tslint /Users/riley/Documents/ionv2-blank/node_modules/tslint/lib/configuration.js:184 throw new Error("Could not find custom rule directory: " + directory);
```

After uninstalling tslint and installing tsify. I ran into your second error which was solved by reinstalling all packages. Hope this helps.

**Comment by balasivagnanam** [comment]
Browser error:
I had this error due to DI before, some things which I don't have to inject in providers, which I had before, after removing all of them mine is working fine now. I just have only the providers I wrote inside removed other things like http......etc which we can directly inject in respective classes.

Make sure your declartions array, providers array and imports array are cleaned up. they are the major culprits for this.

**Comment by Vishnuraj910** [comment]
Same here

[14:15:14]  lint failed:  Unable to find "tslint" command: null

[14:15:14]  Error: Unable to find "tslint" command: null
    at /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/dist/lint.js:38:20
    at runTsLint (/Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/dist/lint.js:35:12)
    at /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/dist/lint.js:22:13
    at FSReqWrap.oncomplete (fs.js:82:15)

[14:15:14]  copy finished in 186 ms
[14:15:14]  bundle dev failed:  Could not resolve '@angular/platform-browser-dynamic' from /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/src/app/main.dev.ts

[14:15:14]  Error: Could not resolve '@angular/platform-browser-dynamic' from /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/src/app/main.dev.ts
    at Error (native)
    at /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/browser-resolve/index.js:265:24
    at /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Visa Workshop/Visa Ionic Apps/ConnectedCarv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by Vishnuraj910** [comment]
Same here

[14:15:14]  lint failed:  Unable to find "tslint" command: null

[14:15:14]  Error: Unable to find "tslint" command: null
    at /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/dist/lint.js:38:20
    at runTsLint (/Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/dist/lint.js:35:12)
    at /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/dist/lint.js:22:13
    at FSReqWrap.oncomplete (fs.js:82:15)

[14:15:14]  copy finished in 186 ms
[14:15:14]  bundle dev failed:  Could not resolve '@angular/platform-browser-dynamic' from /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/src/app/main.dev.ts

[14:15:14]  Error: Could not resolve '@angular/platform-browser-dynamic' from /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/src/app/main.dev.ts
    at Error (native)
    at /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/browser-resolve/index.js:265:24
    at /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Vishnu Workshop/Vishnu Ionic Apps/Connectv2.0/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by balasivagnanam** [comment]
@Vishnuraj910 may be you should add your app.module.ts and ionic info

**Comment by Vishnuraj910** [comment]
@balasivagnanam Thank you. But I just created the app (ionic start --v2 Connectv2.0) and tried ionic serve. It should work with a default template right?

**Comment by Vishnuraj910** [comment]
ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by sgumz** [comment]
Same problem here

**Comment by ataraxus** [comment]
same issue here: 
`
npm -v
2.15.9
A@K ~/git/tabs
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.6.0


`

**Comment by jgw96** [comment]
Hello all! This issue is caused by the fact that you all are running npm 2 and not npm 3. With Ionic 2  RC0 we require npm 3. npm 3 will be the standard very soon when Node 6 becomes the LTS [this month](https://github.com/nodejs/LTS#lts_schedule). In the meantime if you do not want to install Node 6 you can simply run `npm install -g npm` to update your version of NPM to npm 3 but still keep node 4. Thanks!

**Comment by tuongaz** [comment]
I still have the same issue with npm 3. https://cl.ly/022H3s0h3l1K
