### ISSUE TITLE
bug: Blank screen after splashscreen on old Android

### ISSUE THREAD

**Issue by sjahan** [driftyco/ionic#8506]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, 

I'm using Ionic V1.3.1 and I'm currently encountering a problem.
The issue only appears on the older phones on Android. I reproduced the problem on a Galaxy S3 mini which runs Android 4.1.2, but also on a Samsung Galaxy Tab 3 on Android 4.4.2.

After the splash screen, the application is expected to start, but it stays on a white screen.
I extracted the logs from the devices: 

```
10-04 17:50:53.311 E/Web Console( 2863): Error: [$rootScope:inprog] $digest already in progress
10-04 17:50:53.311 E/Web Console( 2863): http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest
10-04 17:50:53.311 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13438:12
10-04 17:50:53.311 E/Web Console( 2863):     at beginPhase (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30753:15)
10-04 17:50:53.311 E/Web Console( 2863):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30493:11)
10-04 17:50:53.311 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:32332:36
10-04 17:50:53.311 E/Web Console( 2863):     at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19194:10)
10-04 17:50:53.311 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19470:7:431
10-04 17:50:53.321 E/Web Console( 2863): Error: [$rootScope:inprog] $digest already in progress
10-04 17:50:53.321 E/Web Console( 2863): http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest
10-04 17:50:53.321 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13438:12
10-04 17:50:53.321 E/Web Console( 2863):     at beginPhase (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30753:15)
10-04 17:50:53.321 E/Web Console( 2863):     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30191:9)
10-04 17:50:53.321 E/Web Console( 2863):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30503:24)
10-04 17:50:53.321 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:32332:36
10-04 17:50:53.321 E/Web Console( 2863):     at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19194:10)
10-04 17:50:53.321 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19470:7:431
10-04 17:50:53.321 E/Web Console( 2863): Uncaught Error: [$rootScope:inprog] $digest already in progress
10-04 17:50:53.321 E/Web Console( 2863): http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest:30506
10-04 17:50:53.411 D/dalvikvm(28919): WAIT_FOR_CONCURRENT_GC blocked 0ms
10-04 17:50:53.451 D/dalvikvm(28919): GC_EXPLICIT freed 244K, 12% free 9738K/11015K, paused 3ms+4ms, total 37ms
10-04 17:50:53.841 D/STATUSBAR-NetworkController( 2154): refreshSignalCluster: data=0 bt=false
10-04 17:50:54.312 E/Web Console( 2863): Error: [$rootScope:inprog] $digest already in progress
10-04 17:50:54.312 E/Web Console( 2863): http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest
10-04 17:50:54.312 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13438:12
10-04 17:50:54.312 E/Web Console( 2863):     at beginPhase (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30753:15)
10-04 17:50:54.312 E/Web Console( 2863):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30493:11)
10-04 17:50:54.312 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:32332:36
10-04 17:50:54.312 E/Web Console( 2863):     at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19194:10)
10-04 17:50:54.312 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19470:7:431
10-04 17:50:54.312 E/Web Console( 2863): Error: [$rootScope:inprog] $digest already in progress
10-04 17:50:54.312 E/Web Console( 2863): http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest
10-04 17:50:54.312 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13438:12
10-04 17:50:54.312 E/Web Console( 2863):     at beginPhase (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30753:15)
10-04 17:50:54.312 E/Web Console( 2863):     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30191:9)
10-04 17:50:54.312 E/Web Console( 2863):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30503:24)
10-04 17:50:54.312 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:32332:36
10-04 17:50:54.312 E/Web Console( 2863):     at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19194:10)
10-04 17:50:54.312 E/Web Console( 2863):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19470:7:431
10-04 17:50:54.322 E/Web Console( 2863): Uncaught Error: [$rootScope:inprog] $digest already in progress
10-04 17:50:54.322 E/Web Console( 2863): http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest:30506

```
I'm using $scope.$apply() from time to time when I'm forced to, but to be sure, I protected each call with a check on the phase to prevent this and it does not seem to come from our application code.

Did you already encountered that? 

I tried to switch on crosswalk but I get the same error :(
Thank you by advance for your help!</span>

<span is-issue-template></span>

**Comment by sjahan** [comment]
Just figured out.
I don't understand why I had this. 
I debugged a lot and this was masking the real problem, and I missed one polyfill for the old Android webviews...

Anyway, i'm still interested if you have some explanation why this happened :)

Thank you anyway for that good work, it's a real pleasure to use Ionic everyday!!! :D
