### ISSUE TITLE
I can't push a new view from push.rx.notification()

### ISSUE THREAD

**Issue by gabrielpeixoto** [driftyco/ionic#8549]
When I try to push a new view, like that:

    constructor(public navCtrl: NavController,
                public storage: Storage,
                private apiRequest: ApiRequest,
                public loadingCtrl: LoadingController,
                public push: Push) {
        console.log('M: iniciando pagina monitoramentos');

        this.push.rx.notification()
            .subscribe((item: any) => {
              this.navCtrl.push(Aparicoes, {
                'id_monitoramento': item.payload.id_monitoramento
              });
  
            });

Then next view was blank. And i got the error

`main.js:6 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'remove' of nullt.handleError @ main.js:6
main.js:6 ORIGINAL STACKTRACE:t.handleError @ main.js:6
main.js:6 Error: Uncaught (in promise): TypeError: Cannot read property 'remove' of null
    at s (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (main.js:7)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at XMLHttpRequest.invoke (polyfills.js:3)t.handleError @ main.js:6
polyfills.js:3 Unhandled Promise rejection: Cannot read property 'remove' of null ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'remove' of null(…) TypeError: Cannot read property 'remove' of null
    at e.t.dismiss (file:///android_asset/www/build/main.js:14:11819)
    at file:///android_asset/www/build/main.js:35:28573
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13400)
    at Object.onInvoke (file:///android_asset/www/build/main.js:7:31418)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13351)
    at e.run (file:///android_asset/www/build/polyfills.js:3:10787)
    at file:///android_asset/www/build/polyfills.js:3:8889
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14029)
    at Object.onInvokeTask (file:///android_asset/www/build/main.js:7:31318)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13965)o @ polyfills.js:3
polyfills.js:3 Error: Uncaught (in promise): TypeError: Cannot read property 'remove' of null
    at s (file:///android_asset/www/build/polyfills.js:3:8546)
    at file:///android_asset/www/build/polyfills.js:3:8918
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14029)
    at Object.onInvokeTask (file:///android_asset/www/build/main.js:7:31318)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13965)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11389)
    at i (file:///android_asset/www/build/polyfills.js:3:8006)
    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:15182)`

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you provide a repo that we can use to reproduce this issue?

**Comment by gabrielpeixoto** [comment]
that was my mistake! sorry and thanks! =D

**Comment by somnathkcrescente** [comment]
i also have problem in redirect to new view when app is in background when i click on  app its only opens app not redirect to page plz help
