### ISSUE TITLE
Ionic2 RC0 ios build fails >ngc failed:  NGC encountered an error

### ISSUE THREAD

**Issue by florianbepunkt** [driftyco/ionic#8579]
My Ionic project works fine `with $ionic serve` but fails when trying to build:

I get errors, that some my variables are private and then it ends with

> ngc failed:  NGC encountered an error

This is my npm-debug.log. I can't figure out why it's not building. Any idea?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node5/5.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v5.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ionic-hello-world@~prebuild: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prebuild: no script for prebuild, continuing
7 info lifecycle ionic-hello-world@~build: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/roomary/node_modules/.bin:/usr/local/Cellar/node5/5.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle ionic-hello-world@~build: CWD: /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/roomary
11 silly lifecycle ionic-hello-world@~build: Args: [ '-c', 'ionic-app-scripts build' ]
12 silly lifecycle ionic-hello-world@~build: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~build: Failed to exec build script
14 verbose stack Error: ionic-hello-world@ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/roomary
17 error Darwin 15.5.0
18 error argv "/usr/local/Cellar/node5/5.12.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v5.12.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ionic-hello-world@ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by infinnie** [comment]
Precisely my problem: #https://github.com/driftyco/ionic-app-scripts/issues/114

**Comment by infinnie** [comment]
@florianbepunkt BTW paste the terminal output here as well OK?

**Comment by florianbepunkt** [comment]
Issue solved. Problem was wrong typings definition. Please take a look here: https://github.com/backand/backand-ionic2-starter/issues/4

Will close this.

**Comment by infinnie** [comment]
@florianbepunkt Good luck.
