### ISSUE TITLE
 Unable to find "tslint" command

### ISSUE THREAD

**Issue by vinodhum** [driftyco/ionic#8591]
Hi,
I am getting this error when try to start new RC0 project
using 
```
ionic start test sidemenu --v2 --ts
cd test
ionic serve

[15:56:37]  lint failed:  Unable to find "tslint" command: null

[15:56:37]  Error: Unable to find "tslint" command: null
    at C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\dist\lint.js:38:20
    at runTsLint (C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\dist\lint.js:35:12)
    at C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\dist\lint.js:22:13
    at FSReqWrap.oncomplete (fs.js:82:15)

[15:56:37]  copy finished in 333 ms
[15:56:37]  bundle dev failed:  Could not resolve '@angular/platform-browser-dynamic' from C:\Users\vinodhum\Desktop\App-v1\plus\src\app\main.dev.ts

[15:56:37]  Error: Could not resolve '@angular/platform-browser-dynamic' from C:\Users\vinodhum\Desktop\App-v1\plus\src\app\main.dev.ts
    at Error (native)
    at C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21
    at C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\browser-resolve\index.js:265:24
    at C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:46:14
    at process (C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\vinodhum\Desktop\App-v1\plus\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

```

```
here is output of "ionic info"
$ ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8.1
Node Version: v4.6.0
```

here is what I have tried to resolve it
uninstall - reinstall ionic, gulp,nodejs
tried deleting %appdata%
then install everything again.
then install fresh new OS and then tried installing everything again.
but still same error.

**Comment by RunningV** [comment]
I'm Chinese. my friend happennd to the same issue. I try to several times to make the same error, finally i reproduce the error. I use `npm install` never find the the error. but when i try to  use `cnpm install` ,it happens to the error. the project may need to download packages from github, maybe u need to use gitbash to download the project and run it.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is caused by you running NPM 2, for RC0 we require NPM 3. Node 4 unfortunately still installs NPM 2 by default, but you can update to NPM 3 by running `npm install -g npm`. You can also install Node 6 which will give you NPM 3 by default. Node 6 is scheduled to become the new LTS release this month, so this may be your better bet. Thanks!

**Comment by vinodhum** [comment]
thanx, finally installing Node 6 resolved it.

**Comment by RunningV** [comment]
this is not just npm version problem. i always use npm@3.x.x but also happened to the problem. now my npm is `3.10.7`.I try to use `ionic start demo --v2` to create initial project. first time is failed, and i try to `npm install` and `cnpm install` to install relay package, it happens to ok. but my friend try also failure, so i want to check out the resoure-problem. i delete `node_modules` file. and `npm install` again. the problem is always at there. i have no idea about the problem. 
i think the demo project may need to use git to download relay from github or npm.I am in Chinese mainland . maybe it's the problem to network.
Anyone can try to delete ur `node_modules` and install again to reproduce the problem?

**Comment by haydenJogs92** [comment]
I get the unable to find ts lint command as well. The project can serve, but it cannot build to ios.

I've tried uninstalling and reinstalling node, npm, ionic & cordova. 

Here's my system

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 


$ ionic start test --v2

$ ionic build ios

Running 'build:before' npm script before build
> ionic-hello-world@ build /Users/haydenbrown/Desktop/ionicProject/myapps/test
> ionic-app-scripts build
[21:42:46]  ionic-app-scripts 0.0.30
[21:42:46]  build prod started ...
[21:42:46]  clean started ...
[21:42:46]  clean finished in 7 ms
[21:42:46]  copy started ...
[21:42:46]  ngc started ...
[21:42:46]  lint started ...
[21:42:46]  lint failed:  Unable to find "tslint" command: null

[21:42:46]  Error: Unable to find "tslint" command: null
    at /usr/local/lib/node_modules/@ionic/app-scripts/dist/lint.js:38:20
    at runTsLint (/usr/local/lib/node_modules/@ionic/app-scripts/dist/lint.js:35:12)
    at /usr/local/lib/node_modules/@ionic/app-scripts/dist/lint.js:22:13
    at FSReqWrap.oncomplete (fs.js:123:15)

[21:42:46]  copy finished in 38 ms
[21:42:46]  ngc: module.js:457
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/haydenbrown/Desktop/ionicProject/myapps/test/node_modules/tsickle/build/src/tsickle.js:7:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)


[21:42:46]  ngc failed:  NGC encountered an error

[21:42:46]  Error: NGC encountered an error
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@ionic/app-scripts/dist/ngc.js:62:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

Error running ionic app script "build": Error: NGC encountered an error



npm
 ERR! Darwin 15.6.0
npm
 ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm
 ERR! node v6.7.0

npm ERR! npm  v3.10.3

npm ERR! code ELIFECYCLE

npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`

npm ERR! Exit status 1

npm ERR! 
npm
 ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR!
 Make sure you have the latest version of node.js and npm installed.
npm ERR!
 If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!
     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm
 ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm 
ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     /Users/haydenbrown/Desktop/ionicProject/myapps/test/npm-debug.log

**Comment by mchapman** [comment]
Seems to happen wth yarn as well

**Comment by adirzoari** [comment]
@jgw96 i have the same issue when i run "npm run build"
i tried everything:deleted all my files cordova\ionic\npm\node\node_modules and then installed again.
i have npm 3.10.8 and node 3.10.8
![ionic infonew](https://cloud.githubusercontent.com/assets/20258998/19367226/e8ff71ca-91a2-11e6-8381-1b48c17ebbb8.jpg)

```
;int failed: Unable to find "tslint" command: null
[16:43:35] Error: Unable to find "tslint" command: null
at C:\Users\Adir\development\eventApp\node_modules\@ionic\app-scripts\dist\lint.js:38:20
at runTsLint (C:\Users\Adir\development\eventApp\node_modules\@ionic\app-scripts\dist\lint.js:35:12)
at C:\Users\Adir\development\eventApp\node_modules\@ionic\app-scripts\dist\lint.js:22:13
at FSReqWrap.oncomplete (fs.js:123:15)
[18:25:35] copy finished in 32 ms
[18:25:35] ngc failed: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli has been installed with NPM.
[18:25:35] Error: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli has been installed with NPM.
at C:\Users\Adir\development\eventApp\node_modules\@ionic\app-scripts\dist\ngc.js:40:20
at runNgc (C:\Users\Adir\development\eventApp\node_modules\@ionic\app-scripts\dist\ngc.js:34:12)
at C:\Users\Adir\development\eventApp\node_modules\@ionic\app-scripts\dist\ngc.js:18:16
Error running ionic app script "build": Error: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli has been installed with NPM.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: ionic-app-scripts build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Adir\development\eventApp\npm-debug.log

C:\Users\Adir\development\eventApp>

```
