### ISSUE TITLE
gulp test,error:ngc:2 basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

### ISSUE THREAD

**Issue by chengziqing** [driftyco/ionic#8640]
F:\workspace\html5\ionic>gulp test
[10:03:12] Using gulpfile F:\workspace\html5\ionic\gulpfile.js
[10:03:12] Starting 'test.assembleVendorJs'...
[10:03:12] Starting 'compile.karma'...

F:\workspace\html5\ionic\node_modules\.bin\ngc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

[10:03:12] 'compile.karma' errored after 478 ms
[10:03:12] Error: Command failed: node --max_old_space_size=8096 F:\workspace\html5\ionic/node_modul
es/.bin/ngc -p F:\workspace\html5\ionic\dist\ionic-angular\umd/tsconfig.json
F:\workspace\html5\ionic\node_modules\.bin\ngc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
[10:03:13] Finished 'test.assembleVendorJs' after 728 ms

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by jdrake3** [comment]
Please at least provide a link to the issue template.
