### ISSUE TITLE
When using cordova with android, building failed.

### ISSUE THREAD

**Issue by lygstate** [driftyco/ionic#8652]
**Steps to reproduce:**
Implement the following moduel
```

export class SpinnerDialog {
    public static show(title: string, message: string, cancelCallback: boolean | ((data: any) => any)): void {
      if (typeof cordova === 'undefined') {
        return
      }
      let finalCallback:(data:any) => any = function () {}
      if (typeof cancelCallback === 'function') {
        finalCallback = cancelCallback
      }
      cordova.exec(finalCallback, null, 'SpinnerDialog', 'show', [ title, message, !!cancelCallback ])
    }
    public static hide(success: () => void, fail: () => void): void {
      if (typeof cordova === 'undefined') {
        return
      }
      cordova.exec(success, fail, 'SpinnerDialog', 'hide', [ '', '' ])
    }
}

```

stacktrace:
```
[00:04:43]  ngc: Error: Error at C:/CI-Cor/acrop/acrop-client/.tmp/providers/dialog.ts:4:18: Cannot find name 'cordova'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/providers/dialog.ts:11:7: Cannot find name 'cordova'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/providers/dialog.ts:14:18: Cannot find name 'cordova'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/providers/dialog.ts:17:7: Cannot find name 'cordova'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/devicelist/devicelist.ts:16:5: Cannot find name 'jdenticon'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:360:42: Property 'deviceInit' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:360:79: Property 'islive' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:365:42: Property 'deviceInit' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:365:79: Property 'islive' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:370:41: Property 'deviceInit' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:376:40: Property 'outputInfos' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:385:41: Property 'vedio_url' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:390:41: Property 'vedio_url' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:395:41: Property 'sensorInfos' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:401:40: Property 'sensorInfos' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/status/status.ngfactory.ts:462:41: Property 'deviceInit' is private and only accessible within class 'StatusPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/taskedit/taskedit.ngfactory.ts:246:40: Property 'relays' is private and only accessible within class 'TaskEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/taskedit/taskedit.ngfactory.ts:299:41: Property 'hasOverlap' is private and only accessible within class 'TaskEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/taskedit/taskedit.ngfactory.ts:304:42: Property 'submitResult' is private and only accessible within class 'TaskEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/taskedit/taskedit.ngfactory.ts:309:74: Property 'submitResultContent' is private and only accessible within class 'TaskEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/taskedit/taskedit.ngfactory.ts:314:42: Property 'submitResult' is private and only accessible within class 'TaskEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/taskedit/taskedit.ngfactory.ts:319:74: Property 'submitResultContent' is private and only accessible within class 'TaskEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:432:40: Property 'script' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:442:40: Property 'args' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:571:42: Property 'submitResult' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:576:72: Property 'submitResultContent' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:581:42: Property 'submitResult' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:586:72: Property 'submitResultContent' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:601:43: Property 'script' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/scriptedit/scriptedit.ngfactory.ts:606:43: Property 'args' is private and only accessible within class 'ScriptEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/statusedit/statusedit.ngfactory.ts:230:40: Property 'relays' is private and only accessible within class 'StatusEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/statusedit/statusedit.ngfactory.ts:264:41: Property 'deviceInit' does not exist on type 'StatusEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/statusedit/statusedit.ngfactory.ts:269:41: Property 'submitResult' is private and only accessible within class 'StatusEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/statusedit/statusedit.ngfactory.ts:274:71: Property 'submitResultContent' is private and only accessible within class 'StatusEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/statusedit/statusedit.ngfactory.ts:279:41: Property 'submitResult' is private and only accessible within class 'StatusEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/statusedit/statusedit.ngfactory.ts:284:71: Property 'submitResultContent' is private and only accessible within class 'StatusEditPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/deviceinfo/deviceinfo.ngfactory.ts:539:40: Property 'pageName' is private and only accessible within class 'DeviceInfoPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/deviceinfo/deviceinfo.ngfactory.ts:571:41: Property 'pageName' is private and only accessible within class 'DeviceInfoPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/deviceinfo/deviceinfo.ngfactory.ts:619:42: Property 'pageName' is private and only accessible within class 'DeviceInfoPage'.
Error at C:/CI-Cor/acrop/acrop-client/.tmp/pages/deviceinfo/deviceinfo.ngfactory.ts:743:43: Property 'pageName' is private and only accessible within class 'DeviceInfoPage'.
    at check (C:\CI-Cor\acrop\acrop-client\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (C:\CI-Cor\acrop\acrop-client\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at C:\CI-Cor\acrop\acrop-client\node_modules\@angular\tsc-wrapped\src\main.js:33:23
```

**Which Ionic Version?** 1.x or 2.x
2 rc.0

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. These are actually issues in your app and not ionic issues. When building to a device using `ionic run` or `ionic emulate` app-scripts does a prod build. This production build runs NGC to do AoT compiling of your templates. Because of how NGC works it can do typechecking and error checking on methods and variables bound to in your template. Since this is not an Ionic issue I am going to be closing this issue for now. Just from glancing at the error here it looks as if you have some thing labeled `private` that should be `public` instead. Thanks!
