### ISSUE TITLE
no such file or directory, scandir

### ISSUE THREAD

**Issue by rkyleg** [driftyco/ionic#8654]
I am getting this error now that I can get the bundle prod process to finish successfully. 

[13:03:45]  bundle prod finished in 10.92 s
[13:03:45]  sass started ...
[13:03:45]  build prod failed:  ENOENT: no such file or directory, scandir "/Users/rkyleg/mega/projects/diamondpro_mobile_v2/src/compiled/app"

[13:03:45]  Error: ENOENT: no such file or directory, scandir "/Users/rkyleg/mega/projects/diamondpro_mobile_v2/src/compiled/app"
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at getSiblingSassFiles (/Users/rkyleg/mega/projects/diamondpro_mobile_v2/node_modules/@ionic/app-scripts/dist/sass.js:130:23)
    at addComponentSassFiles (/Users/rkyleg/mega/projects/diamondpro_mobile_v2/node_modules/@ionic/app-scripts/dist/sass.js:115:32)
    at /Users/rkyleg/mega/projects/diamondpro_mobile_v2/node_modules/@ionic/app-scripts/dist/sass.js:102:9
    at Array.forEach (native)
    at getComponentSassFiles (/Users/rkyleg/mega/projects/diamondpro_mobile_v2/node_modules/@ionic/app-scripts/dist/sass.js:101:26)
    at generateSassData (/Users/rkyleg/mega/projects/diamondpro_mobile_v2/node_modules/@ionic/app-scripts/dist/sass.js:86:30)
    at Object.sass (/Users/rkyleg/mega/projects/diamondpro_mobile_v2/node_modules/@ionic/app-scripts/dist/sass.js:42:9)
    at "/Users/rkyleg/mega/projects/diamondpro_mobile_v2/node_modules/@ionic/app-scripts/dist/build.js:43:23"

node version: v6.7.0
npm version: v3.10.3

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#146

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build issue and not a framework issue I have moved this issue to the app-scripts repo. Thanks!
