### ISSUE TITLE
Unmet Peer Dependencies - ionic 2 demo app setup broken

### ISSUE THREAD

**Issue by rlucian** [driftyco/ionic#8687]
When installing Ionic as per the guide and creating a new app, npm install throws broken dependencies on critical packages.

Therefore 
```ionic build```
fails completely

**Steps to reproduce:**
1. (just in case) uninstalled node and all npm related stuff for good measure
2. followed the ionic 2 installation steps by the book (install node, install ionic, install cordova, create app with -v2
3. run ```npm install```

```
npm install
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/platform-server@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/core@2.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/http@2.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
```

environment is
```
ionic info
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.8.0
```
but it's the same with node 4.6.0

**Comment by ErikAugust** [comment]
+1

**Comment by perdjurner** [comment]
I had the same problem. what worked for me was removing the ^ character from all dependencies in package.json so that it uses specific versions instead.

**Comment by markisme** [comment]
I had this problem, too. And remove the ^ character helped, but what's the reason, conflict between dependences?

**Comment by rlucian** [comment]
just in case this could help:
```
# npm outdated
Package                   Current                   Wanted      Latest  Location
@angular/compiler-cli       0.6.4                    0.6.4       2.1.0  ionic-hello-world
@ionic/app-scripts         0.0.30                   0.0.30      0.0.33  ionic-hello-world
ionic-angular          2.0.0-rc.0  2.0.0-rc.0-201610131811  2.0.0-rc.1  ionic-hello-world
```

**Comment by rlucian** [comment]
@perdjurner and @markisme 
forcing the specific versions helped me too with the dependencies issue, but default app, with no changes, still doesn't compile.

could you do a run and see if it compiles for you?

```
# ionic platform add android
... ... works fine
# ionic run android
Running 'run:before' npm script before run
> ionic-hello-world@ build D:\#Radoo\www\cutePuppy
> ionic-app-scripts build
[10:41:01]  ionic-app-scripts 0.0.30
[10:41:01]  build prod started ...
[10:41:01]  clean started ...
[10:41:01]  clean finished in 11 ms
[10:41:01]  copy started ...
[10:41:02]  ngc started ...
[10:41:02]  lint started ...
[10:41:02]  copy finished in 108 ms
[10:41:02]  lint finished in 641 ms
[10:41:08]  ngc: Error: Compilation failed. Resource file not found: D:/home.html
    at Object.get (D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler-cli\src\codegen.js:123:27)
    at DirectiveNormalizer._fetch (D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler\bundles\compiler.umd.js:13455:45)
    at DirectiveNormalizer.normalizeTemplateAsync (D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler\bundles\compiler.umd.js:13498:23)
    at DirectiveNormalizer.normalizeDirective (D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler\bundles\compiler.umd.js:13473:46)
    at D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler\bundles\compiler.umd.js:12982:139
    at Array.map (native)
    at D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler\bundles\compiler.umd.js:12982:80
    at Array.map (native)
    at OfflineCompiler.compile (D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler\bundles\compiler.umd.js:12975:31)
    at D:\#Radoo\www\cutePuppy\node_modules\@angular\compiler-cli\src\codegen.js:108:18


[10:41:08]  ngc: Compilation failed


[10:41:08]  ngc failed:  NGC encountered an error

[10:41:08]  Error: NGC encountered an error
    at ChildProcess.<anonymous> (D:\#Radoo\www\cutePuppy\node_modules\@ionic\app-scripts\dist\ngc.js:62:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\#Radoo\www\cutePuppy\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error running ionic app script "build": Error: NGC encountered an error



npm
ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm
ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!
     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     D:\#Radoo\www\cutePuppy\npm-debug.log

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```
I am not moving it to the ionic-cli repo issues, since this would probably be implicitly solved by fixing the dependencies in the npm packages...

**Comment by rlucian** [comment]
issue here https://github.com/marcoturi/ionic2-boilerplate/issues/6 also seems related

**Comment by ZiFFeL1992** [comment]
Can you try to upgrade ionic-app-scripts?

`npm i ionic-app-scripts@0.0.33`

**Comment by rlucian** [comment]
@ZiFFeL1992 
based on other subsequent related reports and proposed workarounds, I managed to get the dependencies problem solved, by using 
```
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "@ionic/storage": "^1.0.3",
    "ionic-angular": "^2.0.0-rc.1",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.33",
    "typescript": "^2.0.3"
  },
```
but notice compiler-cli and rxjs are strict for this to work.
and yes app-scripts are at 0.0.33

remaining problem however is that compile still won't work.

**Comment by rlucian** [comment]
UPDATE: 
there might have been a problem with my environment.
retraced my steps, reinstalled everything including node, restarted windows, now blank app compiles just fine.

for the record, package.json minimal workaround for the dependencies problem is pinning two packages:
```
    "@angular/compiler-cli": "0.6.2",
    "rxjs": "5.0.0-beta.12",
``` 
observe the lack of the ^

and updating one:
```
    "@ionic/app-scripts": "^0.0.33",
```
thank you.
