### ISSUE TITLE
Unable to update to RC1

### ISSUE THREAD

**Issue by X4V1** [driftyco/ionic#8695]
I had an Ionic 2 RC0 application (created with the ionic-cli).

I would like to update to Ionic 2 RC1.

I updated the package.json to:

```
  "dependencies": {
    "@angular/common": "^2.0.2",
    "@angular/compiler": "^2.0.2",
    "@angular/compiler-cli": "^0.6.2",
    "@angular/core": "^2.0.2",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.2",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.2",
    "@ionic/storage": "^1.0.3",
    "ionic-angular": "^2.0.0-rc.1",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0",
    "lodash": "^4.16.4",
    "ng2-inline-svg": "^1.2.0",
    "rxjs": "^5.0.0-beta.12",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.31",
    "typescript": "^2.0.3",
    "@types/lodash": "^4.14.37"
  },
```

I deleted the node_module directory.
To be sure that there is nothing left i have executed `npm cache clear && npm cache clean`

and now when I have some unmet peer dependencies when I try to install all dependencies with `npm install`

```
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.9.3 install C:\Users\Xavier\Desktop\sigi\sigi_mobile\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.3/win32-x64-48_binding.node
Binary downloaded and installed at C:\Users\Xavier\Desktop\sigi\sigi_mobile\node_modules\node-sass\vendor\win32-x64-48\binding.node

> node-sass@3.9.3 postinstall C:\Users\Xavier\Desktop\sigi\sigi_mobile\node_modules\node-sass
> node scripts/build.js

"C:\Users\Xavier\Desktop\sigi\sigi_mobile\node_modules\node-sass\vendor\win32-x64-48\binding.node" exists.
 testing binary.
Binary is fine; exiting.
ionic-hello-world@ C:\Users\Xavier\Desktop\sigi\sigi_mobile
+-- @angular/common@2.1.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.1.0
+-- @angular/compiler-cli@0.6.4
| +-- @angular/tsc-wrapped@0.3.0
| | `-- tsickle@0.1.7
| |   `-- source-map-support@0.3.3
| |     `-- source-map@0.1.32
| +-- minimist@1.2.0
| +-- parse5@2.2.2
| `-- reflect-metadata@0.1.8
+-- UNMET PEER DEPENDENCY @angular/core@2.1.0
+-- @angular/forms@2.1.0
+-- @angular/http@2.1.0
+-- @angular/platform-browser@2.1.0
+-- @angular/platform-browser-dynamic@2.1.0
+-- UNMET PEER DEPENDENCY @angular/platform-server@2.1.0
+-- @ionic/app-scripts@0.0.31
| +-- autoprefixer@6.4.1
| | +-- browserslist@1.3.6
| | +-- caniuse-db@1.0.30000557
| | +-- normalize-range@0.1.2
| | +-- num2fraction@1.2.2
| | `-- postcss-value-parser@3.3.0
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.0.0
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- chokidar@1.6.0
| | +-- anymatch@1.3.0
| | | +-- arrify@1.0.1
| | | `-- micromatch@2.3.11
| | |   +-- arr-diff@2.0.0
| | |   | `-- arr-flatten@1.0.1
| | |   +-- array-unique@0.2.1
| | |   +-- braces@1.8.5
| | |   | +-- expand-range@1.8.2
| | |   | | `-- fill-range@2.2.3
| | |   | |   +-- is-number@2.1.0
| | |   | |   +-- isobject@2.1.0
| | |   | |   | `-- isarray@1.0.0
| | |   | |   `-- randomatic@1.1.5
| | |   | +-- preserve@0.2.0
| | |   | `-- repeat-element@1.1.2
| | |   +-- expand-brackets@0.1.5
| | |   | `-- is-posix-bracket@0.1.1
| | |   +-- extglob@0.3.2
| | |   +-- filename-regex@2.0.0
| | |   +-- kind-of@3.0.4
| | |   | `-- is-buffer@1.1.4
| | |   +-- normalize-path@2.0.1
| | |   +-- object.omit@2.0.0
| | |   | +-- for-own@0.1.4
| | |   | | `-- for-in@0.1.6
| | |   | `-- is-extendable@0.1.1
| | |   +-- parse-glob@3.0.4
| | |   | +-- glob-base@0.3.0
| | |   | `-- is-dotfile@1.0.2
| | |   `-- regex-cache@0.4.3
| | |     +-- is-equal-shallow@0.1.3
| | |     `-- is-primitive@2.0.0
| | +-- async-each@1.0.1
| | +-- glob-parent@2.0.0
| | +-- inherits@2.0.3
| | +-- is-binary-path@1.0.1
| | | `-- binary-extensions@1.7.0
| | +-- is-glob@2.0.1
| | | `-- is-extglob@1.0.0
| | +-- path-is-absolute@1.0.1
| | `-- readdirp@2.1.0
| |   +-- readable-stream@2.1.5
| |   | +-- buffer-shims@1.0.0
| |   | +-- core-util-is@1.0.2
| |   | +-- isarray@1.0.0
| |   | +-- process-nextick-args@1.0.7
| |   | `-- string_decoder@0.10.31
| |   `-- set-immediate-shim@1.0.1
| +-- clean-css@3.4.19
| | +-- commander@2.8.1
| | | `-- graceful-readlink@1.0.1
| | `-- source-map@0.4.4
| |   `-- amdefine@1.0.0
| +-- cross-spawn@4.0.0
| | +-- lru-cache@4.0.1
| | | +-- pseudomap@1.0.2
| | | `-- yallist@2.0.0
| | `-- which@1.2.11
| |   `-- isexe@1.1.2
| +-- fs-extra@0.30.0
| | +-- graceful-fs@4.1.9
| | +-- jsonfile@2.4.0
| | +-- klaw@1.3.0
| | `-- rimraf@2.5.4
| +-- magic-string@0.16.0
| | `-- vlq@0.2.1
| +-- node-sass@3.9.3
| | +-- async-foreach@0.1.3
| | +-- cross-spawn@3.0.1
| | +-- gaze@1.1.2
| | | `-- globule@1.0.0
| | |   +-- glob@7.0.6
| | |   `-- lodash@4.9.0
| | +-- get-stdin@4.0.1
| | +-- glob@7.1.1
| | | +-- fs.realpath@1.0.0
| | | +-- inflight@1.0.6
| | | | `-- wrappy@1.0.2
| | | `-- once@1.4.0
| | +-- in-publish@2.0.0
| | +-- lodash.clonedeep@4.5.0
| | +-- meow@3.7.0
| | | +-- camelcase-keys@2.1.0
| | | | `-- camelcase@2.1.1
| | | +-- decamelize@1.2.0
| | | +-- loud-rejection@1.6.0
| | | | +-- currently-unhandled@0.4.1
| | | | | `-- array-find-index@1.0.2
| | | | `-- signal-exit@3.0.1
| | | +-- map-obj@1.0.1
| | | +-- normalize-package-data@2.3.5
| | | | +-- hosted-git-info@2.1.5
| | | | +-- is-builtin-module@1.0.0
| | | | `-- validate-npm-package-license@3.0.1
| | | |   +-- spdx-correct@1.0.2
| | | |   | `-- spdx-license-ids@1.2.2
| | | |   `-- spdx-expression-parse@1.0.4
| | | +-- object-assign@4.1.0
| | | +-- read-pkg-up@1.0.1
| | | | +-- find-up@1.1.2
| | | | | `-- path-exists@2.1.0
| | | | `-- read-pkg@1.1.0
| | | |   +-- load-json-file@1.1.0
| | | |   | +-- parse-json@2.2.0
| | | |   | | `-- error-ex@1.3.0
| | | |   | |   `-- is-arrayish@0.2.1
| | | |   | +-- pify@2.3.0
| | | |   | `-- strip-bom@2.0.0
| | | |   |   `-- is-utf8@0.2.1
| | | |   `-- path-type@1.1.0
| | | +-- redent@1.0.0
| | | | +-- indent-string@2.1.0
| | | | | `-- repeating@2.0.1
| | | | |   `-- is-finite@1.0.2
| | | | `-- strip-indent@1.0.1
| | | `-- trim-newlines@1.0.0
| | +-- mkdirp@0.5.1
| | | `-- minimist@0.0.8
| | +-- nan@2.4.0
| | +-- node-gyp@3.4.0
| | | +-- fstream@1.0.10
| | | +-- nopt@3.0.6
| | | | `-- abbrev@1.0.9
| | | +-- npmlog@3.1.2
| | | +-- osenv@0.1.3
| | | | +-- os-homedir@1.0.2
| | | | `-- os-tmpdir@1.0.2
| | | +-- path-array@1.0.1
| | | | `-- array-index@1.0.0
| | | |   +-- debug@2.2.0
| | | |   | `-- ms@0.7.1
| | | |   `-- es6-symbol@3.1.0
| | | |     +-- d@0.1.1
| | | |     `-- es5-ext@0.10.12
| | | |       `-- es6-iterator@2.0.0
| | | +-- semver@5.3.0
| | | `-- tar@2.2.1
| | |   `-- block-stream@0.0.9
| | +-- npmlog@4.0.0
| | | +-- are-we-there-yet@1.1.2
| | | | +-- delegates@1.0.0
| | | | `-- readable-stream@2.1.5
| | | |   `-- isarray@1.0.0
| | | +-- console-control-strings@1.1.0
| | | +-- gauge@2.6.0
| | | | +-- aproba@1.0.4
| | | | +-- has-color@0.1.7
| | | | +-- has-unicode@2.0.1
| | | | +-- string-width@1.0.2
| | | | | +-- code-point-at@1.0.1
| | | | | | `-- number-is-nan@1.0.1
| | | | | `-- is-fullwidth-code-point@1.0.0
| | | | `-- wide-align@1.1.0
| | | `-- set-blocking@2.0.0
| | +-- request@2.75.0
| | | +-- aws-sign2@0.6.0
| | | +-- aws4@1.5.0
| | | +-- bl@1.1.2
| | | | `-- readable-stream@2.0.6
| | | |   `-- isarray@1.0.0
| | | +-- caseless@0.11.0
| | | +-- combined-stream@1.0.5
| | | | `-- delayed-stream@1.0.0
| | | +-- extend@3.0.0
| | | +-- forever-agent@0.6.1
| | | +-- form-data@2.0.0
| | | | `-- asynckit@0.4.0
| | | +-- har-validator@2.0.6
| | | | +-- commander@2.9.0
| | | | +-- is-my-json-valid@2.15.0
| | | | | +-- generate-function@2.0.0
| | | | | +-- generate-object-property@1.2.0
| | | | | | `-- is-property@1.0.2
| | | | | +-- jsonpointer@4.0.0
| | | | | `-- xtend@4.0.1
| | | | `-- pinkie-promise@2.0.1
| | | |   `-- pinkie@2.0.4
| | | +-- hawk@3.1.3
| | | | +-- boom@2.10.1
| | | | +-- cryptiles@2.0.5
| | | | +-- hoek@2.16.3
| | | | `-- sntp@1.0.9
| | | +-- http-signature@1.1.1
| | | | +-- assert-plus@0.2.0
| | | | +-- jsprim@1.3.1
| | | | | +-- extsprintf@1.0.2
| | | | | +-- json-schema@0.2.3
| | | | | `-- verror@1.3.6
| | | | `-- sshpk@1.10.1
| | | |   +-- asn1@0.2.3
| | | |   +-- assert-plus@1.0.0
| | | |   +-- bcrypt-pbkdf@1.0.0
| | | |   +-- dashdash@1.14.0
| | | |   | `-- assert-plus@1.0.0
| | | |   +-- ecc-jsbn@0.1.1
| | | |   +-- getpass@0.1.6
| | | |   | `-- assert-plus@1.0.0
| | | |   +-- jodid25519@1.0.2
| | | |   +-- jsbn@0.1.0
| | | |   `-- tweetnacl@0.14.3
| | | +-- is-typedarray@1.0.0
| | | +-- isstream@0.1.2
| | | +-- json-stringify-safe@5.0.1
| | | +-- mime-types@2.1.12
| | | | `-- mime-db@1.24.0
| | | +-- node-uuid@1.4.7
| | | +-- oauth-sign@0.8.2
| | | +-- qs@6.2.1
| | | +-- stringstream@0.0.5
| | | +-- tough-cookie@2.3.1
| | | `-- tunnel-agent@0.4.3
| | `-- sass-graph@2.1.2
| |   `-- yargs@4.8.1
| |     +-- cliui@3.2.0
| |     | `-- wrap-ansi@2.0.0
| |     +-- get-caller-file@1.0.2
| |     +-- lodash.assign@4.2.0
| |     +-- os-locale@1.4.0
| |     | `-- lcid@1.0.0
| |     |   `-- invert-kv@1.0.0
| |     +-- require-directory@2.1.1
| |     +-- require-main-filename@1.0.1
| |     +-- which-module@1.0.0
| |     +-- window-size@0.2.0
| |     +-- y18n@3.2.1
| |     `-- yargs-parser@2.4.1
| |       `-- camelcase@3.0.0
| +-- postcss@5.2.0
| | +-- js-base64@2.1.9
| | +-- source-map@0.5.6
| | `-- supports-color@3.1.2
| |   `-- has-flag@1.0.0
| +-- rollup@0.36.3
| | `-- source-map-support@0.4.3
| |   `-- source-map@0.5.6
| +-- rollup-plugin-commonjs@5.0.4
| | +-- acorn@4.0.3
| | +-- estree-walker@0.2.1
| | `-- resolve@1.1.7
| +-- rollup-plugin-json@2.0.2
| +-- rollup-plugin-node-builtins@2.0.0
| | +-- buffer-es6@4.9.2
| | +-- crypto-browserify@3.11.0
| | | +-- browserify-cipher@1.0.0
| | | | +-- browserify-aes@1.0.6
| | | | | `-- buffer-xor@1.0.3
| | | | +-- browserify-des@1.0.0
| | | | | `-- des.js@1.0.0
| | | | |   `-- minimalistic-assert@1.0.0
| | | | `-- evp_bytestokey@1.0.0
| | | +-- browserify-sign@4.0.0
| | | | +-- bn.js@4.11.6
| | | | +-- browserify-rsa@4.0.1
| | | | +-- elliptic@6.3.2
| | | | | +-- brorand@1.0.6
| | | | | `-- hash.js@1.0.3
| | | | `-- parse-asn1@5.0.0
| | | |   `-- asn1.js@4.8.1
| | | +-- create-ecdh@4.0.0
| | | +-- create-hash@1.1.2
| | | | +-- cipher-base@1.0.3
| | | | +-- ripemd160@1.0.1
| | | | `-- sha.js@2.4.5
| | | +-- create-hmac@1.1.4
| | | +-- diffie-hellman@5.0.2
| | | | `-- miller-rabin@4.0.0
| | | +-- pbkdf2@3.0.9
| | | +-- public-encrypt@4.0.0
| | | `-- randombytes@2.0.3
| | `-- process-es6@0.11.5
| +-- rollup-plugin-node-globals@1.0.9
| | `-- acorn@4.0.3
| +-- rollup-plugin-node-resolve@2.0.0
| | +-- browser-resolve@1.11.2
| | `-- builtin-modules@1.1.1
| +-- rollup-pluginutils@1.5.2
| | `-- minimatch@3.0.3
| |   `-- brace-expansion@1.1.6
| |     +-- balanced-match@0.4.2
| |     `-- concat-map@0.0.1
| +-- tslint@3.15.1
| | +-- colors@1.1.2
| | +-- diff@2.2.3
| | +-- findup-sync@0.3.0
| | | `-- glob@5.0.15
| | +-- optimist@0.6.1
| | | +-- minimist@0.0.10
| | | `-- wordwrap@0.0.3
| | `-- underscore.string@3.3.4
| |   +-- sprintf-js@1.0.3
| |   `-- util-deprecate@1.0.2
| +-- tslint-eslint-rules@1.5.0
| | `-- doctrine@0.7.2
| |   +-- esutils@1.1.6
| |   `-- isarray@0.0.1
| `-- uglify-js@2.7.3
|   +-- async@0.2.10
|   +-- source-map@0.5.6
|   +-- uglify-to-browserify@1.0.2
|   `-- yargs@3.10.0
|     +-- camelcase@1.2.1
|     +-- cliui@2.1.0
|     | +-- center-align@0.1.3
|     | | +-- align-text@0.1.4
|     | | | +-- longest@1.0.1
|     | | | `-- repeat-string@1.5.4
|     | | `-- lazy-cache@1.0.4
|     | +-- right-align@0.1.3
|     | `-- wordwrap@0.0.2
|     `-- window-size@0.1.0
+-- @ionic/storage@1.1.6
| +-- @types/localforage@0.0.30
| +-- localforage@1.4.3
| | `-- lie@3.0.2
| |   +-- es3ify@0.1.4
| |   | +-- esprima-fb@3001.1.0-dev-harmony-fb
| |   | +-- jstransform@3.0.0
| |   | | +-- base62@0.1.1
| |   | | `-- source-map@0.1.31
| |   | `-- through@2.3.8
| |   +-- immediate@3.0.6
| |   +-- inline-process-browser@1.0.0
| |   | +-- falafel@1.2.0
| |   | | +-- acorn@1.2.2
| |   | | +-- foreach@2.0.5
| |   | | `-- object-keys@1.0.11
| |   | `-- through2@0.6.5
| |   |   `-- readable-stream@1.0.34
| |   `-- unreachable-branch-transform@0.3.0
| |     +-- esmangle-evaluator@1.0.1
| |     `-- recast@0.10.43
| |       +-- ast-types@0.8.15
| |       +-- esprima-fb@15001.1001.0-dev-harmony-fb
| |       +-- private@0.1.6
| |       `-- source-map@0.5.6
| +-- localforage-cordovasqlitedriver@1.5.0
| `-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
+-- @types/lodash@4.14.37
+-- ionic-angular@2.0.0-rc.1
+-- ionic-native@2.2.2
+-- ionicons@3.0.0
+-- lodash@4.16.4
+-- ng2-inline-svg@1.2.0
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-rc.1
| `-- symbol-observable@1.0.4
+-- typescript@2.0.3
`-- zone.js@0.6.25

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/platform-server@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/core@2.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/http@2.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
```

I don't find a working solution. I'm stuck on this problem for a few hours and I can't find how to solve it. Could you help me please ?

**Comment by Spymannn** [comment]
I have the same problem here... I updated to RC1 and it become impossible to launch the app and I always have these UMMET PEER DEPENDENCY when I npm install.. 

Anyone has a solution ?

**Comment by rtpm** [comment]
#8691

**Comment by ZiFFeL1992** [comment]
Use:

```
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "ionic-angular": "^2.0.0-rc.1",
    "ionicons" : "^3.0.0",
    "@ionic/storage": "^1.0.3",
    "ionic-native": "^2.0.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  },
   "devDependencies": {
    "@ionic/app-scripts": "^0.0.33",
    "typescript": "^2.0.3"
  }
```

**Comment by marcoturi** [comment]
For a working example -> https://github.com/marcoturi/ionic2-boilerplate/blob/master/package.json

@ZiFFeL1992 your package.json is not working to me:

> npm WARN @angular/platform-browser-dynamic@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
> npm WARN @angular/http@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
> npm WARN @angular/platform-browser@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
> npm WARN @angular/forms@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
> npm WARN @angular/common@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
> npm WARN @angular/platform-server@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
> npm WARN @angular/compiler@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
> 

Please run `rm -rf node_modules/ && npm i` to test it

**Comment by ZiFFeL1992** [comment]
Missed the carrot:

`"@angular/core": "^2.0.0",`

It's fine in the PR, modify it and check again please.

**Comment by rlucian** [comment]
@marcoturi that solves the dependencies, but application won't compile.
try 
```
cordova platform add android
ionic run android 
```

**Comment by marcoturi** [comment]
@rlucian to me is working https://github.com/marcoturi/ionic2-boilerplate
git clone, npm i, npm run android:release

**Comment by rlucian** [comment]
did exactly that, with ```ionic build``` at instead of run, and i am getting these:

```
ionic build

Running 'build:before' npm script before build
> ionic2-boilerplate@0.5.0 build \i2-test
> bnr build
running better-npm-run in \i2-test
Executing script: build
to be executed: "ionic-app-scripts build"
[14:44:52]  ionic-app-scripts 0.0.30
[14:44:52]  build prod started ...
[14:44:52]  clean started ...
[14:44:52]  clean finished in 5 ms
[14:44:52]  copy started ...
[14:44:52]  ngc started ...
[14:44:52]  lint started ...
[14:44:52]  copy finished in 107 ms
[14:44:53]  lint finished in 1.10 s
[14:45:00]  ngc: Error: Compilation failed. Resource file not found: D:/home.html
    at Object.resourceLoader.get (D:\i2-test\node_modules\@angular\compiler-cli\src\codegen.js:123:27)
    at DirectiveNormalizer._fetch (D:\i2-test\node_modules\@angular\compiler\bundles\compiler.umd.js:13329:45)
    at DirectiveNormalizer.normalizeTemplateAsync (D:\i2-test\node_modules\@angular\compiler\bundles\compiler.umd.js:13372:23)
    at DirectiveNormalizer.normalizeDirective (D:\i2-test\node_modules\@angular\compiler\bundles\compiler.umd.js:13347:46)
    at D:\i2-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12849:139
    at Array.map (native)
    at D:\i2-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12849:80
    at Array.map (native)
    at OfflineCompiler.compile (D:\i2-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12842:31)
    at D:\i2-test\node_modules\@angular\compiler-cli\src\codegen.js:108:18


[14:45:00]  ngc: Compilation failed


[14:45:00]  ngc failed:  NGC encountered an error

[14:45:00]  Error: NGC encountered an error
    at ChildProcess.<anonymous> (D:\i2-test\node_modules\@ionic\app-scripts\dist\ngc.js:62:24)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at ChildProcess.cp.emit (D:\i2-test\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

Error running ionic app script "build": Error: NGC encountered an error
```

**Comment by X4V1** [comment]
@ZiFFeL1992 Big thanks ! It works like a charm, no unmet dependency, can serve and build without any mistake.

I don't know how do you found that working solution but you make me save a lot of time.

For me as for @marcoturi it's solved !

I don't know why we have to adapt it manually, it's really weird.

**Comment by marcoturi** [comment]
@rlucian 
read carefully, run those commands (copy and paste one by one):
```
git clone https://github.com/marcoturi/ionic2-boilerplate.git
cd ionic2-boilerplate
npm i
npm run android:release
```

**Comment by rlucian** [comment]
@marcoturi 
I cleaned all the environment and it seems the build errors went away, or at least now are related to the app, not the env.
so closed from my pov as well.
thank you.
