### ISSUE TITLE
App loading problem with Ionic 2.0.0.rc0

### ISSUE THREAD

**Issue by flamesoft** [driftyco/ionic#8749]
#### Short description of the problem:
The app runs well in the browser. But when I compile it to run on Android or iOS device, it is frozen during loading: First it shows a splash screen in a short time, then it stays on a white blank screen and nothing is shown in several minutes.
I have tried all kinds of adjustment for the splash screen but nothing works. The white blank screen is shown and nothing loads.

#### What behavior are you expecting?
No blank screen should be shown. The loading should be done after 10 seconds. It shouldn't freeze.

**Steps to reproduce:**
1. Compile an Ionic 2  app for iOS
2. Run it in XCode
3. Check if it loads.

```
insert any relevant code between the above and below backticks
```
My config.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.ionicframework.MyApp818708" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>MyApp</name>
  <description>An awesome Ionic/Cordova app.</description>
  <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
  <content src="index.html"/>
  <access origin="*"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  <allow-intent href="geo:*"/>
  <platform name="android">
    <allow-intent href="market:*"/>
    <icon src="resources/android/icon/drawable-ldpi-icon.png" density="ldpi"/>
    <icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
    <icon src="resources/android/icon/drawable-hdpi-icon.png" density="hdpi"/>
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" density="xhdpi"/>
    <icon src="resources/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi"/>
    <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
    <splash src="resources/android/splash/drawable-land-ldpi-screen.png" density="land-ldpi"/>
    <splash src="resources/android/splash/drawable-land-mdpi-screen.png" density="land-mdpi"/>
    <splash src="resources/android/splash/drawable-land-hdpi-screen.png" density="land-hdpi"/>
    <splash src="resources/android/splash/drawable-land-xhdpi-screen.png" density="land-xhdpi"/>
    <splash src="resources/android/splash/drawable-land-xxhdpi-screen.png" density="land-xxhdpi"/>
    <splash src="resources/android/splash/drawable-land-xxxhdpi-screen.png" density="land-xxxhdpi"/>
    <splash src="resources/android/splash/drawable-port-ldpi-screen.png" density="port-ldpi"/>
    <splash src="resources/android/splash/drawable-port-mdpi-screen.png" density="port-mdpi"/>
    <splash src="resources/android/splash/drawable-port-hdpi-screen.png" density="port-hdpi"/>
    <splash src="resources/android/splash/drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
    <icon src="resources/ios/icon/icon.png" width="57" height="57"/>
    <icon src="resources/ios/icon/icon@2x.png" width="114" height="114"/>
    <icon src="resources/ios/icon/icon-40.png" width="40" height="40"/>
    <icon src="resources/ios/icon/icon-40@2x.png" width="80" height="80"/>
    <icon src="resources/ios/icon/icon-40@3x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-50.png" width="50" height="50"/>
    <icon src="resources/ios/icon/icon-50@2x.png" width="100" height="100"/>
    <icon src="resources/ios/icon/icon-60.png" width="60" height="60"/>
    <icon src="resources/ios/icon/icon-60@2x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-60@3x.png" width="180" height="180"/>
    <icon src="resources/ios/icon/icon-72.png" width="72" height="72"/>
    <icon src="resources/ios/icon/icon-72@2x.png" width="144" height="144"/>
    <icon src="resources/ios/icon/icon-76.png" width="76" height="76"/>
    <icon src="resources/ios/icon/icon-76@2x.png" width="152" height="152"/>
    <icon src="resources/ios/icon/icon-83.5@2x.png" width="167" height="167"/>
    <icon src="resources/ios/icon/icon-small.png" width="29" height="29"/>
    <icon src="resources/ios/icon/icon-small@2x.png" width="58" height="58"/>
    <icon src="resources/ios/icon/icon-small@3x.png" width="87" height="87"/>
    <splash src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" height="1136"/>
    <splash src="resources/ios/splash/Default-667h.png" width="750" height="1334"/>
    <splash src="resources/ios/splash/Default-736h.png" width="1242" height="2208"/>
    <splash src="resources/ios/splash/Default-Landscape-736h.png" width="2208" height="1242"/>
    <splash src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" height="1536"/>
    <splash src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" height="768"/>
    <splash src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" height="2048"/>
    <splash src="resources/ios/splash/Default-Portrait~ipad.png" width="768" height="1024"/>
    <splash src="resources/ios/splash/Default@2x~iphone.png" width="640" height="960"/>
    <splash src="resources/ios/splash/Default~iphone.png" width="320" height="480"/>
  </platform>
  <platform name="wp8">
    <icon src="resources/wp8/icon/ApplicationIcon.png" width="99" height="99"/>
    <icon src="resources/wp8/icon/Background.png" width="159" height="159"/>
    <splash src="resources/wp8/splash/SplashScreenImage.png" width="768" height="1280"/>
  </platform>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashScreenDelay" value="0"/>
  <preference name="FadeSplashScreen" value="false"/>
  <preference name="FadeSplashScreenDuration" value="0"/>
  <preference name="SplashScreenBackgroundColor" value="0xFFFFFFFF"/>
  <preference name="SplashScreen" value="screen"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
  <plugin name="cordova-plugin-device" spec="~1.1.3"/>
  <plugin name="cordova-plugin-console" spec="~1.0.4"/>
  <plugin name="cordova-plugin-whitelist" spec="~1.3.0"/>
  <plugin name="cordova-plugin-splashscreen" spec="~4.0.0"/>
  <plugin name="cordova-plugin-statusbar" spec="~2.2.0"/>
  <plugin name="ionic-plugin-keyboard" spec="~2.2.1"/>
  <plugin name="ionic-plugin-deploy" spec="~0.6.4"/>
  <icon src="resources/android/icon/drawable-xhdpi-icon.png"/>
</widget>

```

**Other information: ** 

Same problems that other people experience 
- https://forum.ionicframework.com/t/ionic-ios-build-does-not-work-anymore-white-screen-of-death/48333/8
- https://forum.ionicframework.com/t/ionic2-rc1-builds-giving-white-screen-of-death/67100
- https://forum.ionicframework.com/t/white-screen-of-death-on-ios/62938
- https://forum.ionicframework.com/t/white-screen-of-death-after-splash-screen/63617

My log from XCode 8 when running simulator for iPhone 6s

 ```
objc[48957]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11b2e9910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11b07c210). One of the two will be used. Which one is undefined.
2016-10-17 08:20:52.005956 MyApp[48957:2591464] subsystem: com.apple.UIKit, category: HIDEventFiltered, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-17 08:20:52.018655 MyApp[48957:2591464] subsystem: com.apple.UIKit, category: HIDEventIncoming, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-17 08:20:52.033455 MyApp[48957:2591460] subsystem: com.apple.BaseBoard, category: MachPort, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
2016-10-17 08:20:52.043064 MyApp[48957:2591392] subsystem: com.apple.libsqlite3, category: logging, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-17 08:20:52.085447 MyApp[48957:2591392] subsystem: com.apple.UIKit, category: StatusBar, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-17 08:20:52.128 MyApp[48957:2591392] Apache Cordova native platform version 4.2.1 is starting.
2016-10-17 08:20:52.129 MyApp[48957:2591392] Multi-tasking -> Device: YES, App: YES
2016-10-17 08:20:52.180 MyApp[48957:2591392] CDVWKWebViewEngine: trying to inject XHR polyfill
2016-10-17 08:20:52.187225 MyApp[48957:2591392] subsystem: com.apple.UIKit, category: GestureEnvironment, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-17 08:20:52.189 MyApp[48957:2591392] CDVWKWebViewEngine will reload WKWebView if required on resume
2016-10-17 08:20:52.189 MyApp[48957:2591392] Using WKWebView
2016-10-17 08:20:52.190 MyApp[48957:2591392] [CDVTimer][handleopenurl] 0.059009ms
2016-10-17 08:20:52.193 MyApp[48957:2591392] [CDVTimer][intentandnavigationfilter] 2.979994ms
2016-10-17 08:20:52.194 MyApp[48957:2591392] [CDVTimer][gesturehandler] 0.195026ms
2016-10-17 08:20:52.216 MyApp[48957:2591392] [CDVTimer][splashscreen] 22.155046ms
2016-10-17 08:20:52.224 MyApp[48957:2591392] [CDVTimer][statusbar] 7.529974ms
2016-10-17 08:20:52.226 MyApp[48957:2591392] VERSION LABEL: 0.0.1:1476533568:
2016-10-17 08:20:52.227 MyApp[48957:2591392] [CDVTimer][ionicdeploy] 2.671003ms
2016-10-17 08:20:52.229 MyApp[48957:2591392] [CDVTimer][keyboard] 1.007974ms
2016-10-17 08:20:52.229 MyApp[48957:2591392] [CDVTimer][TotalPluginStartup] 38.982987ms
2016-10-17 08:20:52.294970 MyApp[48957:2591392] subsystem: com.apple.BackBoardServices.fence, category: App, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
2016-10-17 08:20:52.996 MyApp[48957:2591392] uuid is:
2016-10-17 08:20:52.996 MyApp[48957:2591392] ignore version:
2016-10-17 08:22:23.035435 MyApp[48957:2591392] subsystem: com.apple.UIKit, category: Touch, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-17 08:22:23.038135 MyApp[48957:2591392] subsystem: com.apple.UIKit, category: Gesture, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-17 08:22:23.047052 MyApp[48957:2591392] subsystem: com.apple.UIKit, category: GestureExclusion, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
```

**Which Ionic Version?** 2.0.0.rc0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.23
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v5.10.1
Xcode version: Xcode 8.0 Build version 8A218a 

--------------------------------

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Are you running into any errors when running `ionic build` ? From reviewing this issue it sounds like you have an error in your code that NGC should be catching.

**Comment by flamesoft** [comment]
Thanks for your quick reply. I see "Build succeeded" in the end so I didn't read through it. There are some errors during building the app. This is the log after running "ionic build ios".

```Running 'build:before' npm script before build

> ionic-hello-world@ build /Users/yan/code/MyApp
> ionic-app-scripts build

[17:41:38]  ionic-app-scripts 0.0.23
[17:41:38]  build prod started ...
[17:41:38]  clean started ...
[17:41:38]  clean finished in 24 ms
[17:41:38]  copy started ...
[17:41:38]  ngc started ...
[17:41:38]  lint started ...
[17:41:38]  copy finished in 114 ms
[17:41:39]  tslint: /Users/yan/code/MyApp/src/app/app.component.ts[10, 10]: Unused import: 'ListDetail'
/Users/yan/code/MyApp/src/app/app.component.ts[13, 10]: Unused import: 'Review'
/Users/yan/code/MyApp/src/app/app.component.ts[15, 10]: Unused import: 'About'
/Users/yan/code/MyApp/src/app/app.component.ts[17, 10]: Unused import: 'LocalDataStore'
/Users/yan/code/MyApp/src/app/app.component.ts[20, 3]: Unused import: 'FIREBASE_PROVIDERS'
/Users/yan/code/MyApp/src/app/app.component.ts[21, 3]: Unused import: 'defaultFirebase'
/Users/yan/code/MyApp/src/app/app.component.ts[22, 3]: Unused import: 'AngularFire'
/Users/yan/code/MyApp/src/app/app.component.ts[23, 3]: Unused import: 'AuthMethods'
/Users/yan/code/MyApp/src/app/app.component.ts[24, 3]: Unused import: 'AuthProviders'
/Users/yan/code/MyApp/src/app/app.component.ts[25, 3]: Unused import: 'firebaseAuthConfig'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/app/app.module.ts[24, 3]: Unused import: 'AngularFire'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/pages/dictionary/dictionary.ts[2, 41]: Unused import: 'Alert'
/Users/yan/code/MyApp/src/pages/dictionary/dictionary.ts[4, 17]: Unused import: 'AuthProviders'
/Users/yan/code/MyApp/src/pages/dictionary/dictionary.ts[4, 32]: Unused import: 'AuthMethods'
/Users/yan/code/MyApp/src/pages/dictionary/dictionary.ts[4, 45]: Unused import: 'FirebaseRef'
/Users/yan/code/MyApp/src/pages/dictionary/dictionary.ts[5, 16]: Unused import: 'FirebaseListObservable'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/pages/flash-card-list/flash-card-list.ts[2, 25]: Unused import: 'NavParams'
/Users/yan/code/MyApp/src/pages/flash-card-list/flash-card-list.ts[5, 17]: Unused import: 'AuthProviders'
/Users/yan/code/MyApp/src/pages/flash-card-list/flash-card-list.ts[5, 32]: Unused import: 'AuthMethods'
/Users/yan/code/MyApp/src/pages/flash-card-list/flash-card-list.ts[5, 45]: Unused import: 'FirebaseRef'
/Users/yan/code/MyApp/src/pages/flash-card-list/flash-card-list.ts[6, 40]: Unused import: 'FirebaseObjectObservable'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[1, 21]: Unused import: 'ViewChild'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[1, 87]: Unused import: 'ElementRef'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[1, 99]: Unused import: 'Renderer'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[2, 35]: Unused import: 'IonicModule'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[4, 17]: Unused import: 'AuthProviders'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[4, 32]: Unused import: 'AuthMethods'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[4, 45]: Unused import: 'FirebaseRef'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[5, 40]: Unused import: 'FirebaseObjectObservable'
/Users/yan/code/MyApp/src/pages/flash-cards/flash-cards.ts[125, 15]: Unused variable: 'subscription'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/pages/list-detail/list-detail.ts[5, 17]: Unused import: 'AuthProviders'
/Users/yan/code/MyApp/src/pages/list-detail/list-detail.ts[5, 32]: Unused import: 'AuthMethods'
/Users/yan/code/MyApp/src/pages/list-detail/list-detail.ts[5, 45]: Unused import: 'FirebaseRef'
/Users/yan/code/MyApp/src/pages/list-detail/list-detail.ts[6, 40]: Unused import: 'FirebaseObjectObservable'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/pages/my-list/my-list.ts[5, 17]: Unused import: 'AuthProviders'
/Users/yan/code/MyApp/src/pages/my-list/my-list.ts[5, 32]: Unused import: 'AuthMethods'
/Users/yan/code/MyApp/src/pages/my-list/my-list.ts[5, 45]: Unused import: 'FirebaseRef'
/Users/yan/code/MyApp/src/pages/my-list/my-list.ts[6, 40]: Unused import: 'FirebaseObjectObservable'
/Users/yan/code/MyApp/src/pages/my-list/my-list.ts[103, 9]: Unused variable: 'subUrl'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/pages/settings/settings.ts[26, 11]: Unused variable: 'browser'
/Users/yan/code/MyApp/src/pages/settings/settings.ts[30, 11]: Unused variable: 'browser'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/pages/signup/signup.ts[5, 10]: Unused import: 'Dictionary'

[17:41:39]  tslint: /Users/yan/code/MyApp/src/providers/firebase-data.ts[5, 19]: Unused import: 'AuthProviders'
/Users/yan/code/MyApp/src/providers/firebase-data.ts[5, 34]: Unused import: 'AuthMethods'
/Users/yan/code/MyApp/src/providers/firebase-data.ts[5, 47]: Unused import: 'FirebaseRef'
/Users/yan/code/MyApp/src/providers/firebase-data.ts[6, 42]: Unused import: 'FirebaseObjectObservable'

[17:41:40]  lint finished in 1.80 s
[17:41:41]  ngc error: Error: Error encountered resolving symbol values statically. Calling function 'defaultFirebase', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/yan/code/MyApp/.tmp/app/app.module.ts, resolving symbol AppModule in /Users/yan/code/MyApp/.tmp/app/app.module.ts
    at simplifyInContext (/Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/static_reflector.js:469:23)
    at StaticReflector.simplify (/Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/static_reflector.js:472:22)
    at StaticReflector.annotations (/Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/codegen.js:53:54)
    at CodeGenerator.readFileMetadata (/Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/codegen.js:66:13)
    at /Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (/Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/codegen.js:100:35)
    at codegen (/Users/yan/code/MyApp/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Users/yan/code/MyApp/node_modules/@angular/tsc-wrapped/src/main.js:30:16)

[17:41:41]  ngc error: Compilation failed

[17:41:41]  
[17:41:41]  bundle prod started ...
[17:41:41]  Error: Could not resolve entry (.tmp/app/main.dev.js)
    at /Users/yan/code/MyApp/node_modules/rollup/dist/rollup.js:8602:28
    at process._tickCallback (internal/process/next_tick.js:103:7)
[17:41:41]  sass started ...
[17:41:43]  sass finished in 1.80 s
[17:41:43]  minify started ...
[17:41:43]  cleancss started ...
[17:41:43]  uglifyjs started ...
[17:41:43]  Error: ENOENT: no such file or directory, open '/Users/yan/code/MyApp/www/build/main.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at addFile (/Users/yan/code/MyApp/node_modules/uglify-js/tools/node.js:68:22)
    at /Users/yan/code/MyApp/node_modules/uglify-js/tools/node.js:79:17
    at Array.forEach (native)
    at Object.exports.minify (/Users/yan/code/MyApp/node_modules/uglify-js/tools/node.js:77:26)
    at runUglifyInternal (/Users/yan/code/MyApp/node_modules/@ionic/app-scripts/dist/uglifyjs.js:34:19)
    at runUglify (/Users/yan/code/MyApp/node_modules/@ionic/app-scripts/dist/uglifyjs.js:23:28)
    at Object.uglifyjs (/Users/yan/code/MyApp/node_modules/@ionic/app-scripts/dist/uglifyjs.js:9:12)
[17:41:44]  cleancss finished in 1.18 s
[17:41:44]  minify finished in 1.18 s
[17:41:44]  build prod finished in 6.73 s
Running command: /Users/yan/code/MyApp/hooks/after_prepare/010_add_platform_class.js /Users/yan/code/MyApp


add to body class: platform-ios

Building project: /Users/yan/code/MyApp/platforms/ios/MyApp.xcodeproj


	Configuration: Debug
	Platform: emulator

Build settings from command line:

    CONFIGURATION_BUILD_DIR = /Users/yan/code/MyApp/platforms/ios/build/emulator
    SDKROOT = iphonesimulator10.0
    SHARED_PRECOMPS_DIR = /Users/yan/code/MyApp/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/yan/code/MyApp/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    IPHONEOS_DEPLOYMENT_TARGET = 8.0
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h
    TARGETED_DEVICE_FAMILY = 1,2


=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===


Check dependencies



=== BUILD TARGET MyApp OF PROJECT MyApp WITH CONFIGURATION Debug ===


Check dependencies



PhaseScriptExecution Copy\ www\ directory build/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-304B58A110DAC018002A0835.sh
    cd /Users/yan/code/MyApp/platforms/ios
    /bin/sh -c /Users/yan/code/MyApp/platforms/ios/build/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-304B58A110DAC018002A0835.sh



ProcessInfoPlistFile build/emulator/MyApp.app/Info.plist MyApp/MyApp-Info.plist
    cd /Users/yan/code/MyApp/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0@global/bin:/Users/yanzhang/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/mongodb/bin:/Users/yanzhang/.rvm/bin"
    builtin-infoPlistUtility /Users/yan/code/MyApp/platforms/ios/MyApp/MyApp-Info.plist -genpkginfo /Users/yan/code/MyApp/platforms/ios/build/emulator/MyApp.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/yan/code/MyApp/platforms/ios/build/MyApp.build/Debug-iphonesimulator/MyApp.build/MainViewController-PartialInfo.plist -additionalcontentfile /Users/yan/code/MyApp/platforms/ios/build/MyApp.build/Debug-iphonesimulator/MyApp.build/assetcatalog_generated_info.plist -o /Users/yan/code/MyApp/platforms/ios/build/emulator/MyApp.app/Info.plist



GenerateDSYMFile build/emulator/MyApp.app.dSYM build/emulator/MyApp.app/MyApp
    cd /Users/yan/code/MyApp/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0@global/bin:/Users/yanzhang/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/mongodb/bin:/Users/yanzhang/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/yan/code/MyApp/platforms/ios/build/emulator/MyApp.app/MyApp -o /Users/yan/code/MyApp/platforms/ios/build/emulator/MyApp.app.dSYM



Touch build/emulator/MyApp.app
    cd /Users/yan/code/MyApp/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0@global/bin:/Users/yanzhang/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/mongodb/bin:/Users/yanzhang/.rvm/bin"
    /usr/bin/touch -c /Users/yan/code/MyApp/platforms/ios/build/emulator/MyApp.app



CodeSign build/emulator/MyApp.app
    cd /Users/yan/code/MyApp/platforms/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0/bin:/Users/yanzhang/.rvm/gems/ruby-2.3.0@global/bin:/Users/yanzhang/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/mongodb/bin:/Users/yanzhang/.rvm/bin"
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/yan/code/MyApp/platforms/ios/build/emulator/MyApp.app

/Users/yan/code/MyApp/platforms/ios/build/emulator/MyApp.app: replacing existing signature



** BUILD SUCCEEDED **
```

**Comment by flamesoft** [comment]
@jgw96, as you have guessed, there is the "ngc" error. Before this version I have also tried to install the splashScreen plugin, but I also get long time blank screen.
The command that I have tried is 
```
cordova plugin add cordova-plugin-splashscreen
```

**Comment by ansaril3** [comment]
Remove/set lower versions for pluguns.

**Comment by flamesoft** [comment]
@ansaril3 thanks. I guess it is the Firebase which has problem. Shall I remove that plugin? But I need to use it. 
Which plugin shall I remove?
@jgw96 which is the normal way to deal with "ngc error"?

**Comment by jgw96** [comment]
Hello @flamesoft ! Thanks for the info! So it looks like you have some errors in your code. NGC is able to do error checking and type checking on methods and variables that are bound to your templates. This is the line in the output that is the error message causing NGC to throw: ```[17:41:41] ngc error: Error: Error encountered resolving symbol values statically. Calling function 'defaultFirebase', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/yan/code/MyApp/.tmp/app/app.module.ts, resolving symbol AppModule in /Users/yan/code/MyApp/.tmp/app/app.module.ts ```. I would recommend checking out [this tutorial](https://javebratt.com/ionic2rc0-firebase-angularfire2/) on using AngularFire in Ionic 2 RC1. Since this is an error in your code, and not an error in Ionic I am going to close this issue for now. Thanks!

**Comment by flamesoft** [comment]
Thanks @jgw96  for helping! If not for your help, I could wait until the final release of Ionic 2, which will take some time to make a progress. I find out that it is a problem when I import AngularFire2. I found this tutorial _https://playcode.org/getting-started-with-ionic-2-rc0-firebase-3-angularfire-2/_ which helped me to make AngularFire2 to work.
