### ISSUE TITLE
Tests are broken on branch 1.x

### ISSUE THREAD

**Issue by dennybiasiolli** [driftyco/ionic#8994]
#### Short description of the problem:

Tests are broken on branch 1.x (https://circleci.com/gh/driftyco/ionic/tree/1.x)

#### What behavior are you expecting?

PR #8893 and #8894 will solve the problem in local machines, but on CircleCI persists the problem described here (#8993)

**Steps to reproduce:**
1. clone repo (my platform is macOS Sierra)
2. checkout branch 1.x
3. npm install
4. run gulp karma and watch tests fail

**Which Ionic Version?** 1.x

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
Chrome 54.0.2840 (Mac OS X 10.12.1) $ionicSideMenus controller should have amount and percentage correct FAILED
	Expected 67 to equal 67.5.
	Error: Expected 67 to equal 67.5.
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/angular/controller/sideMenuController.unit.js:84:34)
	Expected 24.814814814814813 to equal 25.
	Error: Expected 24.814814814814813 to equal 25.
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/angular/controller/sideMenuController.unit.js:85:38)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Toggle Should disable and enable FAILED
	Expected false to be true.
	Error: Expected false to be true.
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/angular/directive/toggle.unit.js:40:26)
	Expected false to be true.
	Error: Expected false to be true.
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/angular/directive/toggle.unit.js:49:26)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Toggle Should toggle FAILED
	Expected false to be true.
	Error: Expected false to be true.
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/angular/directive/toggle.unit.js:66:26)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should trigger click on mouseup and when nearby mousedown happened FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapMouseDown (/Users/denny/git/ionic/js/utils/tap.js:9:17452)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:190:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should not trigger click on mouseup because mousedown coordinates too far away FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapMouseDown (/Users/denny/git/ionic/js/utils/tap.js:9:17452)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:212:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should set tapHasPointerMoved=false on tapTouchStart FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapTouchStart (/Users/denny/git/ionic/js/utils/tap.js:9:20525)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:220:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should set tapHasPointerMoved=true on tapTouchMove FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapTouchStart (/Users/denny/git/ionic/js/utils/tap.js:9:20525)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:278:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should set tapHasPointerMoved=false on tapMouseDown FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapMouseDown (/Users/denny/git/ionic/js/utils/tap.js:9:17452)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:286:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should set tapHasPointerMoved=true on tapMouseMove FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapMouseDown (/Users/denny/git/ionic/js/utils/tap.js:9:17452)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:298:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should trigger click on touchend and nearby touchstart happened FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapTouchStart (/Users/denny/git/ionic/js/utils/tap.js:9:20525)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:377:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should not trigger click on touchend because touchstart coordinates too far away FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapTouchStart (/Users/denny/git/ionic/js/utils/tap.js:9:20525)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:400:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should tapEnabledTouchEvents because of touchstart FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapTouchStart (/Users/denny/git/ionic/js/utils/tap.js:9:20525)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:409:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should cancel click when touchmove coordinates goes too far from touchstart coordinates FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapTouchStart (/Users/denny/git/ionic/js/utils/tap.js:9:20525)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:420:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should cancel click when touchend coordinates are too far from touchstart coordinates FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapTouchStart (/Users/denny/git/ionic/js/utils/tap.js:9:20525)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:436:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should preventDefault on touchend when the target is a select FAILED
	Expected undefined to equal true.
	Error: Expected undefined to equal true.
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:449:34)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should cancel click when mousemove coordinates goes too far from mousedown coordinates FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at tapMouseDown (/Users/denny/git/ionic/js/utils/tap.js:9:17452)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:463:5)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should not preventDefault on mousedown if the target is a select element FAILED
	Expected undefined to equal true.
	Error: Expected undefined to equal true.
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:529:36)
Chrome 54.0.2840 (Mac OS X 10.12.1) Ionic Tap Should tapIgnoreEvent false FAILED
	TypeError: Cannot read property 'tagName' of undefined
	    at tapIgnoreEvent (/Users/denny/git/ionic/js/utils/tap.js:9:24307)
	    at jasmine.Spec.<anonymous> (/Users/denny/git/ionic/test/unit/utils/tap.unit.js:1400:13)
Chrome 54.0.2840 (Mac OS X 10.12.1): Executed 932 of 932 (18 FAILED) (17.39 secs / 16.919 secs)
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#74
