### ISSUE TITLE
ionic upload An error occurred uploading the build: SyntaxError: Unexpected token < in JSON at position 2

### ISSUE THREAD

**Issue by mflmartin** [driftyco/ionic#8995]
D:\Sync\Martin\inProgress\p4q\suntrack_home>ionic upload
Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token < in JSON at position 2
--------------------------------

SyntaxError: Unexpected token < in JSON at position 2
    at Object.parse (native)
    at IncomingMessage.<anonymous> (C:\Users\marti\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\upload.js:300:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unexpected token < in JSON at position 2 (CLI v2.1.4)

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS:
Node Version: v6.9.1

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
