### ISSUE TITLE
ionic state save: TypeError: Cannot read property 'LOG_LEVEL' of null

### ISSUE THREAD

**Issue by JulienPalard** [driftyco/ionic#9102]
### Short description of the problem:

When running `ionic state save` I got an exception.

### What behavior are you expecting?

When running `ionic state save` I want it to save my state.

### Steps to reproduce
1. ionic state save

```
$ ionic state save
Saving your Ionic app state of platforms and plugins
Saved platform
There was an error saving your current Ionic setup
 TypeError: Cannot read property 'LOG_LEVEL' of null
    at /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:259:34
    at Array.forEach (native)
    at Object.saveExistingPlugins (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:250:24)
    at Object.saveState (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:73:11)
    at Object.run (/usr/lib/node_modules/ionic/lib/ionic/state.js:55:11)
    at Promise.apply (/usr/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/usr/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
```

Tested with ionic `2.0.0` and ionic `2.1.0`, ionic info:

```
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:     Debian Description:     Debian GNU/Linux 8.6 (jessie) 
Node Version: v4.6.1
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1658
