### ISSUE TITLE
command [ionic platform add ios ] run wrong

### ISSUE THREAD

**Issue by aqnaruto** [driftyco/ionic#9109]
i flowed the offical start document,and rebuild sever time s but  it is still not work 
![image](https://cloud.githubusercontent.com/assets/9067159/20177830/9b2b8756-a703-11e6-959f-87892b61d4fc.png)

```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.runr (/usr/local/lib/node_modules/ionic/lib/cli.js:191:19)
    at /usr/local/lib/node_modules/ionic/lib/cli.js:54:9
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Cannot read property 'hasOwnProperty' of undefined (CLI v2.1.7)

Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by aqnaruto** [comment]
it also do not work on windows ,android .

**Comment by aqnaruto** [comment]
i figure it out by adding`--v2` , but i think the offical document should update! it is really confused the document do not mentioned it

**Comment by malvadeza** [comment]
@aqnaruto but I think it [does](https://ionicframework.com/docs/v2/getting-started/tutorial/), at least in the documentation for the version 2.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1657
