### ISSUE TITLE
watch problem bug

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#9381]
Hello I got problem with RC3 ionic-app-script. I had updated it from 0.0.33 version to 0.0.44 and configure it to my needs. All is good but when I try to change something in templates I got error bellow.
 
```
[12:04:14]  build started ...
[12:04:14]  transpile update started ...
[12:04:14]  transpile update finished in 516 ms
[12:04:14]  webpack update started ...
D:\denwerready\-readyscript\modules\mobilesiteapp\appsourse\node_modules\@ionic\
app-scripts\dist\watch.js:225
    data.filePath = tsFiles.concat(sassFiles, htmlFiles)[0].filePath;
                                                           ^

TypeError: Cannot read property 'filePath' of undefined
    at runBuildUpdate (D:\denwerready\-readyscript\modules\mobilesiteapp\appsour
se\node_modules\@ionic\app-scripts\dist\watch.js:225:60)
    at Timeout._onTimeout (D:\denwerready\-readyscript\modules\mobilesiteapp\app
sourse\node_modules\@ionic\app-scripts\dist\watch.js:145:29)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)



npm
 ERR! Windows_NT 6.3.9600
npm
ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node
_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.9.1
npm
ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR!
 ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR!
npm ERR!
 Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     D:\denwerready\-readyscript\modules\mobilesiteapp\appsourse\npm-deb
ug.log
```
**npm-debug.log** 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ionic-hello-world@~prewatch: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prewatch: no script for prewatch, continuing
7 info lifecycle ionic-hello-world@~watch: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~watch: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\denwerready\-readyscript\modules\mobilesiteapp\appsourse\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Чубзик\AppData\Roaming\npm
10 verbose lifecycle ionic-hello-world@~watch: CWD: D:\denwerready\-readyscript\modules\mobilesiteapp\appsourse
11 silly lifecycle ionic-hello-world@~watch: Args: [ '/d /s /c', 'ionic-app-scripts watch' ]
12 silly lifecycle ionic-hello-world@~watch: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~watch: Failed to exec watch script
14 verbose stack Error: ionic-hello-world@ watch: `ionic-app-scripts watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd D:\denwerready\-readyscript\modules\mobilesiteapp\appsourse
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ionic-hello-world@ watch: `ionic-app-scripts watch`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

What in **watch.config.js**
```
var watch = require('../dist/watch');
var copy = require('../dist/copy');
var copyConfig = require('./copy.config');


// https://www.npmjs.com/package/chokidar

module.exports = {

  watchers: [

    {
      paths: [
        '{{SRC}}/**/*.(ts|tpl|scss)'
      ],
      options: { ignored: ['{{SRC}}/**/*.spec.ts', '**/*.DS_Store'] },
      callback: watch.buildUpdate
    },

    {
      paths: copyConfig.include.map(f => f.src),
      options: { ignored: '**/*.DS_Store' },
      callback: copy.copyUpdate
    }

  ]

};
```

What in **config.js**
```
var BUILD_DIR = '../build';
var SRC_DIR = 'src';
var TMP_DIR = '.tmp';
var WWW_DIR = '../view/app/www';
var WWW_INDEX_FILENAME = 'index.html';
var ENV_VAR_PROD = 'prod';
var ENV_VAR_DEV = 'dev';
var ENV_VAR_IONIC_ENV = 'IONIC_ENV';
var ENV_VAR_IONIC_DEV = 'IONIC_DEV';
var ENV_VAR_ROOT_DIR = 'IONIC_ROOT_DIR';
var ENV_VAR_TMP_DIR = 'IONIC_TMP_DIR';
var ENV_VAR_SRC_DIR = 'IONIC_SRC_DIR';
var ENV_VAR_WWW_DIR = 'IONIC_WWW_DIR';
var ENV_VAR_BUILD_DIR = 'IONIC_BUILD_DIR';
var ENV_VAR_APP_SCRIPTS_DIR = 'IONIC_APP_SCRIPTS_DIR';
var ENV_VAR_SOURCE_MAP = 'IONIC_SOURCE_MAP';
exports.BUNDLER_ROLLUP = 'rollup';
exports.BUNDLER_WEBPACK = 'webpack';

```
What in **copy.config.js**
```
// https://www.npmjs.com/package/fs-extra

module.exports = {
  include: [
    {
      src: '{{SRC}}/assets/',
      dest: '{{WWW}}/../assets/'
    },
    {
      src: '{{SRC}}/app/',
      dest: '{{WWW}}/../app/'
    },
    {
      src: '{{SRC}}/pages/',
      dest: '{{WWW}}/../pages/'
    },
    {
      src: '{{SRC}}/index.html',
      dest: '{{WWW}}/index.tpl'
    },
    {
      src: '{{SRC}}/manifest.json',
      dest: '{{WWW}}/manifest.json'
    },
    {
      src: '{{SRC}}/service-worker.js',
      dest: '{{WWW}}/service-worker.js'
    },
    {
      src: 'node_modules/jquery/dist/jquery.js',
      dest: '{{WWW}}/../build/jquery.min.js'
    },
    {
      src: 'node_modules/ionic-angular/polyfills/polyfills.js',
      dest: '{{BUILD}}/polyfills.js'
    },
    {
      src: 'node_modules/ionicons/dist/fonts/',
      dest: '{{WWW}}/../assets/fonts/'
    },
  ]
};

```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#485
