### ISSUE TITLE
ionic 2 update from rc2.0 to rc3 serve error

### ISSUE THREAD

**Issue by ykonstant** [driftyco/ionic#9425]
ionic-hello-world@ ionic:serve /Applications/XAMPP/xamppfiles/htdocs/huntfishshare
> ionic-app-scripts serve

[19:10:13]  ionic-app-scripts 0.0.45 
[19:10:13]  watch started ... 
[19:10:13]  build dev started ... 
[19:10:13]  clean started ... 
[19:10:13]  clean finished in less than 1 ms 
[19:10:13]  copy started ... 
[19:10:13]  transpile started ... 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/XAMPP/xamppfiles/htdocs/huntfishshare/npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

**Comment by manucorporat** [comment]
EADDRINUSE, stands for "address already in use", you probably have another ionic serve running in the background using the same TCP port. Close it and try again

**Comment by ykonstant** [comment]
thanks, 
port is already in used
i used
sudo lsof -i :<port> for listing
sudo kill -9 <PID> for free port
It resolves my problem
thanks, again
