### ISSUE TITLE
Cannot install ionic through npm

### ISSUE THREAD

**Issue by phuongnd08** [driftyco/ionic#950]
Run `sudo npm install -g ionic`
Getting this:

```
npm http 304 https://registry.npmjs.org/colors
npm ERR! Error: No compatible version found: colors@'^0.6.2'
npm ERR! Valid install targets:
npm ERR! ["0.3.0","0.5.0","0.5.1","0.6.0","0.6.0-1","0.6.1","0.6.2"]
npm ERR!     at installTargetsError (/usr/local/Cellar/node/0.10.4/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/Cellar/node/0.10.4/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/Cellar/node/0.10.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/Cellar/node/0.10.4/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! cwd /Users/phuongnd08/code/vax
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
```

Any thoughts?

**Comment by roymj88** [comment]
@phuongnd08 :  Can you specify the versions to which node and npm where upgraded that resolved the issue?

My versions are:

Node: **0.12.5**
npm: **2.11.2**
