### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by Neo110** [driftyco/ionic#9648]
Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

* What went wrong:

A problem occurred configuring root project 'android'.

> Could not resolve all dependencies for configuration ':classpath'.

   > Could not find com.android.tools.build:gradle:2.2.2.

     Searched in the following locations:

         https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.pom

         https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.jar

     Required by:

         :android:unspecified

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by graphefruit** [comment]
This issue is not related to ionic, rather a wrong setup on your mac.

Have a look here: http://www.androidcentral.com/installing-android-sdk-windows-mac-and-linux-tutorial

**Comment by Neo110** [comment]
not wok . I watch you link .but not work.

**Comment by Neo110** [comment]
add to body class: platform-android

ANDROID_HOME=/Users/zhengbin/Library/Android/sdk

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home

Unzipping /Users/zhengbin/.gradle/wrapper/dists/gradle-2.2.1-all/5dcjnkdtnc8g20eqolsmbk9psn/gradle-2.2.1-all.zip to /Users/zhengbin/.gradle/wrapper/dists/gradle-2.2.1-all/5dcjnkdtnc8g20eqolsmbk9psn

Exception in thread "main"
java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:160)
	at org.gradle.wrapper.Install.access$400(Install.java:29)
	at org.gradle.wrapper.Install$1.call(Install.java:70)

	at org.gradle.wrapper.Install$1.call(Install.java:47)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	... 3 more

Error: Error code 1 for command: /Users/zhengbin/Documents/Workspace/Ionic/gongdy/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/zhengbin/Documents/Workspace/Ionic/gongdy/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

**Comment by jayeshanandani** [comment]
This is not an ionic issue. Please ask on either Ionic forums or StackOverflow.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by kangkangding** [comment]
I'm the same issue    , help me
