### ISSUE TITLE
build dev failed: Cannot read property 'indexOf' of undefined 

### ISSUE THREAD

**Issue by stefdelec** [driftyco/ionic#9692]
Impossible to "serve".
I got this error only on brand new project but not older ones.
` build dev failed: Cannot read property 'indexOf' of undefined `

**Ionic version:** 
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.1 Build version 8B62

npm 4.0.5

[ ] bug report
```
$ ionic serve

> ionic-hello-world@ ionic:serve /Users/Stephane/Downloads/MyProject
> ionic-app-scripts serve

[20:09:16]  ionic-app-scripts 0.0.47 
[20:09:16]  watch started ... 
[20:09:16]  build dev started ... 
[20:09:16]  clean started ... 
[20:09:16]  clean finished in 4 ms 
[20:09:16]  copy started ... 
[20:09:16]  transpile started ... 
[20:09:20]  build dev failed: Cannot read property 'indexOf' of undefined 
[20:09:20]  dev server running: http://localhost:8100/ 

[20:09:20]  copy finished in 4.32 s 
[20:09:20]  watch ready in 4.34 s 
```

Debug file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ionic:build',
1 verbose cli   '--' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'preionic:build', 'ionic:build', 'postionic:build' ]
5 info lifecycle ionic-hello-world@~preionic:build: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:build: no script for preionic:build, continuing
7 info lifecycle ionic-hello-world@~ionic:build: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Stephane/Downloads/MyProject/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle ionic-hello-world@~ionic:build: CWD: /Users/Stephane/Downloads/MyProject
11 silly lifecycle ionic-hello-world@~ionic:build: Args: [ '-c', 'ionic-app-scripts build' ]
12 silly lifecycle ionic-hello-world@~ionic:build: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~ionic:build: Failed to exec ionic:build script
14 verbose stack Error: ionic-hello-world@ ionic:build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /Users/Stephane/Downloads/MyProject
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by lufias** [comment]
Are you using ion-img? Using debugger, my indexOf error was thrown trying to load an ion-img src using a promise.. 

https://github.com/driftyco/ionic/issues/9691

**Comment by stefdelec** [comment]
I am not using anything.
I creating a new project and then serve.

`ionic start myproject tabs --v2 --ts`


...

```
cd myproject
ionic serve
```

**Comment by jayeshanandani** [comment]
Please try by updating ionic-app-scripts to 0.0.48 and ensure you have deleted node_modules folder and reinstalled again for safety check.

**Comment by stefdelec** [comment]
how to update  ionic-app-scripts ?
`npm  ionic-app-scripts --update` ?

**Comment by jayeshanandani** [comment]
You can try by `npm install @ionic/app-scripts@latest --save-dev`

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#597
