### ISSUE TITLE
Ionic upload does not work after first time

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic#9700]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The first time ionic upload works well but as soon as ionic.project file is created and the app id is saved to bundle the next upload starts failing with error message 
Error: Cannot find module '/Users/ajasingh/Uwork/EdumyApp/ionic.config.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.run (/Users/ajasingh/.nvm/versions/node/v0.12.11/lib/node_modules/ionic/lib/cli.js:131:20)
    at Object.<anonymous> (/Users/ajasingh/.nvm/versions/node/v0.12.11/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Expected behavior:**

The app should upload second time also
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Error: Cannot find module '/Users/ajasingh/Uwork/EdumyApp/ionic.config.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.run (/Users/ajasingh/.nvm/versions/node/v0.12.11/lib/node_modules/ionic/lib/cli.js:131:20)
    at Object.<anonymous> (/Users/ajasingh/.nvm/versions/node/v0.12.11/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Cannot find module '/Users/ajasingh/Uwork/EdumyApp/ionic.config.js' (CLI v2.0.0-beta.19)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Version: 2.0.0-rc.4
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.11
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1799
