### ISSUE TITLE
Ionic serve fails...

### ISSUE THREAD

**Issue by murshid1988** [driftyco/ionic#9703]
Ionic serve started failing in PC...

This is the npm-debug I am getting. What could be the issue?

**Ionic 2.1.17
cordova 6.4.0
node 6.9.2**

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/murshid/.nvm/versions/node/v6.9.2/bin/node',
1 verbose cli   '/home/murshid/.nvm/versions/node/v6.9.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--',
1 verbose cli   '--lab' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:serve: PATH: /home/murshid/.nvm/versions/node/v6.9.2/lib/node_modules/npm/bin/node-gyp-bin:/home/murshid/Documents/Ionic/CalConnectV2/node_modules/.bin:/home/murshid/.nvm/versions/node/v6.9.2/bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/bin/robomongo/bin:/home/murshid/Android/Sdk/tools:/home/murshid/Android/Sdk/platform-tools:/opt/gradle-3.1/bin:/opt/gradle-3.1/bin
10 verbose lifecycle ionic-hello-world@~ionic:serve: CWD: /home/murshid/Documents/Ionic/CalConnectV2
11 silly lifecycle ionic-hello-world@~ionic:serve: Args: [ '-c', 'ionic-app-scripts serve "--lab"' ]
12 silly lifecycle ionic-hello-world@~ionic:serve: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--lab"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/murshid/.nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/murshid/.nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /home/murshid/Documents/Ionic/CalConnectV2
17 error Linux 4.4.0-53-generic
18 error argv "/home/murshid/.nvm/versions/node/v6.9.2/bin/node" "/home/murshid/.nvm/versions/node/v6.9.2/bin/npm" "run" "ionic:serve" "--" "--lab"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--lab"`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--lab"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve "--lab"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#598
