### ISSUE TITLE
cannot use AlertController from a service in dev mode

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic#9854]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Injecting the `AlertController` in a service works while in production mode, but not in dev mode.

**Expected behavior:**

I should be able to use the `AlertController` within a service to create alerts in both prod or dev mode.

**Steps to reproduce:**

I made a simple service in order to keep track of all the alerts being presented (visible). The reason I use such a service is because I could not find an API that I could use to detect whether there is a certain alert presented (visible) or not.

**Related code:**

```ts
import {Injectable} from '@angular/core';
import {AlertController, AlertOptions, Alert} from 'ionic-angular';
import {Observable} from 'rxjs/Observable';
import {BehaviorSubject} from 'rxjs/BehaviorSubject';
import {randomStr} from './utils';


export interface AlertItem {
	id: string | symbol;
	instance: Alert;
}


@Injectable()
export class AlertsService {
	private stack: AlertItem[] = [];
	private currentStackSource: BehaviorSubject<AlertItem[]> = new BehaviorSubject<AlertItem[]>([]);
	currentStack: Observable<AlertItem[]> = this.currentStackSource.asObservable(); // tslint:disable-line:member-ordering

	constructor(private alert: AlertController) {}

	create(options?: AlertOptions, id?: string | symbol): Alert {
		const alert = this.alert.create(options);

		if (!id) {
			id = randomStr();
		}

		this.stack.push({id, instance: alert});
		this.currentStackSource.next(this.stack);

		alert.onDidDismiss(() => {
			const index = this.stack.findIndex((item) => item.id === id);
			if (index !== -1) {
				this.stack.splice(index, 1);
				this.currentStackSource.next(this.stack);
			}
		});

		return alert;
	}
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Are you getting an error when this happens?

**Comment by rolandjitsu** [comment]
@jgw96 oh yes, sorry for not adding it:
```text
Error: Can't resolve all parameters for NfcTagManagementPage: (NavController, NavParams, ActionSheetController, ?).
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:8100/build/main.js:25777:19)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:8100/build/main.js:25671:26)
    at Array.map (native)
    at CompileMetadataResolver._loadNgModuleMetadata (http://localhost:8100/build/main.js:25588:18)
    at CompileMetadataResolver.loadNgModuleMetadata (http://localhost:8100/build/main.js:25467:29)
    at RuntimeCompiler._loadModules (http://localhost:8100/build/main.js:28267:41)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:8100/build/main.js:28237:35)
    at RuntimeCompiler.compileModuleAsync (http://localhost:8100/build/main.js:28227:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:8100/build/main.js:7619:25)
    at http://localhost:8100/build/main.js:113786:6
```

Note that it never tells me that `AlertController` cannot be resolved or anything else. But it does seem to work if I remove the `AlertController` as a dependency from the service I pasted in the post.

**Comment by rolandjitsu** [comment]
I am just curious if it's the case that I cannot use `AlertController` in an injected service, the same as I cannot use `NavController` ([#9581](https://github.com/driftyco/ionic/issues/9581)).

**Comment by rolandjitsu** [comment]
I also wonder if there is a simpler way of checking if we are currently presenting an alert? Because using `NavController.getActive()` does not work.

**Comment by rolandjitsu** [comment]
I actually discovered that using the `AlertController` in a service that is injected in another service causes this issue.
So I have a `TagsService`:
```ts
import {Injectable} from '@angular/core';
import {NFC, Ndef} from 'ionic-native';
import {Platform, ToastController, AlertController} from 'ionic-angular';

import {Observable} from 'rxjs/Observable';
import {BehaviorSubject} from 'rxjs/BehaviorSubject';
import 'rxjs/add/observable/empty';
import 'rxjs/add/observable/fromPromise';
import 'rxjs/add/observable/never';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/take';

import {AlertsService} from './alerts.service';


export interface Tag {
	id: number[];
	canMakeReadOnly: boolean;
	isWritable: boolean;
	type: string;
	techTypes: string[];
	maxSize: number;
}


export const LINK_APP_ALERT_ID = Symbol.for('Infarm.LinkAppAlertId');


/**
 * @returns True if all passed tags are the same.
 */
export function areTagsEqual(...tags: any[]): boolean {
	return tags.reduce((a, b) => tagToHexString(a) === tagToHexString(b));
}


/**
 * @returns A string of shape 40:8C:8B:00.
 */
export function tagToHexString(tag: Tag): string {
	const {id} = tag || {} as Tag;
	if (!id) {
		return '';
	}
	return `${NFC.bytesToHexString(id)}`.replace(/(.{2})/g, '$1:')
		.slice(0, -1)
		.toUpperCase();
}


// Requires Cordova plugin [phonegap-nfc](https://ionicframework.com/docs/v2/native/nfc/)
@Injectable()
export class TagsService {
	private enabledSource: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
	enabled: Observable<boolean> = this.enabledSource.asObservable(); // tslint:disable-line:member-ordering

	constructor(
		private platform: Platform,
		private toast: ToastController,
		private alert: AlertController
		// private alerts: AlertsService
	) {
		Observable.fromPromise(this.platform.ready())
			.mergeMap(() => Observable.fromPromise(NFC.enabled()))
			.catch(() => Observable.of(false))
			.subscribe((isNfcEnabled) => {
				this.enabledSource.next(isNfcEnabled);
			});
	}

	discover(): Observable<Tag> {
		return this.enabled.switchMap((isNfcEnabled): any => isNfcEnabled ? NFC.addNdefListener() : Observable.never())
			.map(({tag}) => tag);
	}

	appRecord(): Observable<any> {
		return this.enabled.switchMap((isNfcEnabled): any => {
			if (isNfcEnabled) {
				return Observable.of(Ndef.androidApplicationRecord('com.infarm.maintenance'));
			}
			return Observable.empty();
		});
	}

	link(tag: Tag): Observable<void> {
		const obs = Observable.create((observer) => {
			const alert = this.alert.create({
				title: 'Link app to tag',
				message: `If you'd like to link this tag to the app, please approach and keep the tag near the phone.`
			});

			const sub = this.discover()
				.switchMap((t) => {
					if (areTagsEqual(tag, t)) {
						return Observable.of(tag);
					}

					this.toast.create({
							message: 'Please use the same tag that was used for association.',
							duration: 3500
						})
						.present();

					return Observable.never();
				})
				.take(1)
				.mergeMap(() => this.appRecord())
				.mergeMap((appRecord) => Observable.fromPromise(NFC.write([appRecord])))
				.mergeMap(() => Observable.fromPromise(alert.dismiss()))
				.subscribe(() => {
					const toast = this.toast.create({
						message: 'Successfully linked tag to app.',
						duration: 3500
					});
					toast.present()
						.then(() => {
							observer.next();
							observer.complete();
						});
				}, () => {
					const toast = this.toast.create({
						message: 'Unable to link tag to app.',
						duration: 3500
					});
					toast.present()
						.then(() => {
							observer.error();
							observer.complete();
						});
				});

			alert.addButton({
				text: 'Skip',
				handler: () => {
					sub.unsubscribe();
					alert.dismiss()
						.then(() => {
							observer.complete();
						});
					return false;
				}
			});
			alert.present();
		});

		return obs.share();
	}
}
```

Which works fine as long as I don't add the `AlertsService` dependency. As soon as I add it, I get the error in the comment above.

**Comment by jgw96** [comment]
Thanks for all the info. So after reviewing this it looks like a dependency issue with your Angular DI setup. Could you try injecting your `AlertsService` into your above injectable using `@Inject` ? The code to do this should looks something like `constructor(@Inject(AlertsService) alertService: AlertsService)`. 

PS: Here is a good article on dependency injection in Angular that shows a good example of using `@Inject` along with the technicalities behind it. http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html

**Comment by rolandjitsu** [comment]
That does not fix the issue though.

**Comment by rolandjitsu** [comment]
But I think I found the issue. It occurs because of DI indeed, somewhere along the way there are two files that import stuff from each other. Thanks for the help. I was very confused though that in prod mode, this issue slips without any notice.

**Comment by jgw96** [comment]
Glad you found the issue! Most likely it was not triggering an error in production mode because angular does not run checks for certain DI things in prod mode that it does in dev mode for performance reasons.
