### ISSUE TITLE
Unable to build Ionic from source (1.x)

### ISSUE THREAD

**Issue by sryze** [driftyco/ionic#9952]
[Build instructions in README](https://github.com/driftyco/ionic/tree/1.x#development) at 1.x branch seem outdated: `gulp build` task doesn't exist anymore and other tasks that I tried fail with errors:

`gulp release, gulp nightly`:

```
[17:13:10] Starting 'nightly'...
[17:13:10] Starting 'release.pullLatest'...
[17:13:11] Finished 'release.pullLatest' after 1.38 s
[17:13:11] Starting 'validate'...
[17:13:11] Starting 'clean'...
[17:13:12] Finished 'clean' after 1.22 s
[17:13:12] Starting 'lint.sass'...
[17:13:12] Starting 'lint.ts'...
[17:13:12] Starting 'test.assembleVendorJs'...
[17:13:12] Starting 'compile.karma'...
Fatal undefined
```

`gulp compile.release`:

```
Removing debug statements: /Users/sergey/OpenSource/ionic/dist/ionic-angular

Error: Unexpected value 'LoadingCmp' declared by the module 'IonicModule'
    at /Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:14722:29
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:14702:56)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (/Users/sergey/OpenSource/ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
Compilation failed
```

How do you build ionic v1 from source (to try in inside an app and possibly patch something)?

**Comment by sryze** [comment]
Forget it, forgot to switch git branch (was using master).

**Comment by k1dbl4ck** [comment]
Can we re-open? Having this issue building master.
